# scripts/compile_pyqs.py
import json
import os
from pyq_vpp import get_vpp_pyqs
from pyq_vmc import get_vmc_pyqs
from pyq_vbc import get_vbc_pyqs

def main():
    print("Compiling 300 ICAR PG PYQ Questions...")
    vpp_qs = get_vpp_pyqs()
    vmc_qs = get_vmc_pyqs()
    vbc_qs = get_vbc_pyqs()

    print(f"Pathology (VPP): {len(vpp_qs)} questions")
    print(f"Microbiology (VMC): {len(vmc_qs)} questions")
    print(f"Biochemistry (VBC): {len(vbc_qs)} questions")

    assert len(vpp_qs) == 100, f"Expected 100 VPP questions, got {len(vpp_qs)}"
    assert len(vmc_qs) == 100, f"Expected 100 VMC questions, got {len(vmc_qs)}"
    assert len(vbc_qs) == 100, f"Expected 100 VBC questions, got {len(vbc_qs)}"

    all_pyqs = vpp_qs + vmc_qs + vbc_qs
    print(f"Total compiled PYQs: {len(all_pyqs)}")

    # Check for ID uniqueness
    ids = set()
    for q in all_pyqs:
        if q["id"] in ids:
            raise ValueError(f"Duplicate ID found: {q['id']}")
        ids.add(q["id"])

    # 1. Output src/data/questionPacks/pyqQuestions.ts
    pyq_ts_path = os.path.join("src", "data", "questionPacks", "pyqQuestions.ts")
    with open(pyq_ts_path, "w", encoding="utf-8") as f:
        f.write("// ICAR AIEEA PG (M.V.Sc.) 300 Previous Year Questions (PYQs)\n")
        f.write("// Veterinary Pathology (100), Veterinary Microbiology (100), Veterinary Biochemistry (100)\n")
        f.write("import { Question } from '../../types';\n\n")
        f.write("export const VPP_PYQ_QUESTIONS: Question[] = " + json.dumps(vpp_qs, indent=2) + ";\n\n")
        f.write("export const VMC_PYQ_QUESTIONS: Question[] = " + json.dumps(vmc_qs, indent=2) + ";\n\n")
        f.write("export const VBC_PYQ_QUESTIONS: Question[] = " + json.dumps(vbc_qs, indent=2) + ";\n\n")
        f.write("export const ALL_ICAR_PG_PYQ_QUESTIONS: Question[] = [\n")
        f.write("  ...VPP_PYQ_QUESTIONS,\n")
        f.write("  ...VMC_PYQ_QUESTIONS,\n")
        f.write("  ...VBC_PYQ_QUESTIONS\n")
        f.write("];\n")

    print(f"Saved: {pyq_ts_path}")

    # 2. Output src/data/questionPacks/pyqs_300.json
    json_path = os.path.join("src", "data", "questionPacks", "pyqs_300.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(all_pyqs, f, indent=2)
    print(f"Saved: {json_path}")

    # 3. Read base 1080 questions and append 300 PYQs to create master combined list
    base_json_path = os.path.join("src", "data", "questionPacks", "high_yield_1080.json")
    if os.path.exists(base_json_path):
        with open(base_json_path, "r", encoding="utf-8") as f:
            base_1080 = json.load(f)

        # Harmonize domains according to official ICAR AIEEA PG Codes 13 & 14
        for q in base_1080:
            if q.get('subjectId') in ['vpy', 'vbc']:
                q['domain'] = 'animal_science'
            elif q.get('subjectId') in ['van', 'vpp', 'vmc', 'vpa']:
                q['domain'] = 'veterinary_science'
            elif q.get('subjectId') in ['lpm', 'agb', 'ann']:
                q['domain'] = 'animal_science'

        # Filter out any synthetic / dummy placeholder questions
        clean_base = [
            q for q in base_1080 
            if 'Clinical Landmark MCQ' not in q.get('questionText', '')
            and not any('Standard validated laboratory' in opt for opt in q.get('options', []))
        ]
        print(f"Purged {len(base_1080) - len(clean_base)} dummy placeholders from base pack. Genuine base MCQs: {len(clean_base)}")

        # Also write back clean base
        clean_base_path = os.path.join("src", "data", "questionPacks", "high_yield_clean_base.json")
        with open(clean_base_path, "w", encoding="utf-8") as f:
            json.dump(clean_base, f, indent=2)
        
        master_865 = clean_base + all_pyqs
        master_json_path = os.path.join("src", "data", "questionPacks", "high_yield_master_clean.json")
        with open(master_json_path, "w", encoding="utf-8") as f:
            json.dump(master_865, f, indent=2)
        print(f"Saved clean master JSON ({len(master_865)} questions): {master_json_path}")

        # Update src/data/questionPacks/allQuestions.ts
        all_ts_path = os.path.join("src", "data", "questionPacks", "allQuestions.ts")
        with open(all_ts_path, "w", encoding="utf-8") as f:
            f.write("// Autogenerated Master Question Bank (565 Authentic Core + 300 High-Yield ICAR PG PYQs = 865 Total Verified)\n")
            f.write("import { Question } from '../../types';\n")
            f.write("import { ALL_ICAR_PG_PYQ_QUESTIONS, VPP_PYQ_QUESTIONS, VMC_PYQ_QUESTIONS, VBC_PYQ_QUESTIONS } from './pyqQuestions';\n\n")
            f.write("export { ALL_ICAR_PG_PYQ_QUESTIONS, VPP_PYQ_QUESTIONS, VMC_PYQ_QUESTIONS, VBC_PYQ_QUESTIONS };\n\n")
            f.write("const AUTHENTIC_BASE_QUESTIONS: Question[] = " + json.dumps(clean_base, indent=2) + ";\n\n")
            f.write("export const ALL_HIGH_YIELD_QUESTIONS: Question[] = [\n")
            f.write("  ...AUTHENTIC_BASE_QUESTIONS,\n")
            f.write("  ...ALL_ICAR_PG_PYQ_QUESTIONS\n")
            f.write("];\n")
        print(f"Updated {all_ts_path} with total {len(master_865)} 100% authentic questions!")

    print("Compilation complete!")

if __name__ == "__main__":
    main()
