# scripts/compile_all_1080.py
import json
import os
from data_van import get_van_questions
from data_vpy import get_vpy_questions
from data_vbc import get_vbc_questions
from data_lpm import get_lpm_questions
from data_vpp import get_vpp_questions
from data_vmc import get_vmc_questions
from data_vpa import get_vpa_questions
from data_agb import get_agb_questions
from data_ann import get_ann_questions

def compile_all():
    subjects = [
        ("van", "Veterinary Anatomy", get_van_questions),
        ("vpy", "Veterinary Physiology", get_vpy_questions),
        ("vbc", "Veterinary Biochemistry", get_vbc_questions),
        ("lpm", "Livestock Production Management", get_lpm_questions),
        ("vpp", "Veterinary Pathology", get_vpp_questions),
        ("vmc", "Veterinary Microbiology", get_vmc_questions),
        ("vpa", "Veterinary Parasitology", get_vpa_questions),
        ("agb", "Animal Genetics & Breeding", get_agb_questions),
        ("ann", "Animal Nutrition", get_ann_questions),
    ]

    all_questions = []
    print("==================================================")
    print("Compiling 120 Most Important Questions Per Subject")
    print("==================================================")

    for code, name, fn in subjects:
        qs = fn()
        count = len(qs)
        print(f"[{code.upper()}] {name}: {count} questions loaded.")
        all_questions.extend(qs)

    print("--------------------------------------------------")
    print(f"Total High-Yield Questions Compiled: {len(all_questions)}")
    print("==================================================")

    # 1. Output JSON pack
    json_path = os.path.join(os.path.dirname(__file__), "..", "src", "data", "questionPacks", "high_yield_1080.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(all_questions, f, indent=2, ensure_ascii=False)
    print(f"Saved JSON pack to: {json_path}")

    # 2. Output TypeScript module for direct zero-latency app bundle
    ts_path = os.path.join(os.path.dirname(__file__), "..", "src", "data", "questionPacks", "allQuestions.ts")
    with open(ts_path, "w", encoding="utf-8") as f:
        f.write("// Autogenerated High-Yield Question Bank (120 Questions x 9 Subjects = 1,080 Total)\n")
        f.write("import { Question } from '../../types';\n\n")
        f.write("export const ALL_HIGH_YIELD_QUESTIONS: Question[] = ")
        f.write(json.dumps(all_questions, indent=2, ensure_ascii=False))
        f.write(";\n")
    print(f"Saved TypeScript bundle to: {ts_path}")

if __name__ == "__main__":
    compile_all()
