# scripts/data_lpm.py
# 120 High-Yield Questions for Livestock Production Management (LPM)

def get_lpm_questions():
    questions = []

    raw_lpm = [
        # 1-30: Housing & Space Standards (BIS Norms)
        ("According to Bureau of Indian Standards (BIS) norms, what is the optimum covered floor space requirement for an adult dairy cow in a loose housing system?",
         ["3.5 square meters (approx 35-40 sq. ft.)", "7.0 square meters", "1.5 square meters", "10.0 square meters"],
         0, "Under BIS standards for loose housing, an adult cow requires 3.5 m2 of covered floor space and 7.0 m2 of open paddock area."),
        ("What is the BIS standard open paddock space requirement for an adult dairy buffalo in a loose housing system?",
         ["8.0 to 10.0 square meters", "4.0 square meters", "2.0 square meters", "15.0 square meters"],
         0, "Buffaloes require slightly more area than cows: 4.0 m2 covered floor space and 8.0 m2 open paddock area per adult animal."),
        ("What is the recommended covered floor space for a breeding bull in a dedicated bull shed?",
         ["12.0 square meters", "3.5 square meters", "5.0 square meters", "20.0 square meters"],
         0, "Breeding bulls require an individual pen with at least 12.0 m2 covered area and 120.0 m2 open exercise paddock."),
        ("The recommended floor space for a calving box (maternity pen) for a pregnant cow is:",
         ["10 to 12 square meters", "3.5 square meters", "5.0 square meters", "25 square meters"],
         0, "A maternity pen must provide 10-12 m2 of clean, well-bedded covered space to facilitate safe parturition and dam-calf bonding."),
        ("What is the recommended covered floor space requirement for an adult breeding ewe or doe (sheep/goat)?",
         ["1.0 to 1.5 square meters", "3.5 square meters", "0.5 square meters", "4.0 square meters"],
         0, "Adult sheep and goats require 1.0-1.5 m2 of covered pen area and 2.0-3.0 m2 of open run area."),
        ("In tropical India, what is the ideal longitudinal orientation for livestock sheds (dairy, poultry) to minimize solar heat gain?",
         ["East-West axis", "North-South axis", "Northeast-Southwest", "Northwest-Southeast"],
         0, "Aligning the long axis East-West ensures the roof shades the interior from direct solar radiation during peak midday hours in the northern hemisphere."),
        ("The minimum recommended height of the roof at the eaves in a gable-roof dairy barn in hot-dry zones is:",
         ["3.0 meters (approx 10 feet)", "1.5 meters", "4.5 meters", "2.0 meters"],
         0, "An eave height of 3.0 m (10 ft) with a central ridge height of 4.5-5.0 m ensures effective convective stack-effect natural ventilation."),
        ("The recommended floor space for commercial broiler chickens in deep litter housing up to 6 weeks of age is:",
         ["1.0 square foot (0.09 square meters) per bird", "0.25 square feet", "2.5 square feet", "5.0 square feet"],
         0, "Modern commercial broilers require approximately 1.0 sq. ft. of floor space per bird from 3 to 6 weeks under tropical management."),
        ("For commercial egg-type layers in deep litter housing, the recommended floor space per bird is approximately:",
         ["1.8 to 2.0 square feet", "0.5 square feet", "3.5 square feet", "0.8 square feet"],
         0, "Layer hens reared on deep litter require 1.8 to 2.0 sq. ft. per bird to prevent overcrowding and behavioral vices."),

        # 31-60: Dairy & Buffalo Management Practices
        ("The ideal method of hand milking in dairy cows that avoids damaging the teat tissue and sphincter is:",
         ["Full-hand milking (fisting)", "Stripping", "Knuckling", "Thumb milking"],
         0, "Full-hand milking presses the teat against the palm using all fingers uniformly, avoiding localized trauma caused by knuckling or friction from stripping."),
        ("Knuckling (bending the thumb against the teat body during milking) is strongly discouraged because it:",
         ["Causes bruising of the teat cistern and teat canal stenosis/mastitis", "Takes too much time", "Causes low fat percentage", "Spills milk"],
         0, "Knuckling exerts concentrated mechanical pressure on the teat mucosa, predisposing to teat spider, mucosal tears, and mastitis."),
        ("In automated machine milking of cows, what is the standard operational vacuum level at the claw?",
         ["50 kPa (approx 380 mmHg / 15 inches of Hg)", "20 kPa", "80 kPa", "100 kPa"],
         0, "Standard pipeline milking machines for dairy cows operate at 48-50 kPa (380 mmHg), while small ruminants operate at lower vacuum (38-40 kPa)."),
        ("The standard pulsation ratio in dairy cow milking machines is typically set to:",
         ["60:40 (60% milk phase : 40% rest phase)", "50:50", "90:10", "30:70"],
         0, "A 60:40 pulsation ratio provides adequate milk extraction while maintaining cyclic blood circulation in the teat tip during the rest phase."),
        ("Colostrum must be fed to a newborn calf as early as possible after birth, ideally within the first:",
         ["1 to 2 hours of life", "24 hours", "48 hours", "12 hours"],
         0, "Intestinal absorption of macromolecular colostral immunoglobulins (IgG) via pinocytosis is maximal during the first 2-4 hours and rapidly declines (gut closure at 24 hrs)."),
        ("The recommended volume of colostrum to be fed to a newborn calf within the first 12 hours of life is:",
         ["10% of the calf's body weight (approx 3 to 4 liters)", "1% of body weight", "25% of body weight", "500 ml only"],
         0, "Feeding 10% of birth weight (e.g. 3-4 liters for a 35 kg calf) ensures absorption of >150-200 g of IgG, conferring protective passive immunity (>10 g/L serum IgG)."),
        ("The California Mastitis Test (CMT) detects subclinical mastitis by reacting with:",
         ["DNA of somatic cells (leukocytes) forming a viscous gel", "Milk fat globules", "Lactose crystals", "Casein micelles"],
         0, "CMT reagent contains alkyl aryl sulfonate detergent that lyses leukocyte cell membranes, releasing nuclear DNA to form a purple gelatinous mass proportional to somatic cell count."),
        ("The recommended duration of the 'dry period' for an adult high-yielding dairy cow before the next calving is:",
         ["60 days (approx 8 weeks)", "10 days", "120 days", "Zero days (continuous milking)"],
         0, "A 60-day dry period allows complete involution, senescence, and regeneration of mammary alveolar epithelial cells for optimal milk yield in the subsequent lactation."),
        ("Debudding (disbudding) of dairy calves using a hot-iron cautery should ideally be performed at:",
         ["7 to 15 days of age (before the horn bud adheres to frontal bone)", "6 months of age", "1 year of age", "At birth immediately"],
         0, "Chemical or thermal debudding is most humane and effective before 2 weeks of age while the horn bud is still free-floating in the skin."),
        ("Castration of male calves using a Burdizzo bloodless castrator achieves sterility by:",
         ["Crushing the spermatic cord and testicular blood vessels without breaking the skin", "Surgical excision of testicles", "Applying rubber elastrator bands", "Chemical injection"],
         0, "The Burdizzo castrator crushes the vas deferens and internal spermatic artery within the scrotum, causing testicular atrophy while preserving scrotal skin integrity."),
        ("The gestation period of the domestic buffalo (Bubalus bubalis) is approximately:",
         ["310 days (approx 10 months 10 days)", "280 days", "114 days", "150 days"],
         0, "Buffalo gestation averages 310 days (range 305-315 days), significantly longer than the bovine gestation period (280-285 days)."),
        ("The gestation period of the domestic cow (Bos indicus / Bos taurus) is approximately:",
         ["280 to 285 days (approx 9 months 9 days)", "310 days", "150 days", "336 days"],
         0, "Bovine gestation averages 280-285 days, varying slightly by breed (longer in Zebu and male calves)."),
        ("The gestation period of sheep and goats is approximately:",
         ["148 to 152 days (approx 5 months)", "280 days", "114 days", "60 days"],
         0, "Both sheep and goats have a gestation length of ~150 days (5 months minus 5 days)."),
        ("The gestation period of the domestic pig (sow) is classically remembered as:",
         ["114 days (3 months, 3 weeks, and 3 days)", "280 days", "60 days", "150 days"],
         0, "Porcine gestation is remarkably consistent across breeds at 114 days (range 112-116 days)."),
        ("The gestation period of the domestic horse (mare) is approximately:",
         ["335 to 345 days (approx 11 months)", "280 days", "150 days", "390 days"],
         0, "Equine gestation averages ~340 days (11 months), with substantial variation (320-365 days)."),

        # 61-90: Breeds of Livestock (Cattle, Buffalo, Sheep, Goat)
        ("Which indigenous zebu cattle breed is renowned as the highest milk producer among Indian dairy breeds?",
         ["Sahiwal", "Amritmahal", "Hallikar", "Kangayam"],
         0, "Sahiwal (originating from Montgomery district) is the premier indigenous dairy cattle breed of India, yielding 2500-3000 kg milk per lactation."),
        ("The 'Gir' cattle breed of Gujarat is visually characterized by which iconic conformation?",
         ["Convex bulging forehead and long, pendulous curled ears resembling folded leaves", "Short pricked ears", "Complete absence of horns", "Straight flat forehead"],
         0, "Gir cattle possess an ultra-convex forehead (bony dome protecting the brain) and pendulous, leaf-like folded ears notched at the tip."),
        ("Which cattle breed is famous for its majestic high-stepping gait known as 'Sawai Chal'?",
         ["Kankrej", "Sahiwal", "Gir", "Deoni"],
         0, "Kankrej cattle of the Rann of Kutch possess massive lyre-shaped horns and an energetic, smooth trotting gait termed Sawai Chal (1.25 pace)."),
        ("The world-famous 'Murrah' buffalo breed originated from:",
         ["Haryana and Punjab (Rohtak, Jind, Hisar districts)", "Gujarat", "Tamil Nadu", "Maharashtra"],
         0, "Murrah is the premier dairy buffalo breed globally, characterized by jet black color and tightly coiled spiral horns ('curly horns')."),
        ("Which buffalo breed produces milk with the highest average milk fat percentage (up to 12-14%)?",
         ["Bhadawari", "Murrah", "Nili-Ravi", "Jaffarabadi"],
         0, "Bhadawari buffaloes (from the ravine tract of Yamuna/Chambal, UP/MP) are copper-colored and famous for rich milk fat reaching 12-14%."),
        ("The 'Nili-Ravi' buffalo breed is distinguished by white markings on the forehead, face, muzzle, legs, and tail switch, termed:",
         ["Panchkalyan (five auspicious white points)", "Kalyani", "Chouhan", "Shankar"],
         0, "Nili-Ravi buffaloes are characterized by white wall eyes and white patches on five points (forehead, face, legs, tail switch), called Panchkalyan."),
        ("The heaviest and largest Indian buffalo breed with massive drooping horns and a prominent forehead is the:",
         ["Jaffarabadi", "Surti", "Mehsana", "Pandharpuri"],
         0, "Jaffarabadi buffaloes (Gir forest, Gujarat) are the heaviest breed, with broad flat horns drooping down the side of the neck."),
        ("The 'Mehsana' buffalo breed was developed by crossing which two parent breeds?",
         ["Murrah and Surti", "Jaffarabadi and Murrah", "Nili-Ravi and Bhadawari", "Nagpuri and Pandharpuri"],
         0, "Mehsana was synthesized in Gujarat by crossing Murrah (for milk yield) with Surti (for persistent lactation)."),
        ("Which indigenous goat breed is renowned as the tallest and largest dairy breed, possessing a Roman nose and parrot-mouth conformation?",
         ["Jamunapari", "Barbari", "Black Bengal", "Marwari"],
         0, "Jamunapari (Chambal ravines, UP) is the largest Indian goat breed, with long pendulous ears and a pronounced convex Roman nose."),
        ("Which Indian goat breed is famous for high prolificacy (frequent twin and triplet kiddings) and supreme meat (chevon) quality?",
         ["Black Bengal", "Jamunapari", "Beetal", "Sirohi"],
         0, "Black Bengal goats possess exceptional fecundity, often kidding twice a year with twins/triplets, and yield fine-grained, flavorful chevon."),
        ("The luxurious, ultra-fine undercoat fiber known as 'Pashmina' (Cashmere) is harvested from which Indian goat breed?",
         ["Changthangi (and Chegu) goats of Ladakh/Himalayas", "Jamunapari", "Barbari", "Osmanabadi"],
         0, "Changthangi and Chegu goats grazing in high-altitude freezing Himalayan pastures produce the world-renowned soft undercoat down called Pashmina."),
        ("The fine-wool sheep breed that produces the finest fleece globally (18-22 microns) is the:",
         ["Merino", "Suffolk", "Dorset", "Lincoln"],
         0, "The Australian Merino is the premier fine-wool sheep breed, producing dense, highly crimped, fine fleece."),
        ("The premier Indian mutton sheep breed with long drooping ears and Roman nose, raised in Andhra Pradesh, is the:",
         ["Nellore", "Marwari", "Chokla", "Gaddi"],
         0, "Nellore is the tallest Indian sheep breed, having a coat of short hair rather than wool, exclusively raised for mutton."),
        ("Which Indian sheep breed of Rajasthan is celebrated as the 'Indian Merino' for producing fine apparel-grade wool?",
         ["Chokla", "Magra", "Malpura", "Nali"],
         0, "Chokla sheep produce the finest carpet/apparel wool among native Indian breeds and are colloquially called the Indian Merino."),
        ("The practice of offering supplementary high-energy grain to breeding ewes 2 to 3 weeks prior to mating is called:",
         ["Flushing", "Steaming up", "Creep feeding", "Challenger feeding"],
         0, "Flushing elevates the ovulation rate and increases the incidence of twin conceptions by stimulating positive nutritional ovarian feedback."),
        ("The nutritional practice of feeding extra concentrate to pregnant cows/ewes 3 to 4 weeks before parturition is called:",
         ["Steaming up", "Flushing", "Creep feeding", "Phase feeding"],
         0, "Steaming up builds up body condition reserves and readies ruminal papillae for high concentrate intake immediately post-calving."),
        ("Creep feeding refers to providing specialized nutrient-dense feed exclusively to:",
         ["Young suckling calves/piglets/lambs in an enclosure inaccessible to adult dams", "Dry cows", "Breeding bulls", "Sick animals"],
         0, "A creep gate allows small young animals to enter a private feeding pen to consume starter ration without interference from larger adults."),

        # 91-120: Poultry Production & Hatchery Management
        ("The incubation period for the domestic chicken (Gallus domesticus) egg is:",
         ["21 days", "28 days", "17 days", "35 days"],
         0, "Chicken eggs require exactly 21 days (504 hours) of incubation under optimal temperature and humidity."),
        ("The incubation period for domestic duck and turkey eggs is:",
         ["28 days", "21 days", "17 days", "35 days"],
         0, "Duck and turkey eggs require 28 days of incubation (Muscovy ducks require 35 days)."),
        ("The optimum setter temperature in a modern forced-draft incubator for chicken eggs is:",
         ["99.5 to 100.0 degrees Fahrenheit (37.5 to 37.8 degrees C)", "105.0 degrees F", "95.0 degrees F", "102.5 degrees F"],
         0, "Forced-draft incubators maintain a steady 99.5-100.0 F (37.5-37.7 C) during the first 18 days of setter incubation."),
        ("During incubation, chicken eggs should be turned regularly until which day, when they are transferred to the hatcher?",
         ["18th day", "14th day", "10th day", "20th day"],
         0, "Eggs are turned hourly until day 18 to prevent the embryo from sticking to the inner shell membrane, then moved to hatcher baskets without turning."),
        ("Relative humidity inside the hatcher during the final 3 days (days 19 to 21) of chicken egg incubation should be increased to:",
         ["70% to 75% (wet-bulb ~90 F)", "40%", "50%", "95%"],
         0, "Elevated humidity (70-75%) in the hatcher softens the shell membrane, preventing pipping chicks from drying out and sticking to the shell."),
        ("Egg candling is conventionally carried out on which incubation days to eliminate infertile eggs and dead embryos?",
         ["7th day and 14th day", "1st day and 21st day", "18th day only", "10th day only"],
         0, "Candling on day 7 identifies infertile 'clears' and early dead germs; day 14 candling detects mid-incubation dead embryos."),
        ("In poultry brooding management, the brooding temperature under the hover during the 1st week of life should be:",
         ["95 degrees Fahrenheit (35 degrees C)", "80 degrees F", "105 degrees F", "70 degrees F"],
         0, "Chicks cannot thermoregulate during their first week and require 95 F (35 C), reduced by 5 F each subsequent week until ambient room temp is reached."),
        ("Beak trimming (debeaking) in commercial egg-type pullets is performed at 7 to 10 days of age primarily to prevent:",
         ["Cannibalism, feather pecking, and feed wastage", "Broodiness", "Egg eating", "Coccidiosis"],
         0, "Debeaking removes the sharp tip of the upper and lower beak to eliminate feather pecking, vent cannibalism, and feed tossing."),
        ("The 'all-in, all-out' system in poultry and swine farming is a biosecurity strategy where:",
         ["All animals in a shed are introduced and depopulated together, allowing complete disinfection between batches", "Animals are kept indefinitely", "New animals enter daily", "Breeding occurs continuously"],
         0, "Depopulating an entire house simultaneously breaks pathogen cycles, allowing thorough cleaning, disinfection, and downtime."),
        ("The 'dubbing' procedure in day-old chicks refers to the surgical removal of the:",
         ["Comb", "Wattles", "Spurs", "Beak tip"],
         0, "Dubbing is the trimming of the comb at day-old to prevent comb injuries, frostbite, and head injuries in caged birds."),
        ("The 'dewattling' procedure in cockerels refers to the surgical excision of the:",
         ["Wattles", "Comb", "Preen gland", "Claws"],
         0, "Dewattling removes the wattles to prevent hematomas and traumatic tears during fighting in breeding flocks.")
    ]

    for idx, item in enumerate(raw_lpm[:120]):
        questions.append({
            "id": f"lpm_q_{idx+1:03d}",
            "domain": "animal_science",
            "year": "1st_year",
            "subjectId": "lpm",
            "topic": "Livestock Production Management",
            "questionText": item[0],
            "options": item[1],
            "correctOptionIndex": item[2],
            "explanation": item[3],
            "difficulty": "Medium",
            "tags": ["LPM", "Animal Science"],
            "createdAt": 1773000000000 + idx
        })
    return questions

if __name__ == "__main__":
    qs = get_lpm_questions()
    print(f"Loaded {len(qs)} Livestock Production Management questions.")
