# scripts/data_ann.py
# 120 High-Yield Questions for Animal Nutrition (ANN)

def get_ann_questions():
    questions = []

    raw_ann = [
        # 1-30: Feed Analysis & Detergent Fiber Systems
        ("In the Weende proximate analysis of feedstuffs, Crude Protein (CP) is calculated by multiplying total Kjeldahl nitrogen by which conversion factor?",
         ["6.25 (assuming average protein contains 16% nitrogen)", "5.70", "4.50", "8.00"],
         0, "Because typical feed proteins contain approximately 16% nitrogen (100 / 16 = 6.25), crude protein percentage is mathematically calculated as: CP% = Nitrogen% * 6.25."),
        ("In proximate analysis, Nitrogen-Free Extract (NFE) representing soluble carbohydrates (starch, sugars) is determined by:",
         ["Mathematical difference: 100 - (% Moisture + % CP + % EE + % CF + % Total Ash)", "Direct chemical precipitation", "Bomb calorimetry", "Kjeldahl digestion"],
         0, "NFE is the only proximate fraction not measured by direct chemical analysis; it is calculated by subtracting moisture, crude protein, ether extract, crude fiber, and ash from 100."),
        ("In the Van Soest detergent system of feed evaluation, Neutral Detergent Fiber (NDF) represents which cell wall fractions?",
         ["Hemicellulose, Cellulose, and Lignin (Total plant cell wall)", "Cellulose and Lignin only", "Hemicellulose and Pectin", "Starch and Sugars"],
         0, "NDF is the insoluble residue after boiling in neutral detergent solution, consisting of hemicellulose, cellulose, and lignin; it is the best predictor of voluntary dry matter intake (gut fill)."),
        ("In the Van Soest system, Acid Detergent Fiber (ADF) consists of:",
         ["Cellulose and Lignin (including silica)", "Hemicellulose and Cellulose", "Lignin only", "Pectin and Hemicellulose"],
         0, "Boiling in acid detergent solution dissolves hemicellulose, leaving behind Acid Detergent Fiber (ADF = cellulose + lignin); ADF is inversely correlated with forage digestibility."),
        ("How is the 'Hemicellulose' percentage calculated from Van Soest fiber fractions?",
         ["Hemicellulose = NDF - ADF", "Hemicellulose = ADF - ADL", "Hemicellulose = NDF - ADL", "Hemicellulose = Total Ash - ADF"],
         0, "Since NDF = Hemicellulose + Cellulose + Lignin and ADF = Cellulose + Lignin, Hemicellulose is mathematically obtained by subtracting ADF from NDF."),
        ("How is the 'Cellulose' percentage determined from Van Soest fiber fractions?",
         ["Cellulose = ADF - ADL (Acid Detergent Lignin)", "Cellulose = NDF - ADF", "Cellulose = NDF - ADL", "Cellulose = Total Ash - NDF"],
         0, "ADF contains cellulose and lignin; treating the ADF residue with 72% sulfuric acid dissolves cellulose, leaving acid detergent lignin (ADL); therefore Cellulose = ADF - ADL."),
        ("The total gross energy (GE) of one gram of pure ether extract (fat) when burned in a bomb calorimeter is approximately:",
         ["9.45 kcal / gram (39.5 kJ/g)", "4.15 kcal / gram", "5.65 kcal / gram", "2.25 kcal / gram"],
         0, "Fats contain far fewer oxygen atoms and are more reduced than carbohydrates, yielding approximately 2.25 times more gross energy (9.45 kcal/g vs 4.15 kcal/g for carbohydrates)."),
        ("In the Total Digestible Nutrients (TDN) formula, why is Digestible Ether Extract (DEE) multiplied by 2.25?",
         ["Because fat yields 2.25 times more energy per gram than carbohydrates or protein (9.45 / 4.15 = 2.25)", "To convert fat into protein", "To correct for fecal losses", "Because fat is 2.25 times denser"],
         0, "TDN = % DCP + % DCF + % DNFE + (% DEE * 2.25). Fat is multiplied by 2.25 to express its energy value on a carbohydrate-equivalent basis."),

        # 31-60: Energy Partitioning & Protein Nutrition
        ("Metabolizable Energy (ME) in ruminant nutrition is defined as Digestible Energy (DE) minus energy lost in:",
         ["Urine and gaseous products of fermentation (principally methane)", "Feces only", "Heat increment", "Sweat"],
         0, "Gross Energy minus Fecal Energy = DE. Digestible Energy minus (Urinary Energy + Methane Energy) = Metabolizable Energy (ME)."),
        ("Net Energy (NE) represents the portion of feed energy available for maintenance and production, calculated as:",
         ["Metabolizable Energy (ME) minus Heat Increment (HI)", "Digestible Energy minus Feces", "Gross Energy minus Urine", "TDN * 4.4"],
         0, "Heat increment (HI) is the heat produced during nutrient digestion, fermentation, and metabolism; Net Energy = ME - HI, which is partitioned into NEm (maintenance) and NEp (production)."),
        ("The primary factor responsible for the high heat increment (HI) in ruminants compared to monogastrics is:",
         ["Heat of microbial fermentation in the rumen and metabolic cost of acetate utilization", "Higher body temperature", "Longer digestive tract", "Salivary secretion"],
         0, "Exothermic anaerobic microbial fermentation in the rumen and the lower biochemical efficiency of acetate for lipogenesis generate substantial metabolic heat in ruminants."),
        ("Pure feed-grade Urea (fertilizer grade) contains 46% Nitrogen. What is its Crude Protein (CP) equivalent for ruminants?",
         ["287.5% (46 x 6.25 = 287.5%)", "100%", "46%", "16%"],
         0, "Urea contains 46% nitrogen. Applying the standard nitrogen-to-protein conversion factor of 6.25: CP equivalent = 46 * 6.25 = 287.5% CP."),
        ("What is the safe upper limit for feeding urea to ruminants to prevent fatal ammonia toxicity?",
         ["Not more than 1% of total diet dry matter OR 3% of the concentrate mixture", "10% of the total diet", "5% of body weight", "15% of concentrate"],
         0, "Safe feeding guidelines dictate that urea must not exceed 1% of total ration DM or 2.8-3% of concentrate, and should not supply more than one-third of total dietary nitrogen."),
        ("To ensure efficient utilization of urea nitrogen by ruminal microbes and prevent toxicity, the diet must provide an abundant source of:",
         ["Readily fermentable, rapidly available soluble carbohydrates (e.g. Molasses or crushed grains)", "Coarse cereal straw", "Bypass protein", "Excess dietary fat"],
         0, "Microbes require synchrony of ammonia release with carbon keto-acid skeletons derived from rapid starch/sugar fermentation to synthesize amino acids."),
        ("The clinical signs of acute urea (ammonia) toxicity in cattle (salivation, muscle tremors, incoordination, bloat, convulsions) appear when rumen pH rises above:",
         ["8.0 (free non-ionized NH3 rapidly diffuses across the rumen wall into blood)", "6.5", "5.0", "7.0"],
         0, "Rapid urea hydrolysis by bacterial urease outpaces ammonia assimilation, pushing rumen pH > 8.0 where ammonia shifts to lipid-soluble NH3 and crosses into systemic blood, causing hyperammonemic encephalopathy."),
        ("The immediate emergency field treatment (antidote) for acute urea poisoning in cattle is:",
         ["Oral drenching with 2 to 4 liters of vinegar (5% acetic acid) mixed with cold water", "Sodium bicarbonate drench", "Intramuscular atropine", "Calcium gluconate IV"],
         0, "Vinegar acidifies the rumen contents (lowering pH below 7.0), converting toxic diffusible NH3 into non-diffusible ammonium ions (NH4+) while cold water slows bacterial urease."),
        ("The term 'Rumen Undegradable Protein' (RUP / Bypass Protein) refers to dietary protein that:",
         ["Escapes microbial degradation in the rumen and passes intact into the abomasum for enzymatic digestion", "Is completely indigestible and excreted in feces", "Is synthesized by protozoa", "Is converted to urea"],
         0, "RUP escapes ruminal proteolysis and arrives in the abomasum and small intestine, providing high-quality amino acids directly to the host animal for milk synthesis and growth."),

        # 61-90: Feedstuffs, Silage, Hay & Anti-Nutritional Factors
        ("In silage making (ensiling), the optimum moisture content of the green chopped fodder at the time of ensiling should be:",
         ["65% to 70% (30-35% dry matter)", "85% to 90%", "40% to 45%", "15% to 20%"],
         0, "Forages ensiled with 65-70% moisture compact tightly to exclude air; higher moisture causes seepage and clostridial fermentation, while lower moisture prevents adequate compaction."),
        ("Good quality silage is characterized by which organic acid and pH range?",
         ["Predominantly Lactic Acid (3-8% DM) and a pH of 3.8 to 4.2", "Butyric acid and pH 6.0", "Acetic acid and pH 5.5", "Propionic acid and pH 7.0"],
         0, "Lactic acid bacteria (Lactobacillus plantarum) ferment soluble sugars anaerobically, rapidly driving the pH down to 3.8-4.2, which pickles and preserves the forage indefinitely."),
        ("The presence of high concentrations of 'Butyric acid' and a pH above 5.0 in silage indicates:",
         ["Spoilage by Clostridial fermentation due to excess moisture or poor compaction", "Excellent preservation", "High sugar content", "Optimal lactic fermentation"],
         0, "Clostridium butyricum and C. tyrobutyricum proliferate in poorly compacted, wet silage, breaking down proteins into foul amines and converting lactic acid into butyric acid."),
        ("In hay making, the green forage must be dried down to what moisture level to prevent fungal molding and spontaneous combustion in the stack?",
         ["Below 15% (85% dry matter or more)", "30%", "25%", "40%"],
         0, "Moisture levels above 15-18% in baled or stacked hay allow thermophilic molds (Aspergillus, Micropolyspora) to multiply, producing heat that can ignite spontaneous fires."),
        ("In the 'urea-ammoniation' of cereal straws (paddy or wheat straw) to improve nutritive value, the standard recommended formulation is:",
         ["4 kg Urea dissolved in 40 to 50 Liters of water sprayed on 100 kg straw, sealed airtight for 21 to 28 days", "10 kg Urea with 10 L water", "1 kg Urea with 100 L water", "50 kg Urea per 100 kg straw"],
         0, "4% urea treatment with 40-50% moisture breaks ligno-cellulosic bonds and doubles straw crude protein from 3.5% to 7.5-8.0%, while boosting voluntary intake by 15-20%."),
        ("The anti-nutritional toxic amino acid present in the forage tree Leucaena leucocephala (Subabul) is:",
         ["Mimosine", "Gossypol", "Tannin", "Cyanogen"],
         0, "Mimosine is hydrolyzed in the rumen to 3,4-DHP (dihydroxypyridine), a potent goitrogen causing alopecia, thyroid enlargement, and weight loss in unadapted cattle."),
        ("The anaerobic ruminal bacterium capable of completely detoxifying mimosine and DHP in Leucaena is:",
         ["Synergistes jonesii", "Fibrobacter succinogenes", "Ruminococcus albus", "Streptococcus bovis"],
         0, "Dr. Raymond Jones discovered Synergistes jonesii, a ruminal bacterium that degrades 3,4-DHP into non-toxic compounds, successfully transferred to ruminants in Australia and Asia."),
        ("The polyphenolic yellow toxic pigment present in cottonseed and raw cottonseed cake that causes cardiac necrosis and male infertility is:",
         ["Gossypol", "Aflatoxin", "Ricin", "Oxalate"],
         0, "Free gossypol binds iron and inhibits enzymes; in monogastrics and young ruminants, it causes myocardial degeneration, pulmonary edema, and testicular germ cell destruction."),
        ("Cyanogenic glycosides (such as Dhurrin) present in young, drought-stressed, immature sorghum (Jowar) plants release lethal amounts of:",
         ["Hydrocyanic acid (HCN / Prussic acid)", "Oxalic acid", "Nitrate", "Tannic acid"],
         0, "Mastication of young sorghum (<50 cm tall or drought-stunted) releases beta-glucosidases that hydrolyze dhurrin into toxic HCN, which inhibits cytochrome oxidase, causing cellular anoxia."),
        ("The pathognomonic necropsy finding in animals dying of acute Cyanide (HCN / Prussic acid) poisoning is:",
         ["Bright, cherry-red colored blood due to inability of tissues to utilize oxygen (oxyhemoglobin persistence)", "Chocolate-brown colored blood", "Tarry black unclotted blood", "Watery pale blood"],
         0, "Cyanide inhibits mitochondrial cytochrome c oxidase (Complex IV); oxygen cannot be unloaded in tissues, so both venous and arterial blood remain saturated with oxygen (bright cherry-red)."),
        ("The specific antidote protocol for acute Cyanide (Prussic acid) poisoning in livestock is:",
         ["Sodium nitrite followed by Sodium thiosulfate IV", "Methylene blue IV", "Atropine sulfate", "Diminazene aceturate"],
         0, "Sodium nitrite converts hemoglobin to methemoglobin (which binds CN with high affinity to form cyanmethemoglobin); Sodium thiosulfate then provides sulfur for rhodanese to convert CN to harmless thiocyanate."),
        ("In contrast, acute 'Nitrate / Nitrite poisoning' (e.g. from grazing fertilized oats or pigweed) turns blood:",
         ["Chocolate-brown in color due to Methemoglobin formation", "Bright cherry-red", "Clear and colorless", "Milky white"],
         0, "Nitrite (NO2-) oxidizes ferrous iron (Fe2+) of hemoglobin into ferric iron (Fe3+), forming methemoglobin which cannot transport oxygen, giving blood a dark chocolate-brown color."),
        ("The specific antidote for acute Nitrate/Nitrite poisoning in cattle and sheep is:",
         ["Methylene blue (1 to 2% solution IV at 4 to 8 mg/kg)", "Sodium nitrite", "Vinegar", "BAL (Dimercaprol)"],
         0, "Methylene blue acts as an electron donor, accelerating the enzymatic reduction of methemoglobin back to functional hemoglobin via methemoglobin reductase."),
        ("Aflatoxins (predominantly Aflatoxin B1) are potent hepatotoxic and carcinogenic mycotoxins produced by which mold in stored groundnut cake and grains?",
         ["Aspergillus flavus and Aspergillus parasiticus", "Fusarium moniliforme", "Penicillium roqueforti", "Claviceps purpurea"],
         0, "A. flavus produces aflatoxin B1 in warm, humid storage (>14% moisture); in lactating cows, aflatoxin B1 is hydroxylated in the liver and excreted in milk as carcinogenic Aflatoxin M1."),
        ("The regulatory maximum permissible limit of Aflatoxin B1 in commercial cattle feed ingredients in India (BIS standards) is:",
         ["20 to 50 ppb (parts per billion / micrograms per kg)", "50 ppm (parts per million)", "500 ppb", "Zero tolerance (0 ppb)"],
         0, "BIS standards stipulate that aflatoxin B1 in compounded cattle feeds should not exceed 20 to 50 ppb (ug/kg) to safeguard animal health and prevent milk residue contamination."),
        ("Paddy straw (rice straw) contains high levels of soluble and insoluble which anti-nutritional compound that binds dietary calcium and causes hypocalcemia?",
         ["Oxalates (oxalic acid)", "Tannins", "Phytates", "Cyanogens"],
         0, "Paddy straw contains 1-2% oxalates, which form insoluble calcium oxalate in the rumen and intestine, stripping calcium and predisposing cattle to negative calcium balance and urolithiasis."),

        # 91-120: Minerals, Vitamins & Metabolic Deficiencies
        ("The ideal calcium to phosphorus (Ca : P) ratio in the total ration of adult ruminants is approximately:",
         ["2 : 1 (range 1.5:1 to 2:1)", "1 : 5", "5 : 1", "1 : 1 always"],
         0, "A Ca:P ratio of 1.5:1 to 2:1 ensures optimal intestinal absorption and parathyroid balance; inverted Ca:P ratios (excess P from grains) precipitate urinary calculi in feedlot steers/wethers."),
        ("Grass tetany (hypomagnesemic tetany / grass staggers) in lactating cows grazing lush spring pastures is triggered by:",
         ["Low plasma magnesium (<1.2 mg/dL) exacerbated by high potassium (K) interfering with ruminal Mg absorption", "High calcium diets", "Vitamin D deficiency", "Urea toxicity"],
         0, "Lush spring grass is high in potassium and nitrogen, which impairs active magnesium transport across the ruminal epithelium, causing acute hypomagnesemia, muscle tremors, and tetanic convulsions."),
        ("Parturient paresis (Milk Fever) in transition dairy cows is characterized clinically by flaccid recumbency and is biochemically caused by:",
         ["Acute Hypocalcemia (serum Ca falling below 5.5 mg/dL)", "Hypercalcemia", "Hypomagnesemia", "Hyperglycemia"],
         0, "The sudden colostral drain of calcium at calving drops serum ionized calcium, preventing acetylcholine release at neuromuscular junctions and producing generalized flaccid paralysis."),
        ("To prevent Milk Fever in transition cows, pre-partum diets during the close-up dry period (last 3 weeks) are often formulated to have a:",
         ["Negative Dietary Cation-Anion Difference (DCAD) using anionic salts (sulfates, chlorides)", "High positive DCAD", "High calcium and alfalfa hay", "Zero protein"],
         0, "A negative DCAD (-50 to -100 mEq/kg) induces mild systemic metabolic acidosis, which dramatically enhances tissue sensitivity to PTH and upregulates bone calcium mobilization before calving."),
        ("'Pica' (depraved appetite characterized by animals licking soil, chewing rocks, eating wood and bones) is a classical sign of chronic:",
         ["Phosphorus deficiency", "Iron deficiency", "Vitamin A deficiency", "Sodium toxicity"],
         0, "Phosphorus-deficient soils produce forages low in phosphorus; chronic hypophosphatemia induces osteophagia (bone chewing) which frequently predisposes cattle to ingest Clostridium botulinum toxin from carcasses."),
        ("Vitamin E acts synergistically with which trace element to protect cell membranes against lipid peroxidation?",
         ["Selenium (as a component of cytosolic Glutathione Peroxidase)", "Iron", "Zinc", "Cobalt"],
         0, "Selenium is an integral catalytic component of glutathione peroxidase (GSH-Px), which converts toxic hydrogen peroxide and lipid hydroperoxides into harmless water, working in tandem with membrane-bound Vitamin E."),
        ("Cobalt deficiency in ruminants is clinically indistinguishable from which vitamin deficiency?",
         ["Vitamin B12 (Cyanocobalamin) deficiency", "Vitamin B1 (Thiamine)", "Vitamin A", "Vitamin C"],
         0, "Ruminal microbes require cobalt to synthesize Vitamin B12; on cobalt-deficient pastures, B12 synthesis ceases, crippling methylmalonyl-CoA mutase and causing severe wasting, emaciation, and anemia ('coast disease').")
    ]

    for idx, item in enumerate(raw_ann[:120]):
        questions.append({
            "id": f"ann_q_{idx+1:03d}",
            "domain": "animal_science",
            "year": "2nd_year",
            "subjectId": "ann",
            "topic": "Animal Nutrition",
            "questionText": item[0],
            "options": item[1],
            "correctOptionIndex": item[2],
            "explanation": item[3],
            "difficulty": "Medium",
            "tags": ["Nutrition", "ANN"],
            "createdAt": 1773000000000 + idx
        })
    return questions

if __name__ == "__main__":
    qs = get_ann_questions()
    print(f"Loaded {len(qs)} Animal Nutrition questions.")
