# scripts/data_vpp.py
# 120 High-Yield Questions for Veterinary Pathology (VPP)

def get_vpp_questions():
    questions = []

    raw_vpp = [
        # 1-30: General Pathology (Cell Injury, Degenerations, Necrosis)
        ("Zenker’s degeneration (hyaline degeneration) is classically and characteristically observed in which tissue?",
         ["Striated (skeletal) muscle", "Hepatic cords", "Renal tubular epithelium", "Cardiac Purkinje fibers"],
         0, "Zenker's degeneration is a waxy, hyaline degeneration of skeletal muscle fibers classically seen in White Muscle Disease (Selenium/Vit E deficiency) and toxemias."),
        ("Amyloid deposits in tissue sections stain salmon-pink with Congo Red and exhibit which diagnostic optical property under polarized light?",
         ["Apple-green birefringence", "Yellow fluorescence", "Blue-black metachromasia", "Dark brown opacity"],
         0, "Under polarizing microscopy, Congo red-stained amyloid fibrils exhibit characteristic pathognomonic apple-green birefringence due to their beta-pleated sheet conformation."),
        ("Coagulative necrosis is the characteristic pattern of cell death seen in ischemic infarction in all solid organs EXCEPT the:",
         ["Brain and spinal cord (Central Nervous System)", "Kidney", "Myocardium", "Spleen"],
         0, "Ischemic injury to the brain and spinal cord uniquely produces liquefactive (malacic) necrosis due to high lipid and hydrolytic enzyme content."),
        ("Caseous necrosis with a cheesy, friable, amorphous debris appearance is the classic hallmark lesion of:",
         ["Tuberculosis (Mycobacterium bovis)", "Acute pancreatitis", "Coronary thrombosis", "Rabies"],
         0, "Tuberculosis creates central caseous necrosis surrounded by epithelioid macrophages, Langhans multinucleated giant cells, and a peripheral lymphocytic rim (tubercle)."),
        ("Enzymatic fat necrosis with chalky white calcium deposits (saponification) is classically seen in:",
         ["Acute necrotizing pancreatitis", "Hepatic lipidosis", "Renal amyloidosis", "Pulmonary tuberculosis"],
         0, "Release of activated pancreatic lipases into peripancreatic mesenteric fat hydrolyzes triglycerides into free fatty acids, which complex with calcium to form chalky soaps."),
        ("The 'nutmeg liver' appearance on gross necropsy is characteristic of:",
         ["Chronic passive venous congestion (Right-sided heart failure)", "Acute viral hepatitis", "Hepatic lipidosis", "Biliary cirrhosis"],
         0, "Centrilobular passive congestion and necrosis (dark red) contrasted with periportal fatty change (pale yellow) produces the mottled 'nutmeg' pattern."),
        ("The 'Virchow’s triad' outlines the three primary predisposing factors for intravascular thrombosis, which are:",
         ["Endothelial injury, Stasis / abnormal blood flow, and Hypercoagulability", "Hypotension, Anemia, and Hypocalcemia", "Fever, Leukopenia, and Thrombocytopenia", "Hyperglycemia, Hypokalemia, and Edema"],
         0, "Virchow's triad comprises: 1. Endothelial damage, 2. Alterations in normal laminar blood flow (stasis/turbulence), and 3. Hypercoagulability of blood."),
        ("Post-mortem blood clots can be distinguished grossly from ante-mortem thrombi because post-mortem clots are:",
         ["Moist, gelatinous, unattached to vessel walls, and easily removable ('currant jelly' or 'chicken fat')", "Dry, friable, laminated with lines of Zahn, and adherent to the wall", "Always calcified", "Containing abundant bacteria"],
         0, "Post-mortem clots are smooth, shiny, non-adherent, taking the shape of the lumen ('currant jelly' with red cells settled or 'chicken fat' with plasma separated)."),
        ("The 'wear and tear' insoluble brown-yellow intracellular pigment composed of oxidized lipid polymers that accumulates with aging is:",
         ["Lipofuscin (ceroid)", "Hemosiderin", "Melanin", "Bilirubin"],
         0, "Lipofuscin is an endogenous aging pigment resulting from free radical peroxidation of polyunsaturated lipids in lysosomes of non-dividing cells (neurons, cardiomyocytes)."),
        ("Hemosiderin, the iron-storage pigment formed from hemoglobin degradation in macrophages, stains brilliant blue with:",
         ["Prussian Blue (Perls' reaction)", "Congo Red", "Oil Red O", "Periodic Acid-Schiff (PAS)"],
         0, "Perls' Prussian blue reaction utilizes potassium ferrocyanide in dilute hydrochloric acid to stain ferric iron (Fe3+) in hemosiderin a vivid blue."),
        ("Fatty degeneration (steatosis) of the liver can be histochemically confirmed in frozen sections using which stain?",
         ["Oil Red O or Sudan Black B", "Hematoxylin and Eosin", "Masson's Trichrome", "Von Kossa stain"],
         0, "Standard paraffin embedding leaches out neutral lipids with xylene; frozen cryosections stained with Oil Red O preserve intracellular lipid droplets as bright red."),
        ("The cardinal signs of acute inflammation include Rubor (redness), Calor (heat), Tumor (swelling), Dolor (pain), and:",
         ["Functio laesa (loss of function)", "Necrosis", "Hyperemia", "Fibrosis"],
         0, "Celsus described the four signs, and Rudolf Virchow added the fifth: Functio laesa (loss of function of the inflamed tissue)."),
        ("Langhans multinucleated giant cells with peripheral horseshoe-shaped nuclei are classically found in:",
         ["Granulomatous inflammation (Tuberculosis)", "Acute suppurative abscess", "Fibrinous pericarditis", "Allergic dermatitis"],
         0, "Langhans giant cells are fused epithelioid macrophages characterized by nuclei arranged in an arc or horseshoe pattern around the cell periphery in tuberculosis."),
        ("The predominant inflammatory leukocyte recruited in the first 6 to 24 hours of acute bacterial inflammation is the:",
         ["Neutrophil (heterophil in birds)", "Macrophage", "Eosinophil", "Plasma cell"],
         0, "Neutrophils respond first to chemotactic signals (C5a, LTB4, IL-8), performing phagocytosis and releasing reactive oxygen species."),
        ("Eosinophilic inflammatory infiltrates are classically associated with:",
         ["Parasitic (helminth) infections and Type I IgE-mediated allergic reactions", "Acute viral infections", "Bacterial septicemia", "Infarction"],
         0, "Eosinophils are specifically recruited by eotaxin and IL-5, containing major basic protein and eosinophil cationic protein to destroy migrating helminths."),
        ("The 'bread and butter' appearance of the heart is gross pathology characteristic of:",
         ["Fibrinous pericarditis (e.g. Traumatic Reticulopericarditis in cattle)", "Fatty degeneration", "Myocardial infarction", "Hydropericardium"],
         0, "Fibrin strands depositing across the visceral and parietal pericardium pull apart with heart movement, resembling two slices of buttered bread pulled apart."),
        ("Apoptosis is differentiated morphologically from necrosis because apoptosis features:",
         ["Cell shrinkage, intact cell membrane, chromatin condensation, apoptotic bodies, and NO inflammation", "Cellular swelling, membrane rupture, and intense neutrophil influx", "Formation of large scars", "Calcification"],
         0, "Apoptosis is programmed, energy-dependent cell suicide without plasma membrane lysis or recruitment of inflammatory cells."),

        # 31-60: Neoplasia & Oncology
        ("The universal hallmark diagnostic feature distinguishing malignant tumors from benign tumors is:",
         ["Invasion into surrounding tissues and capability of metastasis", "Rapid growth alone", "Presence of fibrous capsule", "Mitotic figures"],
         0, "While cellular atypia and rapid growth suggest malignancy, local tissue invasion and distant metastasis are the unequivocal criteria of malignancy."),
        ("A malignant neoplasm derived from epithelial tissue is classified as a:",
         ["Carcinoma", "Sarcoma", "Adenoma", "Fibroma"],
         0, "Malignant tumors of epithelial origin are carcinomas (e.g. Squamous Cell Carcinoma, Adenocarcinoma), while those of mesenchymal origin are sarcomas."),
        ("A malignant neoplasm derived from mesenchymal connective tissue (bone, cartilage, fibrous tissue) is termed a:",
         ["Sarcoma", "Carcinoma", "Teratoma", "Hamartoma"],
         0, "Sarcomas (e.g. Osteosarcoma, Fibrosarcoma, Hemangiosarcoma) arise from mesenchymal tissues and classically metastasize via hematogenous routes."),
        ("The 'p53' protein functions biologically as a:",
         ["Tumor suppressor protein ('Guardian of the Genome') regulating cell cycle arrest and apoptosis", "Oncogene stimulating mitosis", "Growth factor receptor", "DNA polymerase"],
         0, "p53 senses DNA damage and arrests the cell cycle at the G1/S checkpoint to allow DNA repair or triggers apoptosis if damage is irreparable."),
        ("Bovine Papillomavirus Type 4 (BPV-4) along with ingestion of bracken fern (Pteridium aquilinum) causes:",
         ["Squamous cell carcinoma of the upper digestive tract and urinary bladder (Enzootic Bovine Hematuria)", "Papillomatosis of skin exclusively", "Bovine leukosis", "Foot rot"],
         0, "Carcinogenic ptaquiloside in bracken fern acts synergistically with BPV-4 to transform papillomas into malignant squamous cell carcinomas and bladder hemangiosarcomas."),
        ("The 'Marek’s Disease' in domestic poultry is a lymphoproliferative neoplastic disease caused by:",
         ["Marek's Disease Virus (an Alphaherpesvirus)", "Retrovirus", "Birnavirus", "Coronavirus"],
         0, "Marek's Disease Virus (MDV, Gallid alphaherpesvirus 2) transforms T-lymphocytes, producing peripheral nerve enlargement (sciatic paralysis), skin leukosis, and visceral lymphomas."),
        ("Lymphoid leukosis in chickens is caused by an:",
         ["Avian Retrovirus (Avian Leukosis Virus - ALV)", "Herpesvirus", "Adenovirus", "Poxvirus"],
         0, "Avian Leukosis Virus is an oncogenic retrovirus that infects the bursa of Fabricius, transforming B-lymphocytes into clonal lymphomas in older birds."),
        ("Canine Transmissible Venereal Tumor (CTVT / Sticker's sarcoma) has a characteristic diploid chromosome count of:",
         ["59 chromosomes (compared to the normal canine 78)", "78 chromosomes", "38 chromosomes", "90 chromosomes"],
         0, "CTVT is a naturally occurring clonally transmissible allograft possessing a remarkably conserved altered karyotype of 57-59 chromosomes."),

        # 61-120: Specific Pathology of Major Animal Diseases
        ("At necropsy of a bovine carcass, you observe: failure of blood to clot (dark tarry blood discharging from all natural orifices), absence of rigor mortis, and tremendous splenomegaly ('blackberry jam' spleen). What is the diagnosis?",
         ["Anthrax (Bacillus anthracis)", "Blackleg", "Bovine Viral Diarrhea", "Hemorrhagic Septicemia"],
         0, "These are the pathognomonic necropsy findings of peracute Anthrax; opening the carcass is legally prohibited to prevent environmental spore contamination."),
        ("The pathognomonic gross lesion of 'Blackleg' (Clostridium chauvoei infection) in cattle is:",
         ["Dry, black, crepitant emphysematous muscle swellings with a sweet, rancid butter (butyric acid) odor", "Splenomegaly with unclotted blood", "Petechiae on kidney cortex", "Ulcers on tongue"],
         0, "C. chauvoei produces severe necrotizing emphysematous myositis, turning skeletal muscle dark red-black and dry with gas crepitation and a butyric odor."),
        ("The hallmark intestinal pathology of 'Johne’s Disease' (Paratuberculosis / Mycobacterium avium subsp. paratuberculosis) in cattle is:",
         ["Thickened, corrugation of the ileal and colonic mucosa resembling cerebral gyri that cannot be smoothed out", "Linear button ulcers", "Hemorrhagic pseudomembranes", "Fibrinous cast formation"],
         0, "Massive infiltration of the lamina propria and submucosa by epithelioid macrophages packed with acid-fast bacilli causes permanent transverse corrugation of the intestine."),
        ("Negri bodies are pathognomonic eosinophilic intracytoplasmic viral inclusion bodies found in neurons in:",
         ["Rabies", "Canine Distemper", "Infectious Canine Hepatitis", "Bovine Spongiform Encephalopathy"],
         0, "Negri bodies represent viral nucleocapsid aggregates, located primarily in pyramidal neurons of the hippocampus (carnivores) and Purkinje cells of the cerebellum (herbivores)."),
        ("Cowdry Type A intranuclear inclusion bodies are the classic histological hallmark of:",
         ["Herpesvirus infections and Infectious Canine Hepatitis (Adenovirus)", "Poxvirus", "Rabies", "Rotavirus"],
         0, "Infectious Canine Hepatitis (CAdV-1) produces large, basophilic to amphophilic intranuclear inclusion bodies inside hepatocytes and vascular endothelial cells."),
        ("Canine Distemper Virus (CDV / Morbillivirus) is pathologically unique because it produces:",
         ["Both intracytoplasmic AND intranuclear inclusion bodies in epithelial and glial cells", "Intranuclear inclusions only", "Intracytoplasmic inclusions only", "No inclusion bodies"],
         0, "Canine distemper virus produces characteristic eosinophilic inclusions in both the nucleus and the cytoplasm of respiratory, urinary, and glial cells."),
        ("'Hard pad disease' (hyperkeratosis of footpads and nose) in dogs is a classic manifestation of chronic:",
         ["Canine Distemper", "Canine Parvovirus", "Rabies", "Leptospirosis"],
         0, "Epitheliotropic proliferation by CDV causes severe secondary hyperkeratosis of the footpads and planum nasale, termed hard pad disease."),
        ("The 'button ulcers' in the cecum and colon mucosa are pathognomonic gross lesions of chronic:",
         ["Classical Swine Fever (Hog Cholera)", "African Swine Fever", "Swine Erysipelas", "Porcine Parvovirus"],
         0, "Concentric necrotic ulcerative lesions ('button ulcers') surrounding the ileocecal orifice are pathognomonic for chronic Classical Swine Fever."),
        ("The 'turkey egg kidney' (subcapsular petechial hemorrhages on the renal cortex) is classically observed in:",
         ["Classical Swine Fever (Hog Cholera)", "Foot and Mouth Disease", "Anthrax", "Glanders"],
         0, "Endothelial damage caused by Pestivirus (CSF) produces widespread cortical petechiae on the pale kidney, resembling a speckled turkey egg."),
        ("'Diamond skin disease' (rhomboid, red-purple raised cutaneous plaques) in pigs is pathognomonic for:",
         ["Erysipelothrix rhusiopathiae (Swine Erysipelas)", "Actinobacillus pleuropneumoniae", "Streptococcus suis", "Classical Swine Fever"],
         0, "Bacterial microvascular thrombosis and vasculitis induced by E. rhusiopathiae produces discrete rhomboidal erythematous skin infarcts."),
        ("In Foot and Mouth Disease (FMD), the characteristic lesion in young nursing calves without oral blisters is acute myocardial necrosis termed:",
         ["'Tiger heart' (myocarditis with grayish-yellow stripes)", "Cor bovinum", "Nutmeg heart", "Bread-and-butter heart"],
         0, "In young calves, the FMD virus (Aphthovirus) exhibits neurotropic/myotropic affinity, producing acute multifocal myocardial necrosis appearing as pale yellowish streaks ('tiger heart')."),
        ("The 'pipe-stem liver' characterized by massively fibrosed, calcified, protruding bile ducts in cattle is pathognomonic for chronic infection by:",
         ["Fasciola hepatica (or Fasciola gigantica)", "Echinococcus granulosus", "Haemonchus contortus", "Ascaris suum"],
         0, "Chronic biliary flukes inhabit the major bile ducts, inducing marked pericholangitis, epithelial hyperplasia, and calcification that resembles clay pipe stems."),
        ("The 'milk spot liver' in pigs is caused by the larval migration of:",
         ["Ascaris suum", "Stephanurus dentatus", "Trichinella spiralis", "Metastrongylus apri"],
         0, "Migrating L3 larvae of Ascaris suum penetrate liver parenchyma, inducing focal eosinophilic hepatitis that heals with whitish fibrous scars ('milk spots')."),
        ("'Pimply gut' (multiple nodular granulomas in the intestinal wall of sheep) is caused by the larvae of:",
         ["Oesophagostomum columbianum", "Haemonchus contortus", "Nematodirus battus", "Moniezia expansa"],
         0, "Larvae of Oesophagostomum encyst in the submucosa of the small and large intestine, provoking caseocalcareous foreign-body granulomas termed pimply gut."),
        ("'Bottle jaw' (submandibular edema) in small ruminants with Haemonchosis is primarily a result of:",
         ["Severe hypoproteinemia (hypoalbuminemia) reducing plasma oncotic pressure due to abomasal blood loss", "Lymphatic obstruction by adult worms", "Congestive heart failure", "Renal amyloidosis"],
         0, "Haemonchus contortus adults consume ~0.05 ml blood/worm/day in the abomasum; massive blood loss drains albumin, collapsing intravascular oncotic pressure and causing ventral dependent edema."),
        ("In equine strangles (Streptococcus equi subsp. equi), the characteristic pathology is:",
         ["Suppurative lymphadenitis and abscessation of the submandibular and retropharyngeal lymph nodes", "Fibrinous pleuropneumonia", "Enteritis", "Encephalitis"],
         0, "S. equi causes acute purulent inflammation and abscessation of lymph nodes draining the upper respiratory tract, which can compress the pharynx/larynx (strangles)."),
        ("The pathognomonic lesion of 'Glanders' (Burkholderia mallei) in horses is the formation of nodules and ulcerations in the respiratory tract and skin healing with:",
         ["Stellate (star-shaped) scars", "Button ulcers", "Rhomboid plaques", "Ringworm lesions"],
         0, "Nodules on the nasal septum break down into crater-like ulcers which heal by fibrosis to form diagnostic stellate (star-shaped) cicatrices.")
    ]

    for idx, item in enumerate(raw_vpp[:120]):
        questions.append({
            "id": f"vpp_q_{idx+1:03d}",
            "domain": "veterinary_science",
            "year": "2nd_year",
            "subjectId": "vpp",
            "topic": "Veterinary Pathology",
            "questionText": item[0],
            "options": item[1],
            "correctOptionIndex": item[2],
            "explanation": item[3],
            "difficulty": "Medium",
            "tags": ["Pathology", "VPP"],
            "createdAt": 1773000000000 + idx
        })
    return questions

if __name__ == "__main__":
    qs = get_vpp_questions()
    print(f"Loaded {len(qs)} Veterinary Pathology questions.")
