# scripts/data_vpa.py
# 120 High-Yield Questions for Veterinary Parasitology (VPA)

def get_vpa_questions():
    questions = []

    raw_vpa = [
        # 1-30: Trematodes & Cestodes
        ("The intermediate snail host for the common liver fluke (Fasciola hepatica) in temperate zones is:",
         ["Lymnaea truncatula", "Indoplanorbis exustus", "Bithynia tentaculata", "Helix aspersa"],
         0, "Lymnaea truncatula (mud snail) is the primary intermediate host for F. hepatica; in tropical Asia, Lymnaea auricularia transmits F. gigantica."),
        ("The infective stage of Fasciola hepatica to grazing ruminants ingested on aquatic herbage is the:",
         ["Encysted Metacercaria", "Miracidium", "Cercaria", "Redia"],
         0, "Cercariae shed from snails encyst on blades of grass and pond margins as resistant metacercariae, which excyst in the duodenum upon ingestion."),
        ("The drug of choice that is uniquely effective against BOTH juvenile (migrating immature) and adult Fasciola flukes in cattle and sheep is:",
         ["Triclabendazole", "Albendazole", "Oxyclozanide", "Praziquantel"],
         0, "Triclabendazole (a halogenated benzimidazole) is uniquely effective against very early immature flukes (>1-2 weeks old) as well as mature adult liver flukes."),
        ("Schistosoma nasale in cattle causes snoring disease (nasal granuloma), and its eggs are characteristically:",
         ["Boomerang or spindle-shaped with a terminal spine", "Oval with an operculum", "Spherical with radial striations", "Barrel-shaped with bipolar plugs"],
         0, "S. nasale adult worms reside in nasal veins; their characteristic boomerang-shaped eggs with a small terminal spine induce granulomatous polypoid rhinitis."),
        ("The intermediate host for the lancet fluke (Dicrocoelium dendriticum) that undergoes behavioral modification ('zombie ant' phenomenon) is:",
         ["Brown ant (Formica fusca)", "Water snail (Lymnaea)", "Oribatid mite", "Beetle"],
         0, "A metacercaria encysts in the subesophageal ganglion (brain worm) of the ant Formica fusca, inducing temperature-dependent mandibular tetany on blade tips to get eaten by sheep."),
        ("Immature flukes of Paramphistomum cervi (rumen fluke) cause severe clinical disease characterized by fetid diarrhea and bottle jaw while migrating in the:",
         ["Duodenum and upper jejunum", "Bile ducts", "Reticulum", "Peritoneal cavity"],
         0, "Massive numbers of plug-feeding juvenile paramphistomes burrow deeply into the duodenal mucosa, causing severe catarrhal and hemorrhagic enteritis and acute death."),
        ("The larval stage (metacestode) of Taenia saginata (beef tapeworm) encysted in bovine cardiac and skeletal muscle is named:",
         ["Cysticercus bovis", "Cysticercus cellulosae", "Coenurus cerebralis", "Hydatid cyst"],
         0, "Cysticercus bovis (measly beef) is the intermediate larval stage found in cattle; adult Taenia saginata tapeworms develop exclusively in the human small intestine."),
        ("The intermediate larval stage of Taenia solium found in pork muscle that can cause human neurocysticercosis is:",
         ["Cysticercus cellulosae", "Cysticercus bovis", "Cysticercus tenuicollis", "Strobilocercus"],
         0, "Cysticercus cellulosae (measly pork) develops in pigs and humans upon ingesting eggs; in humans, oncospheres migrate to the brain, producing life-threatening neurocysticercosis."),
        ("The definitive host for the tapeworm Echinococcus granulosus (which causes hydatid cyst disease in livestock and humans) is the:",
         ["Dog (Canids)", "Sheep", "Cow", "Human"],
         0, "The tiny adult tapeworm (only 3-6 mm, consisting of 3 proglottids) lives in the small intestine of dogs and wild canids; herbivores and humans are intermediate hosts carrying hydatid cysts."),
        ("Hydatid cysts of Echinococcus granulosus contain fluid and multiple brood capsules with protoscolices, collectively termed:",
         ["Hydatid sand", "Cysticercus", "Coracidium", "Oncosphere"],
         0, "The internal germinal layer buds off thousands of microscopic brood capsules and invaginated protoscolices, which detach to form granular sediment termed hydatid sand."),
        ("'Gid' or 'Sturdy' (circling disease, head deviation, blindness) in sheep is caused by the pressure of Coenurus cerebralis, which is the larval stage of:",
         ["Taenia multiceps (adult in dog)", "Taenia hydatigena", "Taenia ovis", "Echinococcus multilocularis"],
         0, "Coenurus cerebralis is a fluid-filled cyst containing hundreds of scoleces developing in the brain or spinal cord of sheep following ingestion of Taenia multiceps eggs from dogs."),
        ("The intermediate host required to complete the life cycle of the common sheep tapeworm Moniezia expansa is an:",
         ["Oribatid forage mite (free-living pasture mite)", "Aquatic snail", "Flea", "Tick"],
         0, "Cysticercoids of Moniezia develop inside microscopic oribatid pasture mites (family Oribatidae) that inhabit grass roots, ingested unintentionally by grazing ruminants."),
        ("Eggs of Moniezia expansa are distinctive under microscopic fecal flotation because they possess a triangular/round shape with a unique inner:",
         ["Pyriform apparatus (pear-shaped embryophore containing the hexacanth embryo)", "Bipolar plugs", "Operculum", "Radial striations"],
         0, "Moniezia eggs have a distinctive pear-shaped inner chitinous structure termed the pyriform apparatus housing the oncosphere."),
        ("Dipylidium caninum (the double-pored tapeworm of dogs and cats) is transmitted by ingestion of infected:",
         ["Adult fleas (Ctenocephalides canis / felis) or biting lice (Trichodectes canis)", "Pasture mites", "Snails", "Raw beef"],
         0, "Flea larvae ingest Dipylidium egg packets; the tapeworm metacestode (cysticercoid) matures in the adult flea and infects dogs when they chew fleas during grooming."),

        # 31-60: Nematodes (Roundworms)
        ("Haemonchus contortus (the 'barber’s pole worm') inhabits which organ of sheep and goats?",
         ["Abomasum", "Small intestine", "Cecum", "Reticulum"],
         0, "Adult H. contortus attach to the abomasal mucosa; the white egg-filled uteri spiraling around the blood-filled red gut gives the female worm the classic barber's pole appearance."),
        ("The 'FAMACHA' scoring system is an on-farm diagnostic tool developed to selectively treat Haemonchosis in small ruminants based on:",
         ["Conjunctival mucous membrane pallor (color scoring 1 to 5)", "Body temperature", "Fecal consistency", "Teat skin color"],
         0, "FAMACHA assesses the degree of anemia caused by Haemonchus blood-sucking by matching the color of the lower eyelid conjunctiva against a 5-color chart."),
        ("The 'milk spot liver' observed at pig slaughter is a pathological scar caused by the migrating larvae of:",
         ["Ascaris suum", "Stephanurus dentatus", "Trichuris suis", "Metastrongylus apri"],
         0, "Ingested L3 larvae of Ascaris suum hatch, penetrate the cecal wall, and migrate via the portal vein to the liver, causing eosinophilic necrosis that heals into white fibrous 'milk spots'."),
        ("The primary route of infection for Toxocara canis in neonatal puppies, often resulting in heavy intestinal roundworm burdens at 2-3 weeks of age, is:",
         ["Transplacental (prenatal) migration of somatic L3 larvae from dam to fetus", "Transmammary via colostrum exclusively", "Skin penetration", "Ingestion of earthworms"],
         0, "Dormant encysted somatic larvae in the pregnant bitch activate around day 42 of gestation and migrate transplacentally into the fetal liver and lungs."),
        ("Ancylostoma caninum (canine hookworm) is a voracious blood-sucker in the small intestine that possesses cutting teeth and secretes anticoagulants, predominantly transmitted to nursing pups via:",
         ["Transmammary route (via bitch's milk during first 3 weeks of lactation)", "Airborne droplets", "Flea bites", "Tick bites"],
         0, "Reactivated somatic L3 larvae in the lactating bitch pass into milk, causing peracute fatal hemorrhagic anemia in 2 to 3-week-old suckling puppies."),
        ("Dirofilaria immitis (canine heartworm) is transmitted biologically by which insect vector?",
         ["Mosquitoes (Culicidae: Culex, Aedes, Anopheles)", "Ticks (Ixodidae)", "Fleas (Ctenocephalides)", "Biting midges (Culicoides)"],
         0, "Mosquitoes ingest circulating L1 microfilariae from infected dogs; larvae develop into infective L3 within the mosquito Malpighian tubules and enter the host during a bite."),
        ("Adult Dirofilaria immitis worms in severe canine heartworm disease reside primarily in the:",
         ["Pulmonary arteries and right ventricle", "Left ventricle and aorta", "Cranial vena cava", "Hepatic portal vein"],
         0, "Adult heartworms live primarily in the pulmonary arterial tree; in heavy infections (caval syndrome), worms back up into the right ventricle and right atrium."),
        ("The 'Knott’s test' (or modified Knott's technique) is a standard concentration method used in veterinary clinics to detect:",
         ["Circulating microfilariae in peripheral blood", "Fecal fluke eggs", "Mange mites in skin", "Trichomonads"],
         0, "The Knott's technique lyses red blood cells with 2% formalin and stains microfilariae with 0.1% methylene blue for microscopic differentiation of D. immitis from Acanthocheilonema."),
        ("The bovine lungworm that causes parasitic bronchitis ('husk' or 'hoose') in calves is:",
         ["Dictyocaulus viviparus", "Metastrongylus apri", "Muellerius capillaris", "Ascaris suum"],
         0, "Dictyocaulus viviparus lives in the bronchi and trachea of cattle, producing coughing, tachypnea, and parasitic pneumonia; L1 larvae are shed in feces and diagnosed by Baermann technique."),
        ("The 'Baermann technique' is the diagnostic laboratory method of choice for recovering which parasitic stage from fresh fecal samples?",
         ["Live nematode larvae (e.g. Dictyocaulus, Strongyloides, Aelurostrongylus)", "Operculated trematode eggs", "Coccidian oocysts", "Tapeworm segments"],
         0, "The Baermann apparatus utilizes the hydrotropism and positive geotropism of active live nematode larvae, which migrate out of warm water-immersed feces and sink to the funnel tip."),
        ("The 'trichostrongyle' nematode of sheep with an exceptionally large egg (more than 150 microns) and whose L3 larvae hatch directly on pasture without L1/L2 free stages is:",
         ["Nematodirus battus", "Haemonchus contortus", "Trichostrongylus axei", "Teladorsagia circumcincta"],
         0, "Nematodirus eggs are massive (approx 150-200 x 80-100 um); larvae develop to L3 inside the durable eggshell and require a cold chilling period followed by spring warmth to hatch en masse."),
        ("Trichinella spiralis is unique among nematodes because:",
         ["The same individual animal host acts as both definitive and intermediate host", "It has an aquatic snail vector", "It lays operculated eggs", "It lives free in the soil"],
         0, "Adult Trichinella worms mate in the small intestinal mucosa; females produce newborn larvae that enter the bloodstream and encyst inside nurse cells in striated skeletal muscle of the same host."),

        # 61-90: Entomology & Acarology (Insects, Ticks, Mites)
        ("Culicoides biting midges ('no-see-ums' / punkies) are biological vectors for which major veterinary viral diseases?",
         ["Bluetongue virus and African Horse Sickness virus", "Foot and Mouth Disease", "Anthrax", "Rabies"],
         0, "Culicoides midges (family Ceratopogonidae) transmit orbiviruses including Bluetongue in ruminants and African Horse Sickness in equids, as well as causing sweet itch hypersensitivity."),
        ("Tabanus (horse flies) and Stomoxys calcitrans (stable flies) act as significant mechanical vectors for:",
         ["Trypanosoma evansi (Surra) and Bacillus anthracis (Anthrax)", "Bluetongue", "Babesia bigemina", "Theileria annulata"],
         0, "The painful bites of Tabanid flies cause interrupted feeding; blood-contaminated slashing mouthparts mechanically transfer T. evansi and B. anthracis between animals within minutes."),
        ("Hypoderma bovis (the ox warble fly / heel fly) causes damage to bovine hides because its L3 larvae:",
         ["Cut breathing holes through the subcutaneous skin along the back line", "Burrow into the liver", "Bite the hooves", "Invade the brain"],
         0, "Hypoderma larvae migrate internally through the spinal canal (H. bovis) or esophagus (H. lineatum) to reach the dorsal back skin in spring, creating warble pores that ruin leather value."),
        ("Oestrus ovis (the sheep nasal bot fly) is biologically unique among dipteran flies because it is:",
         ["Larviparous (deposits live L1 larvae directly into the nostrils of sheep in flight)", "Oviparous (lays eggs)", "Pupiparous", "Parthenogenetic"],
         0, "Female Oestrus ovis flies dart at the nostrils of sheep to squirt squirming L1 larvae, which crawl up the nasal turbinates into the frontal sinuses, provoking catarrhal sinusitis ('false gid')."),
        ("Boophilus (Rhipicephalus) microplus is classified as a:",
         ["One-host tick (completing larval, nymphal, and adult stages on a single bovine host)", "Two-host tick", "Three-host tick", "Soft tick (Argasid)"],
         0, "Boophilus microplus attaches to cattle as a larva and remains on the same individual through moults until engorged females drop off to lay eggs; it transmits Babesia bigemina and B. bovis."),
        ("Hyalomma anatolicum is the principal tick vector for which protozoan parasite of cattle in India?",
         ["Theileria annulata (Tropical Theileriosis)", "Babesia canis", "Trypanosoma evansi", "Histomonas meleagridis"],
         0, "Hyalomma anatolicum (a two- or three-host hard tick) acquires Theileria piroplasms from infected cattle and transmits sporozoites during subsequent feeding stages."),
        ("Rhipicephalus sanguineus (the brown dog tick) is an inornate, three-host tick that transmits:",
         ["Babesia canis and Ehrlichia canis", "Theileria annulata", "Trypanosoma evansi", "Fasciola hepatica"],
         0, "The brown dog tick is adapted to kennels and domestic homes, serving as the primary vector for canine babesiosis (B. canis vogeli) and monocytic ehrlichiosis (E. canis)."),
        ("Sarcoptes scabiei (the cause of sarcoptic mange / scabies) is distinguished from other mites because it:",
         ["Burrows into the stratum corneum of the epidermis, creating intense, intensely pruritic tunnels", "Lives exclusively in hair follicles", "Feeds strictly on surface scales", "Infests only the ear canal"],
         0, "Female Sarcoptes mites burrow tortuous intraepidermal tunnels, triggering intense Type I and IV hypersensitivity, profound pruritus, alopecia, and thick hyperkeratotic crusts."),
        ("Demodex canis (the canine follicular mange mite) is morphologically characterized by:",
         ["An elongated, cigar-shaped / alligator-shaped body with 4 pairs of stubby anterior legs", "A round, flattened tortoise-like body", "Long segmented pedicels", "Piercing stylets"],
         0, "Demodex mites reside deep within hair follicles and sebaceous glands; diagnosis requires a deep skin scraping that squeezes capillaries until capillary bleeding is observed."),
        ("Psoroptes ovis is the non-burrowing mite responsible for 'sheep scab', causing severe damage by:",
         ["Piercing the skin surface with stylets to suck lymph, inducing exudative crusts and fleece loss", "Burrowing deep into dermis", "Entering ears exclusively", "Invading lungs"],
         0, "Psoroptes mites possess long, 3-segmented pedicels with funnel-shaped suckers; they abrade the epidermis to feed on serous exudate, causing widespread fleece loss and debility in sheep flocks."),

        # 91-120: Veterinary Protozoology
        ("The causative agent of 'Surra' in camels, horses, and cattle is:",
         ["Trypanosoma evansi", "Trypanosoma theileri", "Trypanosoma cruzi", "Leishmania donovani"],
         0, "Trypanosoma evansi is a salivarian, monomorphic flagellate parasite living extracellularly in blood plasma, causing acute fatal Surra in horses and wasting disease in camels."),
        ("Under wet blood film examination under high power, Trypanosoma evansi is recognized by its:",
         ["Extremely active, rapid, darting motility across the field displacing erythrocytes", "Stationary intracellular position", "Slow amoeboid crawling", "Flagella inside white cells"],
         0, "Living trypanosomes undulate rapidly via an undulating membrane and long free flagellum, actively buffeting and displacing red blood cells in a fresh wet mount drop."),
        ("The pathognomonic intraerythrocytic appearance of Babesia bigemina under Giemsa-stained thin blood smears is:",
         ["Large, paired pyriform (pear-shaped) bodies joined at an acute angle inside erythrocytes", "Small round ring forms", "Maltese cross appearance", "Comma shapes"],
         0, "Babesia bigemina is a large Babesia (>3-5 um); classical diagnosis is made by identifying two pear-shaped trophozoites joined at their pointed ends at an acute angle."),
        ("The pathognomonic diagnostic microscopic feature of Theileria annulata found in lymph node aspirates is:",
         ["Koch’s blue bodies (macroschizonts inside transformed lymphoblasts)", "Intraerythrocytic pyriform pairs", "Trypomastigotes in plasma", "Amastigotes in neutrophils"],
         0, "Theileria sporozoites infect mononuclear leukocytes, transforming them into dividing lymphoblasts containing multinucleated schizonts termed Koch's blue bodies (diagnostic on lymph node biopsy)."),
        ("The drug of choice for the clinical treatment of bovine Tropical Theileriosis (Theileria annulata) is:",
         ["Buparvaquone", "Diminazene aceturate", "Amprolium", "Ivermectin"],
         0, "Buparvaquone (a hydroxynaphthoquinone, given at 2.5 mg/kg IM) is highly specific and curative for theileriosis by blocking electron transport in parasite mitochondria."),
        ("The standard chemotherapeutic agent widely used for treating bovine Babesiosis and Trypanosomosis (Surra) in India is:",
         ["Diminazene aceturate (Berenil)", "Buparvaquone", "Albendazole", "Piperazine"],
         0, "Diminazene aceturate (at 3.5 to 7.0 mg/kg IM) binds parasitic DNA, effectively curing Babesia bigemina and Trypanosoma evansi infections."),
        ("Anaplasma marginale is an intraerythrocytic rickettsial organism characterized under Giemsa stain as:",
         ["Dense, round, purplish inclusion bodies situated strictly near the periphery (margin) of red blood cells", "Paired pear-shaped bodies", "Flagellated spindle cells", "Cysts"],
         0, "A. marginale appears as a solitary, densely chromatic round body situated at or near the outer rim (margin) of the bovine erythrocyte, inducing severe extravascular immune-mediated hemolysis."),
        ("Cecal coccidiosis in commercial broiler chicks, characterized by bloody droppings and massive cecal hemorrhage, is caused by:",
         ["Eimeria tenella", "Eimeria acervulina", "Eimeria maxima", "Eimeria mitis"],
         0, "Eimeria tenella develops deep in the cecal submucosa of chickens; second-generation schizonts rupture extensive capillary networks, producing severe, often fatal cecal hemorrhage on day 5 post-infection."),
        ("The premier drug used for the prevention and treatment of poultry coccidiosis in drinking water is:",
         ["Toltrazuril (or Amprolium)", "Penicillin", "Ivermectin", "Levamisole"],
         0, "Toltrazuril acts against all intracellular developmental stages (schizonts and gametocytes) of Eimeria species by interfering with mitochondrial respiration."),
        ("The definitive host of Toxoplasma gondii, which is the ONLY host that sheds infective oocysts in feces, is the:",
         ["Domestic and wild felids (Cat family)", "Dog", "Sheep", "Human"],
         0, "The sexual coccidian phase (enteroepithelial cycle) occurs exclusively in felids; cats shed unsporulated oocysts that sporulate in the environment to infect all warm-blooded intermediate hosts."),
        ("In pregnant ewes, Toxoplasma gondii infection classically causes abortion characterized grossly by:",
         ["White, chalky necrotic foci ('flecked appearance') on maternal caruncles and fetal cotyledons", "Uniform liquefaction of placenta", "Mummification exclusively", "Purulent endometritis"],
         0, "Toxoplasmosis in pregnant sheep produces pathognomonic focal necrosis and calcification limited strictly to the cotyledons, appearing as bright white flecks on red cotyledons with normal intercotyledonary membranes.")
    ]

    for idx, item in enumerate(raw_vpa[:120]):
        questions.append({
            "id": f"vpa_q_{idx+1:03d}",
            "domain": "veterinary_science",
            "year": "2nd_year",
            "subjectId": "vpa",
            "topic": "Veterinary Parasitology",
            "questionText": item[0],
            "options": item[1],
            "correctOptionIndex": item[2],
            "explanation": item[3],
            "difficulty": "Medium",
            "tags": ["Parasitology", "VPA"],
            "createdAt": 1773000000000 + idx
        })
    return questions

if __name__ == "__main__":
    qs = get_vpa_questions()
    print(f"Loaded {len(qs)} Veterinary Parasitology questions.")
