# scripts/data_vbc.py
# 120 High-Yield Questions for Veterinary Biochemistry (VBC)

def get_vbc_questions():
    questions = []

    raw_vbc = [
        # 1-30: Carbohydrate Metabolism & Enzymology
        ("The committed, rate-limiting regulatory enzyme of glycolysis is:",
         ["Phosphofructokinase-1 (PFK-1)", "Hexokinase", "Pyruvate kinase", "Aldolase"],
         0, "PFK-1 catalyzes the irreversible phosphorylation of fructose-6-phosphate to fructose-1,6-bisphosphate, allosterically activated by AMP and fructose-2,6-bisphosphate and inhibited by ATP and citrate."),
        ("In ruminants, what is the primary volatile fatty acid that contributes to net glucose synthesis (gluconeogenesis)?",
         ["Propionate (Propionic acid)", "Acetate", "Butyrate", "Isobutyrate"],
         0, "Propionate is converted to propionyl-CoA, then to methylmalonyl-CoA (requiring Biotin and Vitamin B12), entering the TCA cycle as succinyl-CoA for gluconeogenesis."),
        ("The conversion of propionyl-CoA to methylmalonyl-CoA in ruminant gluconeogenesis requires which B-vitamin cofactor?",
         ["Biotin (Vitamin B7)", "Thiamine (Vitamin B1)", "Riboflavin (Vitamin B2)", "Niacin (Vitamin B3)"],
         0, "Propionyl-CoA carboxylase requires Biotin (Vitamin B7), ATP, and CO2, whereas the subsequent mutase requires Vitamin B12 (cobalamin)."),
        ("The isomerization of methylmalonyl-CoA to succinyl-CoA is catalyzed by a mutase requiring which coenzyme?",
         ["Adenosylcobalamin (Vitamin B12)", "Thiamine pyrophosphate (TPP)", "Pyridoxal phosphate (PLP)", "FAD"],
         0, "Methylmalonyl-CoA mutase requires 5'-deoxyadenosylcobalamin (Vitamin B12); cobalt deficiency in ruminants impairs this step, leading to wasting disease (pine / coast disease)."),
        ("The primary regulatory enzyme of glycogenolysis in skeletal muscle and liver is:",
         ["Glycogen phosphorylase", "Glycogen synthase", "Branching enzyme", "Debranching enzyme"],
         0, "Glycogen phosphorylase cleaves alpha-1,4 glycosidic bonds phosphorolytically to yield glucose-1-phosphate, activated by phosphorylation (via phosphorylase kinase)."),
        ("The rate-limiting enzyme of the citric acid (Krebs / TCA) cycle is:",
         ["Isocitrate dehydrogenase", "Citrate synthase", "Alpha-ketoglutarate dehydrogenase", "Malate dehydrogenase"],
         0, "Isocitrate dehydrogenase catalyzes the oxidative decarboxylation of isocitrate to alpha-ketoglutarate, allosterically activated by ADP and inhibited by ATP and NADH."),
        ("How many moles of ATP are theoretically generated from the complete oxidation of one mole of glucose to CO2 and H2O in aerobic conditions?",
         ["30 to 32 ATP", "2 ATP", "12 ATP", "48 ATP"],
         0, "Modern P/O ratio calculations (2.5 ATP per NADH, 1.5 ATP per FADH2) yield a net of 30 to 32 ATP per mole of glucose oxidized aerobically."),
        ("Under anaerobic conditions, pyruvate is reduced to lactate by lactate dehydrogenase (LDH) in order to regenerate:",
         ["NAD+ for continued glycolysis", "NADH", "ATP directly", "FAD"],
         0, "Lactate dehydrogenase reduces pyruvate to L-lactate, oxidizing NADH back to NAD+, which is obligatorily required by glyceraldehyde-3-phosphate dehydrogenase to sustain anaerobic glycolysis."),
        ("The 'Cori cycle' (lactic acid cycle) involves the transport of lactate from contracting muscle to which organ for gluconeogenesis?",
         ["Liver", "Kidney cortex", "Spleen", "Pancreas"],
         0, "Lactate produced in skeletal muscle diffuses into blood, travels to the liver where it is re-oxidized to pyruvate and converted back to glucose via gluconeogenesis."),
        ("The Pentose Phosphate Pathway (HMP shunt) is essential in erythrocytes and adipocytes because it generates:",
         ["NADPH and Ribose-5-phosphate", "ATP and NADH", "Lactic acid", "FADH2"],
         0, "Glucose-6-phosphate dehydrogenase (G6PD) produces NADPH, which maintains reduced glutathione to protect red cells against oxidative hemolysis and provides reducing equivalents for lipogenesis."),
        ("A competitive enzyme inhibitor affects kinetic parameters by:",
         ["Increasing apparent Km without changing Vmax", "Decreasing Vmax without changing Km", "Decreasing both Km and Vmax", "Increasing Vmax"],
         0, "Competitive inhibitors compete with substrate for the active site; higher substrate concentrations outcompete the inhibitor, so Vmax remains unchanged while apparent Km increases."),
        ("A non-competitive enzyme inhibitor affects kinetic parameters by:",
         ["Decreasing Vmax while leaving Km unchanged", "Increasing Km with unchanged Vmax", "Decreasing Km and increasing Vmax", "Increasing both"],
         0, "Non-competitive inhibitors bind to an allosteric site regardless of whether substrate is bound; this reduces the functional turnover number (lowering Vmax) without altering substrate affinity (Km unchanged)."),
        ("The Michaelis constant (Km) represents:",
         ["The substrate concentration at which reaction velocity is half of Vmax", "The maximum possible reaction speed", "The inhibitor concentration", "The turnover rate"],
         0, "Km is the substrate concentration ([S]) at which the reaction velocity equals half of maximal velocity (Vmax/2); lower Km indicates higher enzyme-substrate affinity."),
        ("The 'Lineweaver-Burk plot' is a double-reciprocal plot of:",
         ["1/v versus 1/[S]", "v versus [S]", "log v versus log [S]", "Km versus Vmax"],
         0, "The Lineweaver-Burk transformation yields a straight line where the y-intercept is 1/Vmax and the x-intercept is -1/Km."),
        ("The key regulatory enzyme of gluconeogenesis that bypasses pyruvate kinase is:",
         ["Pyruvate carboxylase and Phosphoenolpyruvate carboxykinase (PEPCK)", "Hexokinase", "Phosphofructokinase", "Glucokinase"],
         0, "Pyruvate carboxylase (mitochondrial, requiring Biotin and allosterically activated by Acetyl-CoA) converts pyruvate to oxaloacetate, which is converted to PEP by PEPCK."),
        ("The enzyme 'Glucose-6-phosphatase' is absent in which tissue, preventing it from releasing free glucose into the bloodstream?",
         ["Skeletal muscle", "Liver", "Renal cortex", "Intestinal epithelium"],
         0, "Skeletal muscle lacks glucose-6-phosphatase; muscle glycogen can only be used intracellularly for its own energy via glycolysis."),
        ("In cats, gluconeogenesis is unique because:",
         ["Key gluconeogenic enzymes in the liver are continuously active even on high-protein diets", "Cats cannot synthesize glucose", "Cats use only carbohydrates", "Cats lack PEPCK"],
         0, "Obligate carnivores like cats have high, constitutive baseline hepatic gluconeogenic enzyme activity (PEPCK, ALT, AST) to produce glucose from dietary amino acids."),

        # 18-45: Lipid Metabolism & Ketogenesis
        ("The transport of long-chain fatty acyl-CoA into the mitochondrial matrix for beta-oxidation requires which carrier shuttle?",
         ["Carnitine shuttle (CPT-I and CPT-II)", "Citrate shuttle", "Glycerol phosphate shuttle", "Malate-aspartate shuttle"],
         0, "Carnitine Palmitoyltransferase-I (CPT-I) on the outer mitochondrial membrane conjugates fatty acyl-CoA to carnitine, translocated by CACT and reformed by CPT-II."),
        ("The rate-limiting regulatory enzyme of fatty acid beta-oxidation is:",
         ["Carnitine Palmitoyltransferase-I (CPT-I)", "Acyl-CoA dehydrogenase", "Thiolase", "Enoyl-CoA hydratase"],
         0, "CPT-I is the gatekeeper of beta-oxidation and is allosterically inhibited by Malonyl-CoA (the product of fatty acid synthesis), preventing simultaneous synthesis and oxidation."),
        ("Each round of fatty acid beta-oxidation yields:",
         ["1 Acetyl-CoA, 1 FADH2, and 1 NADH", "1 Pyruvate and 2 ATP", "1 Propionyl-CoA", "1 Glucose molecule"],
         0, "A 4-step spiral cycle (oxidation, hydration, oxidation, thiolysis) shortens the acyl chain by 2 carbons, producing 1 Acetyl-CoA, 1 FADH2, and 1 NADH."),
        ("The three physiological ketone bodies produced by the mammalian liver are:",
         ["Acetoacetate, Beta-hydroxybutyrate, and Acetone", "Pyruvate, Lactate, and Citrate", "Alanine, Glycine, and Serine", "Acetate, Propionate, and Butyrate"],
         0, "Ketogenesis in liver mitochondria produces acetoacetate, which can be enzymatically reduced to beta-hydroxybutyrate or spontaneously decarboxylated to volatile acetone."),
        ("Ketone body synthesis (ketogenesis) occurs exclusively in the mitochondria of which organ?",
         ["Liver", "Skeletal muscle", "Kidney medulla", "Brain"],
         0, "Hepatocytes are the only cells with high levels of HMG-CoA synthase; however, the liver cannot utilize ketone bodies because it lacks thiophorase (succinyl-CoA:3-ketoacid CoA transferase)."),
        ("The rate-limiting enzyme of ketogenesis in hepatic mitochondria is:",
         ["Mitochondrial HMG-CoA synthase", "HMG-CoA reductase", "Thiolase", "Acetoacetate decarboxylase"],
         0, "Mitochondrial HMG-CoA synthase condenses acetoacetyl-CoA with acetyl-CoA to form HMG-CoA, which is cleaved by HMG-CoA lyase to release acetoacetate."),
        ("The rate-limiting enzyme of cholesterol biosynthesis is:",
         ["HMG-CoA reductase (target of statin drugs)", "HMG-CoA synthase", "Squalene synthase", "Mevalonate kinase"],
         0, "Microsomal HMG-CoA reductase reduces HMG-CoA to mevalonate using 2 NADPH; this is the primary pharmacological target of statins."),
        ("Pregnancy toxemia in ewes (twin lamb disease) and bovine ketosis are fundamentally caused by:",
         ["Severe negative energy balance leading to extreme lipolysis and oxaloacetate depletion", "Excess carbohydrate intake", "Vitamin C toxicity", "Hypomagnesemia"],
         0, "High fetal glucose demand or high milk production outstrips gluconeogenesis, depleting oxaloacetate; acetyl-CoA from runaway lipolysis cannot enter the TCA cycle and is shunted into ketogenesis."),
        ("The 'rate-limiting enzyme' of de novo fatty acid synthesis in the cytoplasm is:",
         ["Acetyl-CoA carboxylase (ACC)", "Fatty acid synthase", "Citrate lyase", "Malic enzyme"],
         0, "Acetyl-CoA carboxylase (requiring Biotin) converts acetyl-CoA to malonyl-CoA, allosterically activated by citrate and inhibited by palmitoyl-CoA."),
        ("Which lipoprotein is responsible for transporting dietary exogenous lipids (triglycerides) from the intestine via lymph into blood?",
         ["Chylomicrons", "Very Low-Density Lipoproteins (VLDL)", "Low-Density Lipoproteins (LDL)", "High-Density Lipoproteins (HDL)"],
         0, "Chylomicrons synthesized in intestinal enterocytes carry dietary triacylglycerols through the thoracic duct into the systemic venous circulation."),
        ("Which apolipoprotein on the surface of chylomicrons and VLDL activates capillary endothelial Lipoprotein Lipase (LPL)?",
         ["Apo C-II", "Apo B-100", "Apo E", "Apo A-I"],
         0, "Apolipoprotein C-II serves as an obligate cofactor to activate endothelial lipoprotein lipase, which hydrolyzes triglycerides into free fatty acids and glycerol."),
        ("The 'brown adipose tissue' (BAT) generates heat via non-shivering thermogenesis in neonates through which uncoupling protein in the inner mitochondrial membrane?",
         ["Thermogenin (UCP-1)", "Cytochrome c", "ATP synthase", "Complex I"],
         0, "Thermogenin (Uncoupling Protein-1) dissipates the proton gradient across the inner mitochondrial membrane as heat instead of driving ATP synthesis."),
        ("The essential fatty acids required in feline diets that cats cannot synthesize from linoleic acid are:",
         ["Arachidonic acid (due to lack of delta-6 desaturase activity)", "Palmitic acid", "Stearic acid", "Oleic acid"],
         0, "Cats possess negligible delta-6 desaturase activity in the liver and obligatorily require preformed arachidonic acid in their diet from animal tissues."),

        # 46-75: Protein Metabolism, Urea Cycle & Nucleic Acids
        ("The primary regulatory, rate-limiting enzyme of the urea cycle located in hepatic mitochondria is:",
         ["Carbamoyl phosphate synthetase I (CPS-I)", "Ornithine transcarbamylase (OTC)", "Argininosuccinate synthetase", "Arginase"],
         0, "CPS-I condenses NH4+ and bicarbonate into carbamoyl phosphate using 2 ATP; it is obligatorily activated allosterically by N-acetylglutamate (NAG)."),
        ("The allosteric activator required for the catalytic function of Carbamoyl Phosphate Synthetase I (CPS-I) is:",
         ["N-acetylglutamate (NAG)", "Citrate", "Fructose-2,6-bisphosphate", "AMP"],
         0, "N-acetylglutamate is synthesized by NAG synthase from acetyl-CoA and glutamate; high protein intake raises arginine, which stimulates NAG synthase and activates the urea cycle."),
        ("The two amino acids that directly contribute nitrogen atoms to the urea molecule are:",
         ["Ammonia (free NH4+) and Aspartate", "Glutamate and Alanine", "Glycine and Serine", "Leucine and Lysine"],
         0, "One nitrogen of urea enters as free ammonia via carbamoyl phosphate; the second nitrogen is contributed by the amino group of aspartate via argininosuccinate synthetase."),
        ("In the urea cycle, the enzyme 'arginase' cleaves arginine to yield urea and regenerate:",
         ["Ornithine", "Citrulline", "Argininosuccinate", "Fumarate"],
         0, "Cytosolic arginase hydrolyzes L-arginine to produce urea and regenerate L-ornithine, which re-enters the mitochondrion via the ORNT1 transporter to continue the cycle."),
        ("Dalmatian dogs have an inherited metabolic predisposition to form which type of urinary calculi?",
         ["Ammonium urate (Uric acid) uroliths", "Calcium oxalate", "Struvite (triple phosphate)", "Cystine"],
         0, "Dalmatians carry a mutation in the SLC2A9 uric acid transporter, impairing hepatic uptake and conversion of uric acid to allantoin by urate oxidase, causing severe hyperuricosuria."),
        ("The end product of purine catabolism in domestic mammals (except humans, apes, and Dalmatians) is:",
         ["Allantoin (via urate oxidase / uricase)", "Uric acid", "Urea", "Xanthine"],
         0, "Non-primate mammals express urate oxidase (uricase) in liver peroxisomes, which oxidizes sparingly soluble uric acid into highly water-soluble allantoin."),
        ("Transamination reactions require which B-vitamin coenzyme to transfer amino groups to alpha-ketoacids?",
         ["Pyridoxal-5'-phosphate (PLP / Vitamin B6)", "Thiamine pyrophosphate (TPP)", "Niacin (NAD)", "Riboflavin (FMN)"],
         0, "All transaminases (ALT, AST) utilize Pyridoxal Phosphate (PLP derived from Vitamin B6), which forms a Schiff base intermediate to shuttle amino groups."),
        ("The amino acid that serves as the major carrier of amino groups from contracting skeletal muscle to the liver is:",
         ["Alanine (via Glucose-Alanine cycle)", "Asparagine", "Proline", "Valine"],
         0, "In the Cahill (glucose-alanine) cycle, muscle pyruvate is transaminated to alanine, exported to the liver, and converted back to pyruvate for gluconeogenesis while releasing ammonia for urea synthesis."),
        ("The two purely ketogenic amino acids that cannot be converted to glucose are:",
         ["Leucine and Lysine", "Alanine and Glycine", "Methionine and Cysteine", "Glutamate and Aspartate"],
         0, "Leucine and lysine yield only acetyl-CoA and acetoacetate; they have no pathway to form pyruvate or TCA cycle intermediates for net gluconeogenesis."),
        ("Which amino acid is the direct precursor for the neurotransmitter serotonin (5-HT) and the hormone melatonin?",
         ["Tryptophan", "Tyrosine", "Phenylalanine", "Histidine"],
         0, "Tryptophan is hydroxylated by tryptophan hydroxylase (requiring tetrahydrobiopterin) and decarboxylated to 5-hydroxytryptamine (serotonin), the precursor to melatonin."),
        ("Which amino acid is the direct precursor for catecholamines (dopamine, norepinephrine, epinephrine) and thyroid hormones?",
         ["Tyrosine (or Phenylalanine)", "Tryptophan", "Glutamine", "Arginine"],
         0, "Phenylalanine is converted to tyrosine by phenylalanine hydroxylase; tyrosine is then converted to DOPA, dopamine, catecholamines, and iodinated to thyroxine in the thyroid."),
        ("The primary sulfur-containing amino acids in mammalian biochemistry are:",
         ["Methionine and Cysteine", "Serine and Threonine", "Proline and Lysine", "Valine and Leucine"],
         0, "Methionine (essential) provides the methyl donor S-adenosylmethionine (SAM) and transfers its sulfur to cysteine via transsulfuration."),
        ("S-Adenosylmethionine (SAM) is the principal biological donor of:",
         ["Methyl (-CH3) groups", "Phosphate groups", "Amino groups", "Acyl groups"],
         0, "SAM is synthesized from ATP and methionine, acting as the universal methyl donor for DNA methylation, phosphatidylcholine synthesis, and epinephrine synthesis."),
        ("The genetic code is described as 'degenerate' (redundant) because:",
         ["Most amino acids are coded for by more than one triplet codon", "A single codon codes for multiple amino acids", "Codons overlap", "The code varies across tissues"],
         0, "There are 64 codons for only 20 standard amino acids; 61 sense codons code for amino acids, meaning multiple synonymous codons specify the same amino acid (wobble hypothesis)."),
        ("The 'start codon' that initiates eukaryotic and prokaryotic translation is:",
         ["AUG (coding for Methionine / N-formylmethionine)", "UAA", "UAG", "UGA"],
         0, "AUG specifies methionine in eukaryotes (and N-formylmethionine in prokaryotes), serving as the universal translation initiation signal."),
        ("The three standard 'stop codons' (nonsense codons) that terminate translation are:",
         ["UAA, UAG, and UGA", "AUG, GUG, and CUG", "AAA, UUU, and GGG", "UAC, UAU, and UGC"],
         0, "UAA (ochre), UAG (amber), and UGA (opal) are recognized by release factors rather than tRNAs, triggering ribosomal dissociation and peptide release."),

        # 76-105: Clinical Diagnostic Enzymology
        ("Serum Alanine Aminotransferase (ALT) is a specific biomarker of acute hepatocellular injury in which domestic species?",
         ["Dog and Cat", "Horse and Cow", "Sheep and Goat", "Bird"],
         0, "In dogs and cats, ALT is located in high concentrations in hepatocytes; in horses, ruminants, and birds, ALT activity in liver tissue is very low and clinically non-diagnostic."),
        ("The preferred, highly specific serum enzyme indicator for acute hepatocellular necrosis in horses and cattle is:",
         ["Sorbitol Dehydrogenase (SDH) and Glutamate Dehydrogenase (GLDH)", "Alanine Aminotransferase (ALT)", "Amylase", "Lipase"],
         0, "In large animals, SDH (Iditol dehydrogenase) and mitochondrial GLDH are the primary specific indicators of acute liver cell necrosis."),
        ("Elevated serum Gamma-Glutamyltransferase (GGT) and Alkaline Phosphatase (ALP) are hallmark indicators of:",
         ["Cholestasis (biliary stasis / obstruction)", "Skeletal muscle trauma", "Acute pancreatitis", "Glomerular nephritis"],
         0, "ALP and GGT are membrane-bound canalicular and biliary epithelial brush-border enzymes; bile duct distension or stasis upregulates their synthesis and shedding into serum."),
        ("A corticosteroid-induced isoenzyme of Alkaline Phosphatase (C-ALP) is uniquely produced in the liver of the:",
         ["Dog", "Cat", "Horse", "Cow"],
         0, "Dogs possess a unique corticosteroid-inducible ALP isoenzyme produced by hepatocytes in response to endogenous or exogenous glucocorticoids (Cushing's syndrome)."),
        ("Serum Creatine Kinase (CK / CPK) is the most sensitive and tissue-specific serum marker for:",
         ["Skeletal and cardiac muscle necrosis (myopathy)", "Renal tubular damage", "Hepatic cirrhosis", "Bone remodeling"],
         0, "CK is found almost exclusively in skeletal muscle, myocardium, and brain; muscle membrane rupture (myositis, capture myopathy, azoturia) releases massive amounts of CK into serum."),
        ("Serum Amylase and Lipase elevations exceeding 3-fold above reference limits in dogs are classic diagnostic markers for:",
         ["Acute Pancreatitis", "Hepatocellular carcinoma", "Renal failure", "Exocrine pancreatic insufficiency"],
         0, "Acinar cell damage in acute pancreatitis releases pancreatic digestive enzymes (amylase and lipase) directly into the peritoneum and systemic circulation."),
        ("The 'azotemia' characterized by elevated Blood Urea Nitrogen (BUN) and serum Creatinine can be classified into pre-renal, renal, and post-renal based on:",
         ["Urine specific gravity (USG) and clinical hydration status", "Blood glucose", "Serum albumin", "Blood pH"],
         0, "Pre-renal azotemia (dehydration/hypovolemia) exhibits concentrated urine (USG > 1.030 in dogs, > 1.035 in cats), whereas intrinsic renal azotemia shows isosthenuria (1.008 - 1.012)."),
        ("Troponin I (cTnI) is currently the gold-standard serum biomarker for:",
         ["Myocardial cell necrosis and cardiac injury", "Skeletal muscle strain", "Liver necrosis", "Pancreatitis"],
         0, "Cardiac troponin I (cTnI) is exclusively expressed in cardiomyocytes; any ischemic, infectious, or toxic injury to cardiac muscle releases cTnI within hours."),

        # 106-120: Vitamins & Minerals
        ("Deficiency of Vitamin E and/or Selenium in calves and lambs produces which classic pathological condition?",
         ["White Muscle Disease (Enzootic Nutritional Muscular Dystrophy)", "Rickets", "Night blindness", "Goiter"],
         0, "Vitamin E acts as a chain-breaking lipid peroxyl radical scavenger and Selenium is a cofactor for glutathione peroxidase; deficiency permits unchecked free radical damage to myocytes."),
        ("Vitamin K is an essential cofactor for the post-translational gamma-carboxylation of glutamic acid residues in coagulation factors:",
         ["Factors II (Prothrombin), VII, IX, and X", "Factors I, V, VIII, and XI", "Factors III and IV", "Factors XII and XIII"],
         0, "Vitamin K epoxide reductase facilitates gamma-carboxylation of Factors II, VII, IX, and X and Proteins C and S, enabling them to bind calcium and phospholipids."),
        ("Anticoagulant rodenticide poisoning (e.g. Brodifacoum, Warfarin) fatally inhibits which enzyme in the vitamin K cycle?",
         ["Vitamin K epoxide reductase (VKOR)", "Thrombin", "Factor Xa", "Tissue factor"],
         0, "Rodenticides competitively block VKOR, preventing regeneration of reduced hydroquinone vitamin K and causing life-threatening bleeding diathesis after Factor VII depletion."),
        ("The active hormonal form of Vitamin D synthesized by renal 1-alpha-hydroxylase is:",
         ["1,25-dihydroxycholecalciferol (Calcitriol)", "25-hydroxycholecalciferol (Calcidiol)", "Cholecalciferol", "Ergosterol"],
         0, "Calcitriol (1,25-(OH)2-D3) binds to nuclear VDR receptors in enterocytes, upregulating calbindin-D to maximize calcium and phosphorus absorption from the gut."),
        ("Thiamine (Vitamin B1) deficiency in cattle and sheep (often associated with high grain diets or amprolium) produces:",
         ["Polioencephalomalacia (PEM / Cerebrocortical necrosis)", "Enzootic ataxia", "White muscle disease", "Rickets"],
         0, "Thiamine deficiency impairs transketolase and pyruvate dehydrogenase in the brain, causing cerebral cortical laminar necrosis that autofluoresces under Wood's lamp."),
        ("Copper deficiency in young lambs is clinically known as:",
         ["Swayback / Enzootic Ataxia", "Grass tetany", "Goiter", "Big head disease"],
         0, "Copper is a cofactor for cytochrome c oxidase; low copper in pregnant ewes causes demyelination of spinal cord white matter in lambs, resulting in spastic paraparesis (swayback)."),
        ("Molybdenum and sulfate in forage interfere with copper absorption in cattle by forming insoluble:",
         ["Thiomolybdates", "Copper carbonate", "Copper oxide", "Copper oxalate"],
         0, "In the rumen, dietary sulfur and molybdenum combine to form thiomolybdates, which bind copper irreversibly, precipitating secondary (conditioned) hypocuprosis."),
        ("Zinc deficiency in pigs fed high-calcium rations produces which characteristic hyperkeratotic skin disorder?",
         ["Parakeratosis", "Alopecia areata", "Pemphigus foliaceus", "Ichthyosis"],
         0, "Porcine parakeratosis is characterized by crusty, proliferative skin lesions over the limbs and snout caused by dietary zinc deficiency or excess dietary calcium competing with zinc absorption."),
        ("Vitamin A (retinol) is essential for vision because 11-cis-retinal combines with opsin in rod cells to form:",
         ["Rhodopsin", "Melanin", "Hemoglobin", "Carotene"],
         0, "11-cis-retinal complexes with the apoprotein opsin to form rhodopsin in rod photoreceptors; light isomerizes retinal to all-trans-retinal, initiating the phototransduction cascade.")
    ]

    for idx, item in enumerate(raw_vbc[:120]):
        questions.append({
            "id": f"vbc_q_{idx+1:03d}",
            "domain": "veterinary_science",
            "year": "1st_year",
            "subjectId": "vbc",
            "topic": "Biochemistry & Metabolism",
            "questionText": item[0],
            "options": item[1],
            "correctOptionIndex": item[2],
            "explanation": item[3],
            "difficulty": "Medium",
            "tags": ["Biochemistry", "VBC"],
            "createdAt": 1773000000000 + idx
        })
    return questions

if __name__ == "__main__":
    qs = get_vbc_questions()
    print(f"Loaded {len(qs)} Veterinary Biochemistry questions.")
