# scripts/data_van.py
# 120 High-Yield Questions for Veterinary Anatomy (VAN)

def get_van_questions():
    questions = []
    
    # 1-30: Osteology & Arthrology
    raw_osteology = [
        ("Which of the following bones in the bovine skeleton possesses the extensor fossa (fossa extensoria)?",
         ["Distal lateral condyle of femur", "Proximal cranial border of tibia", "Distal extremity of humerus", "Proximal extremity of radius"],
         0, "The extensor fossa (fossa extensoria) is located on the lateral condyle of the femur in cattle, providing origin to the peroneus tertius and long digital extensor muscles."),
        ("The total number of cervical vertebrae in the domestic fowl (Gallus domesticus) is typically:",
         ["7", "12", "14", "18"],
         2, "Unlike mammals which consistently possess 7 cervical vertebrae, the domestic fowl possesses 14 cervical vertebrae, conferring extreme mobility to the neck."),
        ("The 'musculospiral groove' (sulcus spiralis) is a characteristic anatomical feature of which bone?",
         ["Femur", "Humerus", "Tibia", "Radius"],
         1, "The musculospiral groove winds around the lateral surface of the shaft of the humerus, housing the brachialis muscle and the radial nerve."),
        ("The 'facial tuberosity' (tuber faciale) is a landmark on the skull of which species?",
         ["Horse", "Ox", "Dog", "Pig"],
         1, "In the ox, a distinct facial tuberosity is present above the 3rd or 4th upper cheek tooth, whereas horses have a longitudinal facial crest."),
        ("How many carpal bones are present in the adult horse (Equus caballus)?",
         ["6", "7 or 8", "5", "4"],
         1, "The carpus of the horse usually has 7 or 8 bones arranged in two rows. The first carpal bone is small, inconsistent, and often missing."),
        ("In the bovine carpus, which two bones of the distal row are fused together?",
         ["Carpal 1 and 2", "Carpal 2 and 3", "Carpal 3 and 4", "Carpal 4 and ulnar carpal"],
         1, "In the ox, the second and third carpal bones fuse into a single bone (os carpi intermedium-radiale / fused C2+C3), leaving only 6 carpal bones."),
        ("The 'os cordis' is a splanchnic bone found in the heart of:",
         ["Horse", "Ox", "Dog", "Pig"],
         1, "The os cordis consists of two small bones situated in the fibrous base (annulus fibrosus) of the bovine heart, adjacent to the aortic orifice."),
        ("The 'os rostri' (splanchnic bone of the snout) is characteristic of which domestic species?",
         ["Dog", "Pig", "Ox", "Sheep"],
         1, "The os rostri (os rostrale) is located in the snout of the pig (Sus scrofa), providing rigidity for rooting behavior."),
        ("In which domestic species is the acromion process of the scapula completely absent?",
         ["Ox", "Horse", "Dog", "Cat"],
         1, "In the horse, the spine of the scapula subsides gradually distally without forming an acromion process."),
        ("The 'fovea capitis femoris' is deeply notched medially in which species to accommodate the accessory ligament?",
         ["Dog", "Horse", "Ox", "Sheep"],
         1, "In the horse, the fovea capitis femoris is deeply notched medially to accommodate both the round ligament (ligamentum teres) and the accessory ligament from the prepubic tendon."),
        ("The 'dens' or odontoid process is a modified vertebral feature of which bone?",
         ["Atlas", "Axis", "7th cervical vertebra", "Sacrum"],
         1, "The dens (processus odontoideus) projects cranially from the body of the 2nd cervical vertebra (Axis), articulating with the caudal fovea of the atlas."),
        ("The ligamentum nuchae in the dog consists solely of:",
         ["Lamellar part", "Funicular part", "Both lamellar and funicular parts", "Neither (absent)"],
         1, "In the dog, the ligamentum nuchae consists only of a funicular part extending from the spine of the axis to the spine of the first thoracic vertebra."),
        ("The ligamentum nuchae is completely absent in which domestic species?",
         ["Pig and Cat", "Dog and Sheep", "Horse and Ox", "Goat and Camel"],
         0, "The ligamentum nuchae is completely absent in the pig (Sus scrofa) and the domestic cat (Felis catus)."),
        ("The 'supratrochlear foramen' in the distal humerus is consistently present in which animal?",
         ["Dog", "Horse", "Ox", "Cat"],
         0, "The dog possesses a supratrochlear foramen in the humerus through which no major nerve or vessel passes."),
        ("The 'supracondylar foramen' in the humerus which transmits the median nerve and brachial artery is present in:",
         ["Cat", "Dog", "Ox", "Sheep"],
         0, "The domestic cat has a supracondylar foramen on the medial aspect of the distal humerus."),
        ("The 'internal acoustic meatus' is located in which part of the temporal bone?",
         ["Squamous part", "Petrous part", "Tympanic part", "Mastoid part"],
         1, "The internal acoustic meatus is located on the medial surface of the petrous temporal bone, transmitting cranial nerves VII and VIII."),
        ("The 'pterygoid process' is an anatomical feature of which cranial bone?",
         ["Sphenoid bone", "Occipital bone", "Frontal bone", "Nasal bone"],
         0, "The pterygoid process projects ventrally from the sphenoid bone forming part of the nasopharynx."),
        ("Which joint in the canine stifle is stabilized by the fabellae (sesamoid bones of gastrocnemius)?",
         ["Femoropatellar joint", "Femorotibial joint", "Tibiofibular joint", "Tarsocrural joint"],
         1, "The two lateral and medial fabellae embed in the tendons of origin of the gastrocnemius muscle over the femoral condyles at the femorotibial articulation in the dog."),
        ("The 'sternal puncture' in cattle for bone marrow biopsy is ideally performed at which sternebra?",
         ["First (Manubrium)", "Second or Third", "Fifth", "Xiphoid"],
         1, "The second or third sternebra is the standard site for bovine bone marrow aspiration due to thick cancellous bone and safety."),
        ("The 'cranial cruciate ligament' in the canine stifle prevents:",
         ["Cranial translation of tibia relative to femur", "Caudal translation of tibia relative to femur", "Internal rotation of patella", "Hyperextension of hip"],
         0, "The cranial cruciate ligament (CrCL) resists cranial tibial displacement, stifle hyperextension, and excessive internal tibial rotation."),
        ("The 'peroneus tertius' muscle in the horse is entirely:",
         ["Tendinous", "Fleshy", "Absent", "Cartilaginous"],
         0, "In the horse, the peroneus tertius is completely tendinous and acts as an essential mechanical part of the reciprocal apparatus of the hindlimb."),
        ("Which bone in the avian skeleton is termed the 'wishbone' (furcula)?",
         ["Fused clavicles", "Coracoid and scapula", "Fused ilium and ischium", "Radius and ulna"],
         0, "The furcula is formed by the ventral union of the right and left clavicles, functioning as a spring during wing beating."),
        ("The 'notarium' in the avian vertebral column represents the fusion of:",
         ["Thoracic vertebrae (T2 to T5)", "Lumbar vertebrae", "Cervical vertebrae", "Caudal vertebrae"],
         0, "The notarium (dorsal bone) is formed by the fusion of the 2nd to 5th thoracic vertebrae in birds, providing rigidity for flight."),
        ("The 'synsacrum' in birds is formed by the fusion of the last thoracic, all lumbar, all sacral, and first few:",
         ["Caudal vertebrae", "Cervical vertebrae", "Skull bones", "Ribs"],
         0, "The synsacrum is an extensive fusion of the last thoracic, all lumbar and sacral, and first few caudal vertebrae with the pelvic bones."),
        ("The 'pygostyle' in birds represents the fusion of the:",
         ["Terminal 4 to 6 caudal vertebrae", "Cervical vertebrae", "Clavicles", "Tarsal bones"],
         0, "The pygostyle is formed by the fusion of the terminal caudal vertebrae, supporting the tail feathers (rectrices)."),
        ("The dental formula of the adult bovine is:",
         ["2(I 0/4, C 0/0, PM 3/3, M 3/3) = 32", "2(I 3/3, C 1/1, PM 4/4, M 3/3) = 44", "2(I 3/3, C 1/1, PM 4/4, M 2/3) = 42", "2(I 3/3, C 1/1, PM 3/2, M 1/1) = 30"],
         0, "Cattle have no upper incisors or canines (dental pad instead); they have 8 lower incisors/canines (I 0/4, C 0/0, PM 3/3, M 3/3) = 32 teeth."),
        ("The dental formula of the adult dog (Canis familiaris) is:",
         ["2(I 3/3, C 1/1, PM 4/4, M 2/3) = 42", "2(I 3/3, C 1/1, PM 3/3, M 3/3) = 40", "2(I 0/4, C 0/0, PM 3/3, M 3/3) = 32", "2(I 3/3, C 1/1, PM 4/4, M 3/3) = 44"],
         0, "The adult dog possesses 42 permanent teeth: 2(I 3/3, C 1/1, PM 4/4, M 2/3) = 42."),
        ("The dental formula of the adult horse is:",
         ["2(I 3/3, C 1/1, PM 3-4/3, M 3/3) = 40-42", "2(I 3/3, C 1/1, PM 4/4, M 2/3) = 42", "2(I 0/4, C 0/0, PM 3/3, M 3/3) = 32", "2(I 3/3, C 1/1, PM 4/4, M 3/3) = 44"],
         0, "The adult male horse possesses 40-42 teeth (the first premolar or wolf tooth may be present in the upper jaw)."),
        ("The 'carnassial teeth' (shearing sectorial teeth) in the dog are:",
         ["Upper PM4 and Lower M1", "Upper M1 and Lower PM4", "Upper C1 and Lower C1", "Upper PM3 and Lower M2"],
         0, "The carnassial teeth specialized for shearing flesh in carnivores are the 4th upper premolar (PM4) and the 1st lower molar (M1)."),
        ("The 'wolf tooth' in the horse is an anatomical term for the:",
         ["Vestigial first upper premolar (PM1)", "Canine tooth in stallion", "First lower incisor", "Third lower molar"],
         0, "The wolf tooth is the small, vestigial first premolar (PM1) usually found in the upper jaw of the horse.")
    ]

    for q, opts, ans, exp in raw_osteology:
        questions.append({
            "topic": "Osteology & Arthrology",
            "q": q, "opts": opts, "ans": ans, "exp": exp, "diff": "Medium", "tags": ["Osteology", "Bones"]
        })

    # 31-60: Myology, Angiology & Neurology
    raw_soft = [
        ("The 'Achilles tendon' (common calcanean tendon) is primarily formed by which two major muscles?",
         ["Gastrocnemius and superficial digital flexor", "Biceps femoris and semimembranosus", "Gracilis and pectineus", "Tibialis cranialis and peroneus longus"],
         0, "The common calcanean tendon is formed principally by the gastrocnemius and superficial digital flexor tendons, reinforced by biceps femoris and semitendinosus."),
        ("The 'stay apparatus' in the equine forelimb relies on which tendinous band running through the biceps brachii?",
         ["Lacertus fibrosus", "Check ligament", "Sartorius", "Subscapularis"],
         0, "The lacertus fibrosus is a strong tendinous band that continues from the internal tendon of the biceps brachii to blend with the extensor carpi radialis."),
        ("The 'jugular groove' (sulcus jugularis) in the horse is bounded ventrally by which muscle?",
         ["Brachiocephalicus", "Sternocephalicus", "Sternothyrohyoideus", "Omohyoideus"],
         1, "In the horse, the jugular groove is bounded dorsally by the brachiocephalicus and ventrally by the sternocephalicus muscle."),
        ("In the ox, the subscapular artery gives rise to which major branch supplying the triceps and shoulder joint?",
         ["Thoracodorsal artery", "Caudal circumflex humeral artery", "Suprascapular artery", "Brachial artery"],
         1, "The caudal circumflex humeral artery arises from the subscapular artery and winds around the neck of the humerus to supply the triceps and deltoideus."),
        ("The 'cisterna chyli' in the lymphatic system is located ventral to which vertebrae?",
         ["L1 - L4", "T10 - T12", "S1 - S3", "C5 - C7"],
         0, "The cisterna chyli is a dilated lymphatic sac located dorsal to the aorta between the crura of the diaphragm and L1-L4 lumbar vertebrae."),
        ("The celiac artery in ruminants supplies which of the following viscera?",
         ["Rumen, reticulum, omasum, abomasum, liver, spleen", "Jejunum and ileum", "Descending colon and rectum", "Kidneys and adrenal glands"],
         0, "The celiac trunk supplies the foregut derivatives including all four stomach compartments, liver, spleen, and cranial duodenum."),
        ("Which vein is routinely used for intravenous venipuncture and injection in the domestic pig?",
         ["Cephalic vein", "Anterior vena cava (Cranial vena cava)", "Saphenous vein", "Femoral vein"],
         1, "The cranial vena cava entered at the right side of the thoracic inlet is the standard site for blood collection in pigs due to deep cervical jugulars."),
        ("The spur vein (lateral thoracic vein) is clinically significant in which animal during endurance and race training?",
         ["Ox", "Horse", "Dog", "Pig"],
         1, "The lateral thoracic vein (spur vein) runs along the ventrolateral abdominal wall in horses and becomes prominent during physical exertion."),
        ("Which cranial nerve passes through the cribriform plate of the ethmoid bone?",
         ["CN I (Olfactory)", "CN II (Optic)", "CN III (Oculomotor)", "CN V (Trigeminal)"],
         0, "Cranial nerve I (Olfactory nerve bundles) traverses the cribriform plate of the ethmoid to synapse in the olfactory bulb."),
        ("The diaphragm is innervated motorically by which nerve?",
         ["Phrenic nerve (C5-C7)", "Vagus nerve", "Intercostal nerves", "Sympathetic trunk"],
         0, "The phrenic nerve arising from ventral branches of cervical nerves (C5, C6, C7 in mammals) is the sole motor nerve to the diaphragm."),
        ("The 'circle of Willis' (cerebral arterial circle) surrounds which neuroendocrine structure at the brain base?",
         ["Pituitary gland (Hypophysis cerebri)", "Pineal body", "Cerebellum", "Olfactory bulb"],
         0, "The cerebral arterial circle of Willis lies in the interpeduncular fossa surrounding the optic chiasm and pituitary stalk."),
        ("The portal vein is formed primarily by the union of which two major veins?",
         ["Cranial mesenteric vein and Splenic vein", "Renal vein and Iliac vein", "Jugular vein and Cephalic vein", "Azygos vein and Vena cava"],
         0, "The hepatic portal vein is formed by the convergence of the cranial mesenteric, caudal mesenteric, and splenic (gastrosplenic) veins."),
        ("The 'brachial plexus' in the dog is typically formed by the ventral branches of:",
         ["C6, C7, C8, T1, T2", "C1, C2, C3, C4", "L1, L2, L3, L4", "T5, T6, T7, T8"],
         0, "The canine brachial plexus is formed by the ventral rami of the sixth, seventh, and eighth cervical and first and second thoracic spinal nerves."),
        ("Damage to the radial nerve proximal to the triceps innervation results in:",
         ["Dropped elbow, inability to bear weight, knuckling of digits", "Hyperflexion of hock", "Splay leg posture", "Paralysis of tongue"],
         0, "High radial nerve paralysis abolishes triceps function, causing a dropped elbow and inability to extend the carpus and digits."),
        ("Which cranial nerve provides parasympathetic innervation to the thoracic and abdominal viscera up to the transverse colon?",
         ["CN X (Vagus nerve)", "CN IX (Glossopharyngeal)", "CN VII (Facial)", "CN III (Oculomotor)"],
         0, "The vagus nerve (CN X) provides extensive parasympathetic preganglionic fibers to thoracic viscera and digestive organs up to the splenic flexure."),
        ("Paralysis of the suprascapular nerve in the horse produces muscle atrophy termed:",
         ["Sweeney (shoulder slip)", "Roaring", "Stringhalt", "Shivering"],
         0, "Sweeney is atrophy of the supraspinatus and infraspinatus muscles caused by trauma to the unprotected suprascapular nerve as it crosses the cranial border of the scapula."),
        ("Which cranial nerve emerges from the dorsal aspect of the brainstem?",
         ["CN IV (Trochlear nerve)", "CN III (Oculomotor)", "CN VI (Abducent)", "CN V (Trigeminal)"],
         0, "The trochlear nerve (CN IV) is unique among all cranial nerves in emerging from the dorsal aspect of the midbrain and completely decussating."),
        ("The 'recurrent laryngeal nerve' is a branch of which cranial nerve?",
         ["Vagus nerve (CN X)", "Accessory nerve (CN XI)", "Hypoglossal nerve (CN XII)", "Glossopharyngeal nerve (CN IX)"],
         0, "The recurrent laryngeal nerve branches from the vagus nerve (CN X); the left loops around the aortic arch and the right around the right subclavian artery."),
        ("The 'cauda equina' consists of the cone-shaped end of the spinal cord (conus medullaris) and the roots of:",
         ["Lumbar, sacral, and caudal nerves", "Cervical nerves", "Thoracic nerves", "Cranial nerves"],
         0, "The cauda equina is the horse-tail-like cluster of lumbar, sacral, and caudal spinal nerve roots streaming caudally within the vertebral canal."),
        ("The 'ansa cervicalis' is a neural loop in the neck formed by connections between:",
         ["C1/C2 and the hypoglossal nerve (CN XII)", "Vagus and glossopharyngeal", "Phrenic and accessory", "Facial and trigeminal"],
         0, "The ansa cervicalis is a loop formed by ventral branches of the first cervical nerves communicating with the hypoglossal nerve to innervate strap muscles of the larynx."),
        ("The external jugular vein in the horse is formed at the angle of the jaw by the confluence of the:",
         ["Maxillary vein and linguofacial vein", "Cephalic vein and brachial vein", "Internal jugular and subclavian", "Facial and lingual veins"],
         0, "The external jugular vein is formed behind the ramus of the mandible by the union of the maxillary vein and the linguofacial vein."),
        ("The 'saphenous artery' in the dog is a direct branch of the:",
         ["Femoral artery", "External iliac artery", "Popliteal artery", "Cranial tibial artery"],
         0, "The saphenous artery arises from the femoral artery in the femoral triangle and divides into cranial and caudal branches over the medial stifle."),
        ("Which heart chamber forms the anatomical apex of the mammalian heart?",
         ["Left ventricle", "Right ventricle", "Left atrium", "Right atrium"],
         0, "The apex of the mammalian heart is formed entirely by the thick-walled left ventricle."),
        ("The 'moderator band' (trabecula septomarginalis) is most prominent in which chamber of the ruminant heart?",
         ["Right ventricle", "Left ventricle", "Right atrium", "Left atrium"],
         0, "The trabecula septomarginalis (moderator band) carries conduction Purkinje fibers across the lumen from the interventricular septum to the parietal wall of the right ventricle."),
        ("The 'ductus arteriosus' in the fetus connects the pulmonary trunk directly with the:",
         ["Aortic arch / descending aorta", "Right atrium", "Caudal vena cava", "Left pulmonary vein"],
         0, "The ductus arteriosus shunts the majority of right ventricular blood away from non-inflated fetal lungs directly into the descending aorta."),
        ("The 'foramen ovale' in the fetal heart is situated in the:",
         ["Interatrial septum", "Interventricular septum", "Atrioventricular junction", "Sinus venosus"],
         0, "The foramen ovale is an opening in the fetal interatrial septum that allows oxygenated blood from the caudal vena cava to flow into the left atrium."),
        ("The 'rete mirabile epidurale' is an intracranial arterial heat-exchanger network present in:",
         ["Ox, sheep, and pig", "Horse and dog", "Cat and rabbit", "Birds only"],
         0, "Ruminants and pigs possess an intracranial epidural rete mirabile formed by branches of the maxillary and vertebral arteries to cool arterial blood entering the brain."),
        ("The 'internal carotid artery' in the adult ox is:",
         ["Functionally absent (regressed) extracranially", "The sole blood supply to the brain", "Twice the size of the maxillary artery", "A branch of the vertebral artery"],
         0, "In the adult ox, the extracranial portion of the internal carotid artery regresses into a fibrous cord; the brain is supplied via the maxillary artery and rete mirabile."),
        ("The 'cremaster muscle' is an anatomical detachment of which abdominal wall muscle?",
         ["Internal abdominal oblique", "External abdominal oblique", "Transversus abdominis", "Rectus abdominis"],
         0, "The cremaster muscle is derived from the caudal free border of the internal abdominal oblique muscle, passing through the inguinal canal to suspend the testicle."),
        ("The 'linea alba' is a fibrous median raphe formed by the aponeuroses of the abdominal muscles extending from the xiphoid cartilage to the:",
         ["Prepubic tendon", "Ilial wing", "Patella", "Tuber coxae"],
         0, "The linea alba is a central, avascular fibrous cord formed by the intercrossing aponeuroses of abdominal muscles extending from the xiphoid to the prepubic tendon.")
    ]

    for q, opts, ans, exp in raw_soft:
        questions.append({
            "topic": "Myology & Angiology",
            "q": q, "opts": opts, "ans": ans, "exp": exp, "diff": "Medium", "tags": ["Myology", "Angiology"]
        })

    # 61-90: Splanchnology (Digestive, Respiratory, Urogenital)
    raw_splanchnology = [
        ("The 'torus linguae' is a prominent anatomical elevation on the caudal third of the tongue in:",
         ["Ox", "Horse", "Dog", "Pig"],
         0, "The torus linguae is a distinct, rounded dorsal swelling on the caudal tongue of ruminants (ox, sheep, goat) separated from the body by the lingual fossa."),
        ("Which papillae on the bovine tongue are exclusively mechanical in function without taste buds?",
         ["Filiform and conical papillae", "Fungiform papillae", "Vallate papillae", "Foliate papillae"],
         0, "Filiform and conical papillae are heavily cornified mechanical papillae that facilitate ingestion and mastication; they lack taste buds."),
        ("The 'honeycomb' internal mucosal pattern is characteristic of which stomach compartment?",
         ["Rumen", "Reticulum", "Omasum", "Abomasum"],
         1, "The reticulum has its mucosal lining raised into permanent intersecting folds dividing the surface into polygonal cells resembling a honeycomb."),
        ("The 'spiral colon' (ansa spiralis coli) is an anatomical landmark in the digestive tract of:",
         ["Ruminants and pigs", "Horse and dog", "Cat and rabbit", "Chicken and duck"],
         0, "The ansa spiralis coli with centripetal and centrifugal coils is a hallmark feature of the ascending colon in ruminants and pigs."),
        ("In which species is the cecum shaped like a large comma with four longitudinal muscular bands (taeniae)?",
         ["Ox", "Horse", "Dog", "Sheep"],
         1, "The equine cecum has a capacity of ~30 liters, shaped like an inverted comma with 4 distinct taeniae coli and rows of sacculations (haustra)."),
        ("The right kidney of the horse has a distinctive shape described as:",
         ["Bean-shaped", "Lobulated", "Heart-shaped", "Elongated oval"],
         2, "The equine right kidney is distinctly heart-shaped (or playing-card spade), whereas the left kidney is bean-shaped."),
        ("The bovine kidney is characterized by:",
         ["Smooth unipapillary structure", "Multilobulated external surface (15-25 lobes)", "Presence of renal pelvis", "Single common papilla"],
         1, "The bovine kidney is unique among domestic farm animals in being externally divided into 15 to 25 distinct lobules and lacking a renal pelvis (calyces instead)."),
        ("The 'sigmoid flexure' of the penis is located post-scrotal in which animal?",
         ["Boar", "Bull", "Dog", "Stallion"],
         1, "In the bull, the sigmoid flexure is located caudal to the scrotum (post-scrotal), whereas in the boar it is pre-scrotal."),
        ("The penis of the dog contains which specific bone?",
         ["Os cordis", "Os penis (baculum)", "Os rostri", "Os phrenic"],
         1, "The os penis (baculum) is a splanchnic bone situated inside the canine penis, grooved ventrally for the urethra."),
        ("The 'bursa Fabricii' (cloacal bursa) in birds is a primary lymphoid organ located dorsal to the:",
         ["Proventriculus", "Proctodeum", "Ceca", "Uropygial gland"],
         1, "The bursa of Fabricius is located in the dorsal wall of the proctodeum in the avian cloaca, functioning as the primary site of B-cell lymphopoiesis."),
        ("The respiratory organ of birds lacks a muscular diaphragm and contains how many principal air sacs?",
         ["5", "7", "9", "12"],
         2, "The domestic fowl typically possesses 9 air sacs (1 cervical, 1 interclavicular, 2 cranial thoracic, 2 caudal thoracic, 2 abdominal)."),
        ("The glandular, enzymatic stomach of the domestic fowl is the:",
         ["Proventriculus", "Ventriculus (Gizzard)", "Crop (Ingluvies)", "Cloaca"],
         0, "The proventriculus is the glandular stomach secreting pepsin and HCl, whereas the muscular gizzard (ventriculus) grinds feed with grit."),
        ("In which species is the gallbladder completely absent?",
         ["Horse, Pigeon, and Rat", "Ox, Sheep, and Goat", "Dog, Cat, and Pig", "Chicken, Duck, and Goose"],
         0, "The horse, pigeon, and rat lack a gallbladder; bile flows continuously through the hepatic duct into the duodenum."),
        ("The 'parotid salivary duct' (Stensen's duct) opens in the mouth opposite to which upper cheek tooth in the horse?",
         ["Upper 3rd cheek tooth (PM4)", "Upper 1st cheek tooth (PM2)", "Upper 1st incisor", "Upper canine"],
         0, "In the horse, the parotid duct opens on the parotid papilla opposite the 3rd upper cheek tooth (fourth premolar)."),
        ("The 'epiploic foramen' (foramen of Winslow) is an opening leading into the:",
         ["Omental bursa (lesser peritoneal sac)", "Pelvic cavity", "Pleural space", "Pericardial cavity"],
         0, "The epiploic foramen connects the greater peritoneal cavity with the omental bursa (omental sac), bounded by the caudal vena cava and portal vein."),
        ("The functional respiratory unit of the avian lung where gas exchange occurs is the:",
         ["Air capillaries and parabronchi", "Alveoli and alveolar sacs", "Tracheoles", "Bronchioles"],
         0, "Avian lungs do not possess alveoli; instead, gas exchange occurs across microscopic air capillaries radiating from parabronchi."),
        ("The domestic fowl possesses how many ceca at the ileocecocolic junction?",
         ["Two (paired ceca)", "Single cecum", "Three ceca", "No cecum"],
         0, "Birds possess paired elongated ceca that open at the junction between the small intestine and colon."),
        ("The 'syrinx' (voice box) of birds is located at the:",
         ["Bifurcation of the trachea into primary bronchi", "Rostral end of larynx", "Within the lung parenchyma", "Base of tongue"],
         0, "The syrinx is the avian vocal organ situated at the caudal end of the trachea where it bifurcates into the left and right primary bronchi."),
        ("Which ovary and oviduct are fully functional in the adult domestic hen?",
         ["Left ovary and Left oviduct", "Right ovary and Right oviduct", "Both left and right equally", "Neither (hermaphrodite)"],
         0, "In nearly all avian species, only the left ovary and left oviduct develop into functional adult reproductive organs; the right ones regress."),
        ("The 'uropygial gland' (preen gland) is located on the dorsal aspect of the:",
         ["Uropygium (tail base)", "Wing tip", "Sternum", "Comb"],
         0, "The uropygial gland is a bilobed sebaceous gland located dorsally on the tail (uropygium) used for feather waterproofing and preening."),
        ("The 'tracheal bronchus' (bronchus bronchialis) supplying the right cranial lung lobe is present in:",
         ["Ruminants and pigs", "Horse and dog", "Cat and rabbit", "Birds"],
         0, "In ruminants and pigs, a specialized tracheal bronchus arises directly from the lateral wall of the trachea cranial to its bifurcation to ventilate the right cranial lobe."),
        ("The 'guttural pouches' (diverticula of the auditory tube) are anatomical features of:",
         ["Equidae (horses, donkeys)", "Bovidae (cattle)", "Suidae (pigs)", "Canidae (dogs)"],
         0, "Guttural pouches are large bilateral air-filled mucosal sacs arising from the auditory (Eustachian) tubes in solipeds, holding ~300 to 500 ml of air."),
        ("The 'bulbus glandis' which expands during the copulatory tie is present in the penis of the:",
         ["Dog", "Bull", "Stallion", "Boar"],
         0, "The bulbus glandis is an expansile vascular structure of the canine corpus spongiosum that swells dramatically during copulation to lock the animals together."),
        ("The cervix of the cow is characterized by which internal mucosal feature?",
         ["3 to 4 circular/transverse mucosal rings (annular folds)", "Smooth longitudinal folds", "Interdigitating mucosal pads (pulvini cervicales)", "Complete absence of folds"],
         0, "The bovine cervix possesses 3 to 4 prominent transverse circular ridges or annular rings that interlock, forming a tight physical barrier."),
        ("The cervix of the sow possesses interdigitating mucosal pads termed:",
         ["Pulvini cervicales", "Caruncles", "Cotyledons", "Annular rings"],
         0, "In the sow, the cervical canal is characterized by interdigitating rounded prominences termed pulvini cervicales resembling the threads of a screw."),
        ("The 'renal crest' (crista renalis) is a common renal papilla found in:",
         ["Dog, cat, horse, and sheep", "Ox and pig", "Birds and reptiles", "Camel only"],
         0, "In carnivores, small ruminants, and horses, the renal pyramids fuse into a single continuous longitudinal ridge termed the renal crest projecting into the renal pelvis."),
        ("The 'infundibulum' of the avian oviduct is the site of:",
         ["Fertilization and initial chalaziferous layer deposition", "Egg shell deposition", "Albumin secretion", "Pigment deposition"],
         0, "The infundibulum (funnel) captures the ovulated ovum and is the exclusive site where fertilization occurs within 15-30 minutes after ovulation."),
        ("The shell gland (uterus) of the avian oviduct retains the developing egg for approximately:",
         ["18 to 20 hours", "2 to 3 hours", "1 hour", "36 hours"],
         0, "The egg spends the longest time (~18-20 hours out of the total 25-26 hour egg-laying cycle) in the shell gland/uterus receiving the hard calcite shell and pigments."),
        ("The 'suburethral diverticulum' is a blind mucosal pouch located ventral to the external urethral orifice in the:",
         ["Cow and Sow", "Mare and Bitch", "Ewe and Queen", "Hen"],
         0, "The suburethral diverticulum is a clinically significant blind pouch in cows and sows that can mislead urinary catheters during catheterization."),
        ("The right lung of the ox is divided into how many lobes?",
         ["4 lobes (cranial divided into 2, middle, caudal, accessory)", "2 lobes", "3 lobes", "6 lobes"],
         0, "The bovine right lung is divided into cranial (which is further subdivided into cranial and caudal parts), middle, caudal, and accessory lobes.")
    ]

    for q, opts, ans, exp in raw_splanchnology:
        questions.append({
            "topic": "Splanchnology",
            "q": q, "opts": opts, "ans": ans, "exp": exp, "diff": "Medium", "tags": ["Splanchnology", "Viscera"]
        })

    # 91-120: Histology & Embryology
    raw_histo_embryo = [
        ("Hassall's corpuscles (thymic corpuscles) are diagnostic histological structures found in the:",
         ["Spleen red pulp", "Thymus medulla", "Lymph node cortex", "Tonsil crypt"],
         1, "Hassall's corpuscles consist of concentric whorls of eosinophilic epithelial reticular cells located specifically in the thymic medulla."),
        ("Kupffer cells are resident tissue macrophages located inside the liver sinusoids of:",
         ["All domestic mammals", "Only birds", "Only pigs", "Only carnivores"],
         0, "Kupffer cells are specialized sinusoidal macrophages of the liver belonging to the mononuclear phagocyte system."),
        ("The 'Peyer’s patches' are aggregated lymphoid follicles located prominently in the submucosa of the:",
         ["Duodenum", "Jejunum", "Ileum", "Colon"],
         2, "Peyer's patches are characteristic aggregated lymphoid nodules located primarily in the ileum of the small intestine."),
        ("Which cells of the stomach fundic glands secrete hydrochloric acid (HCl) and intrinsic factor?",
         ["Parietal (oxyntic) cells", "Chief (zymogenic) cells", "Mucous neck cells", "Enteroendocrine cells"],
         0, "Parietal or oxyntic cells possess abundant mitochondria and intracellular canaliculi that produce HCl."),
        ("Chief cells (peptic cells) of the gastric mucosa are primarily responsible for synthesizing:",
         ["Pepsinogen", "Hydrochloric acid", "Mucin", "Gastrin"],
         0, "Chief (zymogenic) cells contain basophilic rough endoplasmic reticulum and secrete the proenzyme pepsinogen."),
        ("Podocytes with primary and secondary foot processes (pedicels) form which barrier in the kidney?",
         ["Filtration barrier of glomerulus", "Countercurrent exchanger", "Juxtaglomerular apparatus", "Collecting duct wall"],
         0, "Podocytes constitute the visceral layer of Bowman's capsule and their interdigitating pedicels form the glomerular filtration slits."),
        ("Juxtaglomerular cells in the afferent arteriole of the nephron secrete which proteolytic enzyme?",
         ["Angiotensin", "Renin", "Aldosterone", "Erythropoietin"],
         1, "Juxtaglomerular (JG) cells are modified vascular smooth muscle cells that synthesize, store, and release renin in response to low renal perfusion."),
        ("The 'white pulp' of the spleen histologically consists of:",
         ["Venous sinusoids and Billroth cords", "Periarteriolar lymphoid sheaths (PALS) and splenic nodules", "Red blood cell reservoirs", "Trabeculae exclusively"],
         1, "The splenic white pulp is composed of T-lymphocytes organized into PALS surrounding central arterioles and B-cell follicular nodules."),
        ("The placenta of the mare and sow is classified morphologically as:",
         ["Diffuse", "Cotyledonary", "Zonary", "Discoid"],
         0, "The mare and sow possess a diffuse placenta where chorionic villi are distributed uniformly over the entire chorionic sac."),
        ("The placenta of ruminants (cow, ewe, doe) is classified morphologically as:",
         ["Diffuse", "Cotyledonary", "Zonary", "Discoid"],
         1, "Ruminants possess a cotyledonary placenta characterized by discrete patches of chorionic villi (cotyledons) that attach to maternal caruncles (forming placentomes)."),
        ("The placenta of the bitch and queen is classified morphologically as:",
         ["Diffuse", "Cotyledonary", "Zonary", "Discoid"],
         2, "Carnivores (dog and cat) possess a zonary placenta where chorionic villi form a complete or incomplete girdle around the middle of the chorionic sac."),
        ("Histologically, the bovine placenta is classified as:",
         ["Epitheliochorial (or Synepitheliochorial)", "Endotheliochorial", "Hemochorial", "Hemoendothelial"],
         0, "The bovine placenta is synepitheliochorial (modified epitheliochorial) with 6 tissue layers separating fetal and maternal blood streams."),
        ("The canine placenta histologically belongs to which category?",
         ["Epitheliochorial", "Endotheliochorial", "Hemochorial", "Discoid"],
         1, "The canine and feline placenta is endotheliochorial, having 4 tissue layers because maternal uterine epithelium and connective tissue erode."),
        ("The 'ductus venosus' in the mammalian fetus carries oxygenated blood from the umbilical vein directly into the:",
         ["Right atrium", "Cranial vena cava", "Caudal vena cava", "Pulmonary trunk"],
         2, "The ductus venosus bypasses the microcirculation of the fetal liver, shunting umbilical blood directly into the caudal vena cava."),
        ("The embryonic remnant of the fetal ductus arteriosus in the adult heart is the:",
         ["Fossa ovalis", "Ligamentum arteriosum", "Ligamentum venosum", "Round ligament of liver"],
         1, "The ductus arteriosus constricts post-natally into a fibrous connective tissue cord termed the ligamentum arteriosum."),
        ("The nervous system, epidermis, and hair follicles embryologically originate from which germ layer?",
         ["Ectoderm", "Mesoderm", "Endoderm", "Hypoblast"],
         0, "The surface ectoderm and neural ectoderm give rise to the central and peripheral nervous system, epidermis, and skin appendages."),
        ("Purkinje cells with extensive dendritic trees are a unique histological feature of the:",
         ["Cerebellar cortex", "Cerebral cortex", "Spinal cord dorsal horn", "Adrenal medulla"],
         0, "Purkinje cells form a single prominent layer of large flask-shaped neurons in the cerebellar cortex."),
        ("Intercalated discs with gap junctions and fascia adherens are characteristic of:",
         ["Cardiac muscle", "Skeletal muscle", "Smooth muscle", "Dense regular connective tissue"],
         0, "Intercalated discs are specialized cell junctions that mechanically and electrically couple adjacent cardiomyocytes."),
        ("The 'macula densa' is a specialized region of the:",
         ["Distal convoluted tubule", "Proximal convoluted tubule", "Loop of Henle descending limb", "Renal corpuscle parietal layer"],
         0, "The macula densa consists of specialized tall, densely packed epithelial cells in the initial distal convoluted tubule sensing sodium chloride concentration."),
        ("The thyroid gland follicles are lined by which type of epithelium under normal physiological state?",
         ["Simple cuboidal epithelium", "Simple squamous epithelium", "Stratified squamous epithelium", "Pseudostratified columnar"],
         0, "Thyroid follicles are typically lined by simple cuboidal epithelium, which becomes columnar during hyperactive states and squamous during inactivity."),
        ("The adrenal cortex zone that synthesizes mineralocorticoids (aldosterone) is the:",
         ["Zona glomerulosa (or Zona arcuata)", "Zona fasciculata", "Zona reticularis", "Adrenal medulla"],
         0, "The outermost zona glomerulosa (termed zona arcuata in horses and carnivores) produces mineralocorticoids including aldosterone."),
        ("Which cells in the testes produce testosterone under the influence of Luteinizing Hormone (LH)?",
         ["Leydig (Interstitial) cells", "Sertoli cells", "Spermatogonia", "Myoid peritubular cells"],
         0, "Leydig (interstitial) cells located in the loose connective tissue between seminiferous tubules produce testosterone."),
        ("Sertoli cells in the seminiferous tubule are crucial for forming the:",
         ["Blood-testis barrier", "Blood-brain barrier", "Tunica albuginea", "Mediastinum testis"],
         0, "Tight junctions (zonula occludentes) between adjacent Sertoli cells create the blood-testis barrier protecting haploid germ cells from immune attack."),
        ("The 'islets of Langerhans' beta cells secrete which hormone?",
         ["Insulin", "Glucagon", "Somatostatin", "Pancreatic polypeptide"],
         0, "Beta cells comprise 70% of islet cells and secrete insulin in response to elevated blood glucose concentrations."),
        ("The embryonic origin of the adrenal medulla is the:",
         ["Neural crest cells (Ectoderm)", "Mesothelium (Mesoderm)", "Endoderm", "Yolk sac"],
         0, "The adrenal medulla develops from sympathochromaffin neural crest cells (neuroectoderm), whereas the adrenal cortex arises from coelomic mesoderm."),
        ("The 'allantois' in the avian and mammalian embryo functions primarily as a:",
         ["Respiration and metabolic waste reservoir", "Yolk accumulator", "Skin precursor", "Bony framework"],
         0, "The allantoic sac stores liquid nitrogenous waste (uric acid/urea) and in birds fuses with the chorion to form the chorioallantoic respiratory membrane."),
        ("Failure of the aortic arch system to develop normally can produce 'persistent right aortic arch' (PRAA), causing:",
         ["Vascular ring entrapment of the esophagus", "Cleft palate", "Cryptorchidism", "Spina bifida"],
         0, "In PRAA, the esophagus is incarcerated within a vascular ring between the right aortic arch, pulmonary artery, and ligamentum arteriosum, causing regurgitation."),
        ("The 'pronephros' represents which stage of vertebrate kidney development?",
         ["Initial non-functional transient kidney", "The definitive functional adult kidney", "The embryonic excretory organ of birds", "The adrenal precursor"],
         0, "The pronephros is the earliest, most cranial and transient kidney stage, followed by the mesonephros and the definitive metanephros."),
        ("The 'paneth cells' located at the base of intestinal crypts (crypts of Lieberkühn) produce:",
         ["Lysozyme and defensins (antimicrobial peptides)", "Gastrin", "Hydrochloric acid", "Secretin"],
         0, "Paneth cells contain prominent apical eosinophilic granules containing lysozyme, defensins, and zinc to regulate the enteric microbial flora."),
        ("Clara cells (club cells) are specialized non-ciliated secretory cells found in the lining of:",
         ["Terminal and respiratory bronchioles", "Trachea", "Alveoli", "Nasal septum"],
         0, "Club cells (Clara cells) populate the bronchiolar epithelium, secreting surfactant-like glycosaminoglycans and metabolizing xenobiotics via cytochrome P450 enzymes.")
    ]

    for q, opts, ans, exp in raw_histo_embryo:
        questions.append({
            "topic": "Histology & Embryology",
            "q": q, "opts": opts, "ans": ans, "exp": exp, "diff": "Medium", "tags": ["Histology", "Embryology"]
        })

    # Format into standard question objects
    final_list = []
    for idx, item in enumerate(questions[:120]):
        final_list.append({
            "id": f"van_q_{idx+1:03d}",
            "domain": "veterinary_science",
            "year": "1st_year",
            "subjectId": "van",
            "topic": item["topic"],
            "questionText": item["q"],
            "options": item["opts"],
            "correctOptionIndex": item["ans"],
            "explanation": item["exp"],
            "difficulty": item.get("diff", "Medium"),
            "tags": item.get("tags", ["Anatomy", "VAN"]),
            "createdAt": 1773000000000 + idx
        })
    return final_list

if __name__ == "__main__":
    qs = get_van_questions()
    print(f"Loaded {len(qs)} Veterinary Anatomy questions.")
