# scripts/data_vmc.py
# 120 High-Yield Questions for Veterinary Microbiology (VMC)

def get_vmc_questions():
    questions = []

    raw_vmc = [
        # 1-30: General & Systematic Bacteriology
        ("The primary chemical component of the bacterial endospore cortex and core conferring resistance to extreme heat is:",
         ["Calcium dipicolinate (dipicolinic acid complexed with calcium)", "Peptidoglycan", "Teichoic acid", "Lipopolysaccharide"],
         0, "Calcium dipicolinate represents 5-15% of the dry weight of the spore, dehydrating the core and stabilizing enzymes and DNA against heat denaturation."),
        ("The 'McFadyean reaction' is a diagnostic stain used for presumptive identification of Bacillus anthracis in blood smears using:",
         ["Polychrome methylene blue (demonstrating pink/purple capsule around dark blue bacilli)", "Carbol fuchsin", "Crystal violet", "Indian ink"],
         0, "Polychrome methylene blue stains the poly-D-glutamic acid capsule of B. anthracis an amorphous pink-purple surrounding blue, square-ended truncated rods."),
        ("The thermoprecipitin test developed by Alberto Ascoli for rapid detection of anthrax antigens in decomposed hides and tissues is the:",
         ["Ascoli test (ring precipitation test)", "Complement fixation test", "Rose Bengal test", "Schick test"],
         0, "The Ascoli test is a ring precipitation reaction using heated tissue extracts layered over anti-anthrax serum to detect thermostable polysaccharide antigens."),
        ("The neurotoxin 'tetanospasmin' produced by Clostridium tetani exerts its spastic paralytic effect by:",
         ["Cleaving synaptobrevin and blocking release of inhibitory neurotransmitters (GABA and Glycine) from Renshaw cells", "Inhibiting acetylcholine release at the motor endplate", "Directly destroying muscle fibers", "Inactivating voltage-gated sodium channels"],
         0, "Tetanospasmin migrates retrograde into spinal cord inhibitory interneurons, blocking vesicular exocytosis of glycine and GABA, producing unchecked spastic tetany."),
        ("The neurotoxin of Clostridium botulinum causes flaccid paralysis by:",
         ["Cleaving SNARE proteins and blocking the exocytosis of Acetylcholine (ACh) at the neuromuscular junction", "Blocking GABA release", "Stimulating parasympathetic ganglia", "Directly depolarizing muscle cells"],
         0, "Botulinum neurotoxin (the most potent biological toxin known) targets presynaptic motor nerve terminals, preventing acetylcholine release and causing flaccid paralysis."),
        ("The 'pulpy kidney disease' (enterotoxemia) in sheep is caused by which toxin of Clostridium perfringens Type D?",
         ["Epsilon toxin", "Alpha toxin", "Beta toxin", "Iota toxin"],
         0, "Epsilon protoxin is activated by trypsin in the intestine, dramatically increasing vascular permeability in the brain and kidneys, causing rapid post-mortem autolysis of renal parenchyma."),
        ("The causative agent of 'Hemorrhagic Septicemia' (HS) in cattle and buffaloes in Asian countries is:",
         ["Pasteurella multocida serotype B:2 (Carter's B / Heddleston 2)", "Pasteurella multocida serotype E:2", "Mannheimia haemolytica A1", "Histophilus somni"],
         0, "Asian hemorrhagic septicemia is caused exclusively by Pasteurella multocida serotype B:2, while serotype E:2 is the classical African etiology."),
        ("Under microscopic examination of blood or tissue smears stained with Leishman or Giemsa, Pasteurella multocida characteristically displays:",
         ["Bipolar staining ('safety-pin' appearance)", "Drumstick spores", "Medusa-head colonies", "Chinese-letter arrangement"],
         0, "P. multocida shows prominent bipolar condensation of chromatin at both poles with a clear central band, resembling a closed safety-pin."),
        ("The 'Milk Ring Test' (MRT / ABR test) for herd screening of bovine brucellosis uses Brucella abortus antigen stained with:",
         ["Hematoxylin (producing a blue-purple cream ring with positive milk)", "Crystal violet", "Safranin", "Methylene blue"],
         0, "In Brucella-infected cows, milk antibodies agglutinate hematoxylin-stained B. abortus antigen, which attaches to rising fat globules to form a deep blue cream ring on top."),
        ("The rapid field serum agglutination test widely employed for presumptive diagnosis of Brucellosis in cattle and goats is the:",
         ["Rose Bengal Plate Test (RBPT) buffered at pH 3.65", "VDRL test", "Widal test", "Castaneda strip test"],
         0, "RBPT uses B. abortus cells stained with Rose Bengal dye buffered at acidic pH (3.65), which suppresses non-specific agglutinins and enhances IgG1 binding."),
        ("Mycobacterium bovis and Mycobacterium tuberculosis are classified as 'acid-fast' bacilli because their cell walls are exceptionally rich in:",
         ["Mycolic acids and complex glycolipids", "Peptidoglycan exclusively", "Teichoic acids", "Chitin"],
         0, "Mycolic acids form a waxy, lipid-rich hydrophobic barrier (60% of cell wall weight) that resists standard staining, holding carbol fuchsin against acid-alcohol decolorization."),
        ("The gold-standard egg-based culture medium traditionally used for primary isolation of Mycobacterium species is:",
         ["Lowenstein-Jensen (L-J) medium", "Blood agar", "MacConkey agar", "Sabouraud dextrose agar"],
         0, "L-J medium contains whole eggs, glycerol, potato starch, and malachite green (which inhibits contaminating bacteria), supporting slow mycobacterial growth."),
        ("The 'swarming phenomenon' (concentric waves of bacterial spreading over non-inhibitory agar plates) is characteristic of:",
         ["Proteus mirabilis and Proteus vulgaris", "Escherichia coli", "Salmonella enterica", "Pseudomonas aeruginosa"],
         0, "Proteus species alternate between short swimmer cells and elongated, hyperflagellated swarmer cells, creating rhythmic concentric waves across blood agar."),
        ("Pseudomonas aeruginosa is visually and diagnostically recognized on agar culture by the production of a blue-green pigment called:",
         ["Pyocyanin (and Pyoverdine)", "Prodigiosin", "Violacein", "Melanin"],
         0, "Pseudomonas aeruginosa synthesizes water-soluble pyocyanin (blue, non-fluorescent) and pyoverdine (green-yellow, fluorescent), giving colonies a characteristic green sheen and grape-like odor."),
        ("The primary diagnostic test used to differentiate pathogenic Staphylococcus aureus from non-pathogenic staphylococci is the:",
         ["Coagulase test (converting fibrinogen to fibrin clot)", "Catalase test", "Oxidase test", "Indole test"],
         0, "S. aureus produces coagulase which clots rabbit plasma; coagulase-negative staphylococci (CNS, e.g. S. epidermidis) do not clot plasma."),
        ("The enzyme that distinguishes all Staphylococci (positive) from Streptococci (negative) is:",
         ["Catalase (producing effervescence with 3% H2O2)", "Coagulase", "Oxidase", "Urease"],
         0, "Staphylococci produce catalase (2 H2O2 -> 2 H2O + O2), producing bubbling when mixed with hydrogen peroxide; Streptococci are catalase-negative."),
        ("On MacConkey agar, Escherichia coli forms distinctive bright pink colonies because it is a:",
         ["Lactose fermenter (producing acid that turns neutral red indicator pink)", "Non-lactose fermenter", "Urease producer", "Gelatin liquefier"],
         0, "E. coli ferments lactose, producing acidic end-products that precipitate bile salts and turn the neutral red pH indicator bright pink."),
        ("Salmonella colonies on MacConkey agar appear:",
         ["Colorless, pale, translucent (non-lactose fermenting)", "Bright pink", "Jet black", "Fluorescent green"],
         0, "Salmonella species cannot ferment lactose and form pale, colorless, transparent colonies on MacConkey agar."),
        ("The 'CAMP test' (named after Christie, Atkins, and Munch-Petersen) detects synergistic beta-hemolysis between Staphylococcus aureus and:",
         ["Streptococcus agalactiae (producing an arrowhead of complete hemolysis)", "Streptococcus dysgalactiae", "Streptococcus uberis", "Enterococcus faecalis"],
         0, "Streptococcus agalactiae secretes the CAMP factor (a diffusible extracellular protein) that interacts synergistically with staphylococcal beta-lysin to produce an arrowhead zone of complete lysis."),
        ("Actinomyces bovis, the causative agent of 'lumpy jaw' in cattle, produces diagnostic granules in pus known as:",
         ["Sulfur granules (yellow granules of bacterial filaments embedded in protein matrix)", "Aschoff bodies", "Cowdry bodies", "Russell bodies"],
         0, "Exudates from lumpy jaw lesions contain macroscopically visible gritty, yellowish 'sulfur granules' consisting of ray-fungus rosettes with club-shaped peripheral calcification."),
        ("The causative agent of 'wooden tongue' in cattle is the Gram-negative coccobacillus:",
         ["Actinobacillus lignieresii", "Actinomyces bovis", "Fusobacterium necrophorum", "Corynebacterium diphtheriae"],
         0, "Actinobacillus lignieresii invades lingual mucosa damaged by rough forage, causing chronic granulomatous induration of the tongue ('wooden tongue')."),

        # 31-60: Veterinary Mycology
        ("The premier fungal etiology of 'ringworm' (dermatophytosis) in domestic cattle is:",
         ["Trichophyton verrucosum", "Microsporum canis", "Trichophyton mentagrophytes", "Microsporum gypseum"],
         0, "Trichophyton verrucosum is the principal agent of bovine ringworm, producing thick, circumscribed, asbestos-like greyish-white crusts around the eyes and neck."),
        ("Which dermatophyte species is the most common cause of ringworm in dogs and cats, exhibiting apple-green fluorescence under Wood's lamp?",
         ["Microsporum canis (50-60% of strains fluoresce)", "Trichophyton verrucosum", "Microsporum nanum", "Epidermophyton floccosum"],
         0, "Microsporum canis produces pteridine metabolites in infected hair shafts that emit a diagnostic bright apple-green fluorescence under Wood's lamp (365 nm UV)."),
        ("'Brooder pneumonia' (mycotic pneumonia) in young hatchery chicks is caused by inhalation of conidia of:",
         ["Aspergillus fumigatus", "Candida albicans", "Rhizopus oryzae", "Mucor pusillus"],
         0, "Aspergillus fumigatus grows rapidly in contaminated hatchery litter; inhaled spores germinate in the warm avian respiratory tract, producing yellow mycotic granulomas."),
        ("The unique yeast that produces a massive mucopolysaccharide capsule, best visualized with negative staining using India Ink, is:",
         ["Cryptococcus neoformans", "Candida albicans", "Malassezia pachydermatis", "Histoplasma capsulatum"],
         0, "Cryptococcus neoformans possesses a thick, clear glucuronoxylomannan capsule that excludes Indian ink particles, standing out as an unstained halo around the yeast cell."),
        ("The non-filamentous, unipolar budding yeast with a characteristic 'peanut / footprint' morphology commonly causing canine otitis externa is:",
         ["Malassezia pachydermatis", "Candida albicans", "Cryptococcus neoformans", "Rhodotorula rubra"],
         0, "Malassezia pachydermatis is a normal commensal of canine ears and skin that proliferates in moist, allergic environments, appearing as peanut-shaped yeasts on cytology."),

        # 61-90: Veterinary Virology
        ("The genome of all Parvoviruses (including Canine Parvovirus - CPV-2) consists of:",
         ["Single-stranded DNA (ssDNA)", "Double-stranded DNA (dsDNA)", "Single-stranded RNA", "Double-stranded RNA"],
         0, "Parvoviridae are among the smallest viruses, possessing a linear, single-stranded non-enveloped DNA genome that replicates exclusively in dividing S-phase cells."),
        ("Poxviruses (Poxviridae) are unique among all DNA viruses because they:",
         ["Replicate exclusively in the cytoplasm of the host cell", "Replicate in the nucleus", "Lack an envelope", "Have a segmented genome"],
         0, "Poxviruses are large and complex, carrying their own DNA-dependent RNA polymerase, allowing them to replicate and assemble viral factories (Guarnieri bodies) entirely in the cytoplasm."),
        ("Foot and Mouth Disease Virus (FMDV) is an Aphthovirus belonging to which viral family?",
         ["Picornaviridae (single-stranded positive-sense RNA, non-enveloped)", "Rhabdoviridae", "Flaviviridae", "Paramyxoviridae"],
         0, "FMDV is an acid-labile Picornavirus possessing a positive-sense ssRNA genome; it has 7 immunological serotypes with no cross-protection: O, A, C, Asia 1, SAT 1, SAT 2, SAT 3."),
        ("Which FMD virus serotype is historically and currently the most prevalent in India?",
         ["Serotype O (accounting for >80-85% of outbreaks)", "Serotype A", "Serotype Asia 1", "Serotype C"],
         0, "Serotype O is the dominant strain causing field outbreaks across India, followed by Asia 1 and A. Serotype C has not been reported globally since 2004."),
        ("The causative agent of 'Ranikhet disease' (Newcastle Disease) in poultry is:",
         ["Avian Paramyxovirus Serotype 1 (APMV-1 / Avian orthoavulavirus 1)", "Infectious Bursal Disease Virus", "Avian Influenza Virus", "Poxvirus"],
         0, "Newcastle disease is caused by virulent strains of APMV-1 belonging to the family Paramyxoviridae, categorized into lentogenic, mesogenic, and velogenic pathotypes."),
        ("The causative agent of 'Infectious Bursal Disease' (Gumboro disease) in poultry belongs to the family:",
         ["Birnaviridae (double-stranded bi-segmented RNA)", "Reoviridae", "Coronaviridae", "Picornaviridae"],
         0, "IBD virus is an un-enveloped Birnavirus with a bisegmented dsRNA genome that selectively targets and destroys dividing B-lymphocytes in the bursa of Fabricius."),
        ("Rabies virus (Lyssavirus) exhibits a characteristic morphology described under electron microscopy as:",
         ["Bullet-shaped (rhabdovirus)", "Brick-shaped", "Spherical with spikes", "Icosahedral"],
         0, "Rabies is an enveloped, negative-sense single-stranded RNA Rhabdovirus with a distinct cylindrical, bullet-shaped morphology measuring ~75 x 180 nm."),
        ("The primary surface glycoprotein on Rabies virus responsible for binding to nicotinic acetylcholine receptors and inducing neutralizing antibodies is:",
         ["G protein (Glycoprotein)", "M protein (Matrix)", "N protein (Nucleoprotein)", "L protein (Polymerase)"],
         0, "The trimeric G glycoprotein spikes project from the viral envelope and mediate cell receptor attachment; all protective rabies vaccines are based on G protein immunity."),
        ("Peste des Petits Ruminants (PPR / 'Goat Plague') is caused by a virus in the genus:",
         ["Morbillivirus (Family Paramyxoviridae)", "Aphthovirus", "Flavivirus", "Capripoxvirus"],
         0, "PPR virus is a Morbillivirus closely related to Rinderpest, Measles, and Canine Distemper, causing high fever, necrotic stomatitis, pneumonia, and severe diarrhea in sheep and goats."),
        ("Avian Influenza viruses belong to the family Orthomyxoviridae and are subtyped based on which two surface glycoproteins?",
         ["Hemagglutinin (H1 to H18) and Neuraminidase (N1 to N11)", "Spike (S) and Membrane (M)", "Fusion (F) and Attachment (G)", "Glycoprotein 120 and 41"],
         0, "Influenza A viruses are classified by their Hemagglutinin (HA) which binds sialic acid receptors and Neuraminidase (NA) which cleaves sialic acid to release progeny virions."),
        ("The sudden major genetic shift resulting from reassortment of segmented RNA genome fragments between different influenza strains is termed:",
         ["Antigenic Shift", "Antigenic Drift", "Lysogeny", "Transduction"],
         0, "Antigenic shift is genetic reassortment among segmented RNA genomes (8 segments) during co-infection, generating novel subtypes that trigger pandemics; point mutations cause drift."),

        # 91-120: Immunology & Diagnostic Serology
        ("The immunoglobulin isotype that possesses the highest concentration in normal adult bovine serum is:",
         ["IgG (specifically IgG1 in ruminants)", "IgM", "IgA", "IgE"],
         0, "IgG constitutes over 85-90% of circulating serum immunoglobulins in adult cattle, with IgG1 being selectively transported into colostrum before calving."),
        ("Which antibody class is a pentamer with 10 antigen-binding sites held together by a joining (J) chain, making it the most potent agglutinator?",
         ["IgM", "IgG", "IgA", "IgD"],
         0, "Secreted IgM is a 900 kDa pentamer; because of high valency (10 paratopes), it is 1,000 times more efficient than IgG at agglutinating bacteria and fixing complement."),
        ("The primary immunoglobulin isotype responsible for protecting mucosal surfaces (gut, respiratory tract, eyes, reproductive tract) is:",
         ["Secretory IgA (sIgA dimer)", "IgM", "IgG", "IgE"],
         0, "Dimeric IgA joined by a J chain acquires a protective secretory component as it traverses epithelial cells, rendering it resistant to proteolytic enzymes in mucosal secretions."),
        ("Type I Hypersensitivity (immediate anaphylaxis, atopy, urticaria) is mediated by which immunoglobulin binding to Fc-epsilon receptors on mast cells?",
         ["IgE", "IgM", "IgG", "IgA"],
         0, "IgE binds with high affinity to Fc-epsilon-RI on mast cells and basophils; allergen cross-linking triggers explosive degranulation of histamine, leukotrienes, and heparin."),
        ("Major Histocompatibility Complex (MHC) Class I molecules present endogenous peptide antigens to which subset of T-lymphocytes?",
         ["CD8+ Cytotoxic T cells", "CD4+ Helper T cells", "B cells", "NK cells"],
         0, "MHC Class I (expressed on all nucleated cells) presents viral or tumor peptides derived from the cytoplasm to CD8+ cytotoxic T lymphocytes."),
        ("MHC Class II molecules are expressed exclusively on professional antigen-presenting cells (dendritic cells, macrophages, B-cells) and present exogenous antigens to:",
         ["CD4+ Helper T lymphocytes (Th1, Th2, Th17)", "CD8+ Cytotoxic T cells", "Erythrocytes", "Neutrophils"],
         0, "MHC Class II presents peptides processed in endosomes/lysosomes to CD4+ T-helper cells, stimulating cytokine secretion and antibody class-switching."),
        ("The primary cytokine responsible for activating macrophages and stimulating cell-mediated Th1 immunity against intracellular pathogens is:",
         ["Interferon-gamma (IFN-gamma)", "Interleukin-4 (IL-4)", "Interleukin-10 (IL-10)", "Transforming Growth Factor-beta (TGF-beta)"],
         0, "IFN-gamma secreted by Th1 and NK cells is the premier macrophage-activating factor, stimulating phagolysosomal fusion and nitric oxide synthesis to kill intracellular bacilli."),
        ("In the Indirect Enzyme-Linked Immunosorbent Assay (Indirect ELISA), the enzyme (e.g. Horseradish Peroxidase) is conjugated to:",
         ["Anti-species secondary antibody", "The target pathogen antigen", "Primary serum antibody", "The plastic microplate well"],
         0, "In indirect ELISA, patient serum antibody binds plate-bound antigen, and an enzyme-labeled anti-species immunoglobulin (e.g. anti-bovine IgG) detects bound antibodies with a chromogen."),
        ("The standard 'Single Intradermal Tuberculin Test' (SITT) in cattle is read by measuring skin fold thickness increase at which anatomical site after 72 hours?",
         ["Caudal fold of the tail (mid-third)", "Neck crest", "Ear pinna", "Flank"],
         0, "The caudal fold test uses 0.1 ml of bovine PPD tuberculin injected intradermally in the caudal fold; swelling is palpated and measured with calipers at 72 +/- 6 hours."),
        ("A positive tuberculin skin test in cattle is an immunological manifestation of:",
         ["Type IV (Delayed-Type / Cell-Mediated) Hypersensitivity", "Type I (Anaphylactic) Hypersensitivity", "Type II (Cytotoxic) Hypersensitivity", "Type III (Immune-Complex) Hypersensitivity"],
         0, "Tuberculin reaction is a classic Type IV DTH response mediated by sensitized memory Th1 lymphocytes releasing cytokines (IFN-gamma) that recruit macrophages over 48-72 hours.")
    ]

    for idx, item in enumerate(raw_vmc[:120]):
        questions.append({
            "id": f"vmc_q_{idx+1:03d}",
            "domain": "veterinary_science",
            "year": "2nd_year",
            "subjectId": "vmc",
            "topic": "Veterinary Microbiology",
            "questionText": item[0],
            "options": item[1],
            "correctOptionIndex": item[2],
            "explanation": item[3],
            "difficulty": "Medium",
            "tags": ["Microbiology", "VMC"],
            "createdAt": 1773000000000 + idx
        })
    return questions

if __name__ == "__main__":
    qs = get_vmc_questions()
    print(f"Loaded {len(qs)} Veterinary Microbiology questions.")
