# scripts/data_vpy.py
# 120 High-Yield Questions for Veterinary Physiology (VPY)

def get_vpy_questions():
    questions = []

    raw_vpy = [
        # 1-25: Hematology & Cardiovascular
        ("The primary physiological pacemaker of the mammalian heart is the:",
         ["Sinoatrial (SA) node", "Atrioventricular (AV) node", "Bundle of His", "Purkinje fiber network"],
         0, "The SA node possesses the highest intrinsic rate of spontaneous diastolic depolarization (prepotential) due to funny channels (If), initiating the cardiac impulse."),
        ("On a standard electrocardiogram (ECG), the P wave represents:",
         ["Atrial depolarization", "Ventricular depolarization", "Ventricular repolarization", "Atrial repolarization"],
         0, "The P wave represents the spread of electrical depolarization across both atria, followed immediately by atrial systole."),
        ("On an ECG, ventricular repolarization is represented by the:",
         ["T wave", "P wave", "QRS complex", "PR interval"],
         0, "The T wave reflects ventricular myocardial repolarization (potassium efflux restoring resting membrane potential)."),
        ("The 'Frank-Starling law of the heart' states that:",
         ["Stroke volume increases in response to an increase in end-diastolic volume (preload)", "Heart rate is inversely proportional to blood pressure", "Cardiac output is independent of venous return", "Contractility decreases when stretched"],
         0, "The Frank-Starling mechanism dictates that increased ventricular filling (preload) optimizes sarcomere length, resulting in stronger force of myocardial contraction."),
        ("Which plasma protein is the principal contributor to blood colloid osmotic (oncotic) pressure?",
         ["Albumin", "Fibrinogen", "Gamma globulin", "Alpha-1 antitrypsin"],
         0, "Albumin accounts for approximately 75-80% of total plasma oncotic pressure (25 mmHg), preventing excessive fluid filtration into interstitial spaces."),
        ("The average life span of erythrocytes in the domestic dog is approximately:",
         ["110 to 120 days", "60 to 70 days", "140 to 160 days", "20 to 30 days"],
         0, "Canine red blood cells circulate for ~110-120 days before being sequestered and destroyed by macrophages in the spleen and liver."),
        ("The life span of erythrocytes in the domestic cat is notably shorter, averaging approximately:",
         ["68 to 70 days", "120 days", "150 days", "90 days"],
         0, "Feline erythrocytes have a much shorter circulating life span (~68-70 days) compared to dogs, cattle, and humans."),
        ("In birds, the mature circulating erythrocytes are uniquely:",
         ["Oval, biconvex, and nucleated", "Biconcave and enucleated", "Spherical and enucleated", "Crescent-shaped"],
         0, "Avian erythrocytes are oval, biconvex, and retain a prominent functional nucleus throughout their lifespan."),
        ("The main trigger for erythropoietin (EPO) synthesis and secretion by peritubular interstitial cells of the kidney is:",
         ["Renal tissue hypoxia", "Hyperglycemia", "Hypercalcemia", "Hypertension"],
         0, "Decreased oxygen tension (hypoxia) in renal tissue activates hypoxia-inducible factor (HIF-1alpha), stimulating erythropoietin secretion."),
        ("Which coagulation factor is also known as the 'Christmas factor'?",
         ["Factor IX", "Factor VIII", "Factor VII", "Factor X"],
         0, "Factor IX is the Christmas factor (antihemophilic factor B). Factor VIII is antihemophilic factor A, and Factor X is Stuart-Prower factor."),
        ("The 'extrinsic pathway' of blood coagulation is initiated by the release of:",
         ["Tissue factor (Thromboplastin / Factor III)", "Hageman factor (Factor XII)", "Fibrinogen (Factor I)", "Calcium ions solely"],
         0, "Tissue damage exposes subendothelial Tissue Factor (Factor III), which complexes with Factor VII in the presence of calcium to trigger the extrinsic pathway."),
        ("Erythrocyte sedimentation rate (ESR) is exceptionally rapid under normal physiological conditions in the healthy:",
         ["Horse", "Ox", "Sheep", "Dog"],
         0, "Equine erythrocytes form prominent rouleaux formations very rapidly due to high plasma fibrinogen and globulin interactions, producing a high baseline ESR."),
        ("In cattle, normal physiological ESR is:",
         ["Virtually zero (extremely slow)", "Very rapid like the horse", "Moderate", "Fluctuating daily"],
         0, "Bovine erythrocytes exhibit minimal or no rouleaux formation; thus, healthy cattle show an ESR near 0 mm/hour."),
        ("The sound produced by closure of the atrioventricular (mitral and tricuspid) valves is the:",
         ["First heart sound (S1 - 'Lub')", "Second heart sound (S2 - 'Dub')", "Third heart sound (S3)", "Fourth heart sound (S4)"],
         0, "S1 marks the onset of ventricular systole caused by sudden tension and vibrations following closure of the AV valves."),
        ("The second heart sound (S2) is caused by the closure of the:",
         ["Aortic and pulmonary semilunar valves", "Mitral and tricuspid valves", "Vena cava orifices", "Coronary sinus"],
         0, "S2 marks the end of ventricular systole and beginning of diastole, produced by turbulent blood deceleration upon aortic and pulmonic valve closure."),
        ("The 'Bainbridge reflex' describes the phenomenon where:",
         ["An increase in right atrial pressure/venous return causes a reflex increase in heart rate", "Elevated carotid sinus pressure decreases heart rate", "Deep inspiration slows the heart", "Pain produces bradycardia"],
         0, "Stretch of right atrial mechanoreceptors by increased venous return signals via vagal afferents to increase heart rate (Bainbridge reflex)."),
        ("The arterial baroreceptors responsible for short-term arterial blood pressure stabilization are located in the:",
         ["Carotid sinus and Aortic arch", "Jugular vein and Renal pelvis", "Femoral artery and Spleen", "Coronary artery"],
         0, "Carotid sinus (innervated by CN IX) and aortic arch (innervated by CN X) baroreceptors sense arterial wall stretch and regulate vascular tone."),
        ("Cardiopulmonary low-pressure volume receptors stimulate the secretion of which natriuretic peptide when atria stretch?",
         ["Atrial Natriuretic Peptide (ANP)", "Antidiuretic Hormone (ADH)", "Aldosterone", "Angiotensin II"],
         0, "Atrial stretch releases ANP, which promotes renal sodium and water excretion, decreases renin secretion, and reduces blood pressure."),
        ("Hematocrit or Packed Cell Volume (PCV) in a normal healthy adult cow is approximately:",
         ["24% to 46% (average ~30-35%)", "10% to 15%", "55% to 65%", "70% to 80%"],
         0, "The normal reference range for PCV in cattle is 24-46%, typically averaging around 32-35%."),
        ("The 'hematocrit paradox' or splenic reservoir effect allows which domestic animal to dramatically double its PCV during intense exercise?",
         ["Horse and Dog", "Cow and Sheep", "Pig and Rabbit", "Chicken and Duck"],
         0, "Horses and dogs have highly muscular spleens that store up to 30-50% of total RBC mass, released via sympathetic alpha-1 adrenergic contraction during sprinting."),
        ("Platelets (thrombocytes) in mammals are cell fragments derived from:",
         ["Megakaryocytes in the bone marrow", "Kupffer cells in the liver", "Erythroblasts", "Monocytes"],
         0, "Megakaryocytes undergo endomitosis and demarcate their cytoplasm to shed thousands of anucleated platelets into the circulation."),
        ("Von Willebrand Factor (vWF) is essential in hemostasis for mediating:",
         ["Platelet adhesion to subendothelial collagen", "Conversion of prothrombin to thrombin", "Cross-linking of fibrin monomers", "Lysis of blood clots"],
         0, "vWF acts as a molecular bridge between exposed subendothelial collagen and the platelet GP Ib-IX-V receptor complex during initial primary hemostasis."),
        ("Antithrombin III is a circulating anticoagulant that inhibits thrombin, whose activity is accelerated thousands-fold by:",
         ["Heparin", "Vitamin K", "Calcium", "Warfarin"],
         0, "Heparin binds to antithrombin III, inducing a conformational change that dramatically accelerates its inhibition of thrombin (Factor IIa) and Factor Xa."),
        ("Fibrinolysis (dissolution of the fibrin clot) is executed by which active serine protease?",
         ["Plasmin", "Thrombin", "Trypsin", "Pepsin"],
         0, "Tissue plasminogen activator (tPA) converts inactive plasminogen to active plasmin, which cleaves fibrin into fibrin degradation products (FDPs / D-dimers)."),
        ("The 'mean arterial pressure' (MAP) can be clinically approximated as:",
         ["Diastolic Pressure + 1/3 (Pulse Pressure)", "Systolic Pressure + Diastolic Pressure", "(Systolic - Diastolic) / 2", "Systolic Pressure / Diastolic Pressure"],
         0, "Since diastole occupies approximately two-thirds of the cardiac cycle, MAP = Diastolic BP + 1/3(Systolic - Diastolic BP)."),

        # 26-55: Ruminant Digestion & Metabolism
        ("The primary volatile fatty acid (VFA) produced in the rumen on high-forage (roughage) diets is:",
         ["Acetate (Acetic acid)", "Propionate (Propionic acid)", "Butyrate (Butyric acid)", "Lactate"],
         0, "On high-fiber roughage diets, cellulolytic and hemicellulolytic bacteria predominate, producing acetic acid (approx 65-70% of total VFAs)."),
        ("The primary volatile fatty acid that serves as the major glucogenic precursor in ruminants is:",
         ["Propionate (Propionic acid)", "Acetate", "Butyrate", "Isovalerate"],
         0, "Propionate is the only major VFA that undergoes net gluconeogenesis in the bovine liver, converted via methylmalonyl-CoA into succinyl-CoA."),
        ("The predominant volatile fatty acid metabolized directly by the ruminal epithelial wall during absorption is:",
         ["Butyrate (converted to beta-hydroxybutyrate)", "Acetate", "Propionate", "Formate"],
         0, "Over 80-90% of absorbed butyrate is metabolized by ruminal epithelial cells into beta-hydroxybutyrate (BHBA), a primary ketone body."),
        ("The normal physiological pH of the rumen liquor in a cow fed a balanced roughage-concentrate ration is:",
         ["6.2 to 6.8", "4.5 to 5.0", "7.5 to 8.2", "3.0 to 3.5"],
         0, "Rumen pH normally ranges between 6.2 and 6.8, maintaining an optimal environment for cellulolytic microbes and ciliate protozoa."),
        ("Acute ruminal acidosis occurs when the ruminal pH falls below:",
         ["5.0 (due to lactic acid accumulation)", "6.5", "7.0", "6.2"],
         0, "Ingestion of excessive soluble carbohydrates causes Streptococcus bovis and lactobacilli overgrowth, producing D- and L-lactic acid and plunging pH below 5.0."),
        ("The normal rate of primary (mixing) contractions in the adult bovine reticulorumen is approximately:",
         ["1 to 2 contractions per minute (or 3 in 2 minutes)", "10 per minute", "1 per hour", "15 per minute"],
         0, "Healthy adult cattle exhibit approximately 1 to 2 primary reticuloruminal motility cycles per minute, palpable over the left paralumbar fossa."),
        ("The secondary ruminal contraction (eructation cycle) initiates in the:",
         ["Caudoventral blind sac and caudal dorsal sac", "Reticulum", "Omasum", "Abomasum"],
         0, "The eructation contraction begins in the caudal dorsal sac, moving cranially to push the free gas bubble (CO2 and CH4) toward the cardia."),
        ("The 'reticular groove reflex' (esophageal groove reflex) in neonatal calves directs ingested milk directly into the:",
         ["Abomasum (bypassing rumen and reticulum)", "Omasum", "Rumen", "Duodenum"],
         0, "Afferent stimulation of the pharyngeal and oral receptors by suckling triggers vagal closure of the reticular groove lips, channeling milk straight to the abomasum."),
        ("The reticular groove closure reflex in adult small ruminants can be pharmacologically stimulated by oral dosing with:",
         ["Copper sulfate (CuSO4)", "Sodium chloride", "Magnesium sulfate", "Calcium carbonate"],
         0, "Oral administration of a small volume of 5% copper sulfate solution in sheep stimulates reflex closure of the esophageal groove within seconds."),
        ("The principal gases produced during ruminal fermentation are:",
         ["Carbon dioxide (60-70%) and Methane (30-40%)", "Oxygen and Nitrogen", "Hydrogen sulfide and Helium", "Ammonia and Argon"],
         0, "Ruminal gas consists of approximately 60-70% CO2, 30-40% CH4, with trace amounts of N2, O2, H2, and H2S."),
        ("Free-gas bloat (secondary tympany) in cattle is commonly caused by:",
         ["Physical or functional obstruction of the esophagus preventing eructation", "Stable foam formation", "Deficiency of saliva", "High rumen pH"],
         0, "Free-gas bloat results from failure of eructation due to esophageal obstruction (choke), tetanus, vagal indigestion, or lateral recumbency."),
        ("Frothy bloat (primary tympany) is triggered by:",
         ["Stable foam trapping fermentation gas in the rumen fluid (legume bloat)", "Esophageal foreign body", "Vagus nerve trauma", "Rumen flukes"],
         0, "Frothy bloat occurs on lush legume pastures (alfalfa, clover) containing soluble proteins and saponins that create a viscous, stable foam."),
        ("The primary nitrogen source synthesized by ruminal microbes into high-quality microbial protein is:",
         ["Ammonia (NH3)", "Uric acid", "Creatinine", "Bilirubin"],
         0, "Dietary true protein and non-protein nitrogen (NPN) are broken down into ammonia, which microbes utilize with carbohydrate carbon skeletons to make microbial protein."),
        ("Urea nitrogen is conserved in ruminants through the 'rumino-hepatic nitrogen cycle' via:",
         ["Salivary secretion and direct diffusion across the ruminal wall", "Renal filtration exclusively", "Sweat glands", "Bile ducts"],
         0, "Hepatic urea is recycled back into the rumen via saliva and direct trans-epithelial diffusion, preserving protein during low-nitrogen intake."),
        ("The abomasum in adult cattle functions physiologically as the:",
         ["True glandular stomach secreting HCl and pepsin", "Fermentation vat", "Water absorption organ", "Grinding mill"],
         0, "The abomasum is the glandular stomach analogous to the monogastric stomach, maintaining an acidic pH (~2-3) to digest microbial bodies and bypass protein."),
        ("The 'omasum' functions primarily in:",
         ["Absorption of water, electrolytes, and residual VFAs", "Acid digestion", "Methane production", "Fat emulsification"],
         0, "The extensive omasal laminae (manyplies) provide a massive surface area to absorb 60-70% of water and electrolytes entering from the reticulum."),
        ("The primary buffer entering the rumen to neutralize volatile fatty acids is:",
         ["Sodium bicarbonate and disodium phosphate in saliva", "Bile salts", "Gastric juice", "Pancreatic lipase"],
         0, "Bovine serous parotid saliva is rich in sodium bicarbonate (NaHCO3) and phosphate buffers, delivering over 100-150 liters of alkaline fluid daily."),
        ("Which microbial population in the rumen is responsible for breaking down plant cell wall cellulose?",
         ["Fibrobacter succinogenes, Ruminococcus albus, Ruminococcus flavefaciens", "Lactobacillus acidophilus", "Streptococcus bovis", "Escherichia coli"],
         0, "F. succinogenes, R. albus, and R. flavefaciens are the primary fibrolytic cellulolytic bacterial species in the rumen."),
        ("Defaunation refers to the experimental or practical elimination of which microbial group from the rumen?",
         ["Ciliate protozoa", "Cellulolytic bacteria", "Anaerobic fungi", "Bacteriophages"],
         0, "Defaunation is the removal of protozoa from the rumen, which often improves dietary protein utilization efficiency by reducing bacterial predation."),
        ("Rumen anaerobic fungi (e.g. Neocallimastix frontalis) play an essential role in:",
         ["Penetrating the cuticular barrier of coarse fibrous plant stems via rhizoids", "Synthesizing vitamin C", "Producing lactic acid", "Degrading toxic oxalates"],
         0, "Ruminal fungi use rhizoidal hyphae to physically crack tough lignified plant tissues, exposing internal cellulose to bacterial colonization."),
        ("The primary site of cellulose and hemicellulose digestion in the horse is the:",
         ["Cecum and large colon (hindgut fermentation)", "Stomach", "Duodenum", "Ileum"],
         0, "The horse is a hindgut fermenter whose massive cecum and ventral/dorsal colon harbor symbiotic microbes that ferment plant fiber into absorbable VFAs."),
        ("Unlike ruminants, horses cannot directly absorb microbial protein synthesized in their hindgut because:",
         ["Microbial protein is formed caudal to the stomach and small intestine, being excreted in feces", "Microbial protein is toxic to horses", "Equine colon absorbs only fat", "Horses lack proteases"],
         0, "Because microbial fermentation takes place in the large intestine distal to the small intestine (where amino acids are absorbed), equine microbial protein is lost in manure unless coprophagy occurs."),
        ("The daily production of saliva in an adult dairy cow can reach up to:",
         ["150 to 200 Litres", "10 to 15 Litres", "500 Litres", "2 to 5 Litres"],
         0, "A lactating dairy cow produces 150-200 liters of saliva daily, providing the continuous aqueous buffer needed to maintain ruminal pH."),
        ("Vagal indigestion (Hoflund syndrome) Type II is characterized by:",
         ["Omasal transport failure", "Failure of eructation", "Pyloric stenosis", "Esophageal rupture"],
         0, "Hoflund Type II vagal indigestion involves failure of transport through the reticulo-omasal orifice, leading to progressive bilateral abdominal enlargement ('papple shape')."),
        ("The primary stimulus for the initiation of rumination (chewing the cud) is:",
         ["Tactile friction of coarse roughage particles against the cranial rumen and reticular mucosa", "High rumen pH", "Abomasal distension", "Hypoglycemia"],
         0, "Coarse fibrous feed scratching against the mucosa near the cardia triggers sensory vagal afferents that initiate the regurgitation reflex of rumination."),

        # 56-80: Respiration, Excretion & Neuro-Muscle
        ("Pulmonary surfactant, which reduces alveolar surface tension and prevents alveolar collapse, is synthesized by:",
         ["Type II pneumocytes (Granular alveolar cells)", "Type I pneumocytes", "Alveolar macrophages", "Clara cells"],
         0, "Type II alveolar epithelial cells produce pulmonary surfactant composed predominantly of dipalmitoylphosphatidylcholine (DPPC) and surfactant apoproteins."),
        ("The primary chemical driver of physiological ventilation under resting conditions is the arterial partial pressure of:",
         ["Carbon dioxide (PaCO2)", "Oxygen (PaO2)", "Nitrogen (PaN2)", "Carbon monoxide"],
         0, "Central chemoreceptors on the ventrolateral medulla respond to changes in brain ECF pH driven by arterial PaCO2, acting as the primary regulator of ventilation."),
        ("The 'Bohr effect' describes the physiological shift of the oxygen-hemoglobin dissociation curve:",
         ["To the right in the presence of elevated CO2, H+ (acidosis), and temperature", "To the left at low pH", "Upward in anemia", "Downward in alkalosis"],
         0, "The Bohr effect shifts the Hb-O2 dissociation curve to the right in metabolically active tissues, facilitating oxygen offloading to peripheral cells."),
        ("Avian respiration is unique among vertebrates because airflow through the parabronchi is:",
         ["Unidirectional during both inspiration and expiration", "Bidirectional like mammals", "Tidal", "Intermittent"],
         0, "The avian respiratory system uses air sacs as non-vascular bellows to circulate air unidirectionally through the paleopulmonic parabronchi during both phases."),
        ("How many respiratory cycles (inspiration + expiration) are required for a single parcel of air to pass completely through the avian respiratory system?",
         ["Two complete respiratory cycles", "One cycle", "Four cycles", "Three cycles"],
         0, "It takes two complete respiratory cycles (Cycle 1: trachea -> caudal sacs -> lungs; Cycle 2: lungs -> cranial sacs -> trachea -> exit) for air to traverse the bird."),
        ("The primary site of sodium and water reabsorption in the mammalian nephron is the:",
         ["Proximal convoluted tubule (65-70%)", "Distal convoluted tubule", "Collecting duct", "Ascending thin limb of Henle"],
         0, "The proximal convoluted tubule obligatorily reabsorbs approximately 65-70% of filtered water, sodium, chloride, and 100% of glucose and amino acids."),
        ("The 'countercurrent multiplier system' responsible for generating a hypertonic medullary osmotic gradient is located in the:",
         ["Loop of Henle", "Glomerulus", "Afferent arteriole", "Proximal tubule"],
         0, "The loop of Henle (specifically the thick ascending limb actively pumping Na-K-2Cl into the interstitium) functions as a countercurrent multiplier."),
        ("Antidiuretic Hormone (ADH / Vasopressin) increases water reabsorption by inserting which water channels into collecting duct principal cells?",
         ["Aquaporin-2 (AQP-2)", "Aquaporin-1", "GLUT-4", "Sodium-potassium pump"],
         0, "ADH binds to basolateral V2 receptors, triggering cAMP-mediated exocytic insertion of Aquaporin-2 water channels into the apical membrane of collecting ducts."),
        ("Aldosterone acts primarily on which nephron segment to promote sodium reabsorption and potassium/hydrogen excretion?",
         ["Late distal convoluted tubule and cortical collecting duct principal cells", "Proximal tubule", "Glomerulus", "Bowman capsule"],
         0, "Aldosterone enters principal cells to upregulate basolateral Na+/K+ ATPase and apical ENaC sodium channels, conserving Na+ and excreting K+."),
        ("Renin is secreted by the juxtaglomerular cells in response to:",
         ["Decreased renal arterial perfusion pressure or decreased NaCl delivery to macula densa", "Hypertension", "Hypernatremia", "Increased blood volume"],
         0, "Renin release is triggered by decreased renal perfusion pressure, sympathetic renal nerve stimulation (beta-1), or low NaCl delivery sensed by macula densa."),
        ("The enzyme that converts Angiotensin I into the potent vasoconstrictor Angiotensin II is:",
         ["Angiotensin-Converting Enzyme (ACE) located primarily in pulmonary endothelial cells", "Renin", "Pepsin", "Kallikrein"],
         0, "ACE is an endothelial brush border ectoenzyme concentrated in the capillary bed of the lungs that hydrolyzes the decapeptide Ang I into the octapeptide Ang II."),
        ("The 'renal threshold' for glucose in the domestic dog is approximately:",
         ["180 mg/dL (10 mmol/L)", "80 mg/dL", "350 mg/dL", "500 mg/dL"],
         0, "When blood glucose exceeds ~180 mg/dL in dogs, tubular maximum (Tm) for glucose reabsorption in the PCT is exceeded, resulting in glucosuria."),
        ("In the domestic cat, the renal threshold for glucose is significantly higher, approximately:",
         ["280 to 300 mg/dL", "100 mg/dL", "150 mg/dL", "450 mg/dL"],
         0, "Feline kidneys have a higher tubular capacity for glucose, exhibiting glucosuria only when blood glucose exceeds ~280-300 mg/dL."),
        ("The primary nitrogenous excretory waste in birds and terrestrial reptiles is:",
         ["Uric acid", "Urea", "Ammonia", "Hippuric acid"],
         0, "Birds are uricotelic; they convert toxic ammonia into insoluble uric acid, excreted as a white paste without requiring water, conserving body hydration."),
        ("The resting membrane potential (RMP) of typical mammalian excitable cells is predominantly determined by the diffusion potential of:",
         ["Potassium ions (K+)", "Sodium ions (Na+)", "Calcium ions (Ca2+)", "Chloride ions (Cl-)"],
         0, "Because resting neuronal and muscle membranes possess numerous open potassium leak channels, the RMP (-70 to -90 mV) approaches the Nernst potential for K+."),
        ("The rapid upstroke (depolarization) of the action potential in a nerve fiber is caused by the sudden opening of:",
         ["Voltage-gated Sodium (Na+) channels", "Voltage-gated Potassium channels", "Calcium ATPase", "Chloride channels"],
         0, "Once the threshold potential is reached, voltage-gated Na+ channels rapidly activate, causing an explosive inward influx of sodium."),
        ("The neurotransmitter released at the mammalian neuromuscular junction (motor endplate) is:",
         ["Acetylcholine (ACh)", "Norepinephrine", "Dopamine", "GABA"],
         0, "Somatic motor neurons release acetylcholine, which binds to nicotinic acetylcholine receptors (nAChRs) on the muscle motor endplate."),
        ("In skeletal muscle, the calcium sensor protein on the actin thin filament that binds calcium to initiate contraction is:",
         ["Troponin C", "Tropomyosin", "Myosin light chain", "Actinin"],
         0, "Calcium released from the sarcoplasmic reticulum binds to Troponin C, shifting tropomyosin away from the myosin-binding sites on actin."),
        ("Rigor mortis occurs after death because:",
         ["ATP depletion prevents detachment of myosin heads from actin filaments", "Calcium is completely exhausted", "Lactic acid dissolves actin", "Troponin is degraded"],
         0, "Without ATP production after death, the myosin cross-bridge cannot dissociate from actin, locking muscles in a stiff state termed rigor mortis."),
        ("Saltatory conduction of action potentials in myelinated axons occurs from:",
         ["Node of Ranvier to Node of Ranvier", "Schwann cell to Schwann cell", "Soma to dendrite", "Synapse to nucleus"],
         0, "Myelin acts as an electrical insulator; voltage-gated sodium channels are concentrated at the nodes of Ranvier, allowing action potentials to jump rapidly."),

        # 81-120: Endocrinology & Reproduction
        ("The 'milk ejection reflex' (milk letdown) is mediated neurohormonally by the release of which hormone from the neurohypophysis?",
         ["Oxytocin", "Prolactin", "Growth Hormone", "Progesterone"],
         0, "Teat stimulation triggers sensory spinothalamic impulses to the supraoptic and paraventricular nuclei of the hypothalamus, releasing oxytocin to contract myoepithelial cells."),
        ("The hormone responsible for the initiation and maintenance of lactogenesis (milk synthesis) within alveolar epithelial cells is:",
         ["Prolactin", "Oxytocin", "Estrogen", "Luteinizing Hormone"],
         0, "Prolactin secreted by anterior pituitary lactotrophs stimulates the transcription of milk protein genes (casein, alpha-lactalbumin) and enzyme machinery."),
        ("The average duration of the estrous cycle in the domestic cow is:",
         ["21 days (range 18-24 days)", "28 days", "14 days", "60 days"],
         0, "The bovine estrous cycle averages 21 days (polyestrous year-round), comprising proestrus, estrus (~12-18 hours), metestrus, and diestrus."),
        ("Ovulation in the cow uniquely occurs:",
         ["10 to 12 hours AFTER the end of estrus (standing heat)", "During standing heat", "Before standing heat begins", "At the onset of proestrus"],
         0, "Unlike mares, ewes, and sows which ovulate during heat, the cow is unique in ovulating approximately 10-12 hours after standing heat ends (metestrus)."),
        ("The 'LH surge' (preovulatory luteinizing hormone surge) is directly stimulated by positive feedback from high levels of:",
         ["Estradiol-17beta", "Progesterone", "Inhibin", "Cortisol"],
         0, "When the dominant follicle reaches preovulatory size, sustained high estradiol concentrations switch from negative to positive feedback on GnRH/LH secretion."),
        ("The primary luteolytic hormone in domestic farm animals that induces regression of the corpus luteum is:",
         ["Prostaglandin F2alpha (PGF2alpha)", "Progesterone", "Prolactin", "Relaxin"],
         0, "Uterine endometrium secretes pulsatile PGF2alpha in the late luteal phase, which reaches the ipsilateral ovary via the ovarian artery countercurrent mechanism to destroy the CL."),
        ("Maternal recognition of pregnancy (MRP) in the cow is signaled by the conceptus secreting:",
         ["Bovine Interferon-tau (bIFN-tau)", "Estrogen", "Equine chorionic gonadotropin", "Human chorionic gonadotropin"],
         0, "The elongating bovine blastocyst secretes Interferon-tau between days 15-17, which suppresses uterine oxytocin receptors and prevents pulsatile PGF2alpha release."),
        ("Maternal recognition of pregnancy in the pig (sow) is signaled by conceptus secretion of:",
         ["Estrogen (Estradiol-17beta)", "Interferon-tau", "Progesterone", "PGF2alpha"],
         0, "Pig embryos secrete estradiol between days 11-12, which redirects PGF2alpha secretion into the uterine lumen (exocrine direction) where it is degraded."),
        ("Induced (reflex) ovulation upon coital stimulation occurs naturally in which domestic species?",
         ["Cat (Queen) and Camelids", "Cow and Ewe", "Mare and Sow", "Bitch"],
         0, "The domestic cat, camelids (camel, llama, alpaca), and ferrets are induced ovulators; mechanical stimulation of the cervix during copulation triggers neuroendocrine LH release."),
        ("The 'bitch' (female dog) is classified endocrinologically as a:",
         ["Monoestrous, non-seasonal animal with obligatory pseudopregnancy in diestrus", "Seasonally polyestrous long-day breeder", "Continuous polyestrous animal", "Induced ovulator"],
         0, "The bitch undergoes 1 or 2 estrous cycles per year (monoestrous); regardless of pregnancy, the CL persists for ~60 days with high progesterone."),
        ("The hormone responsible for maintaining myometrial quiescence and pregnancy in all domestic animals is:",
         ["Progesterone", "Estrogen", "Oxytocin", "Prostaglandin E2"],
         0, "Progesterone ('pro-gestation') synthesized by the corpus luteum and/or placenta inhibits uterine myometrial contractions and stimulates endometrial gland secretion."),
        ("Equine Chorionic Gonadotropin (eCG / PMSG) is produced by specialized fetal structures termed:",
         ["Endometrial cups", "Caruncles", "Cotyledons", "Amniotic plaques"],
         0, "Between days 35-120 of equine gestation, invading fetal trophoblast cells form endometrial cups in the mare uterus, secreting eCG with potent LH/FSH activity to form accessory CLs."),
        ("Which hormone is synthesized by thyroid parafollicular (C cells) and acts to lower plasma calcium concentration?",
         ["Calcitonin", "Parathyroid Hormone (PTH)", "Thyroxine (T4)", "Vitamin D3 (Calcitriol)"],
         0, "Calcitonin is released in response to hypercalcemia; it inhibits osteoclast-mediated bone resorption and renal tubular calcium reabsorption."),
        ("Parathyroid Hormone (PTH) acts to raise serum ionized calcium by:",
         ["Stimulating osteoclasts, increasing renal tubular Ca reabsorption, and activating 1-alpha-hydroxylase", "Inhibiting bone breakdown", "Excreting calcium in urine", "Suppressing Vitamin D"],
         0, "PTH restores normocalcemia by mobilizing calcium from bone, conserving calcium in the distal nephron, and stimulating renal synthesis of active calcitriol."),
        ("Parturient paresis (Milk Fever) in high-producing dairy cows is fundamentally caused by acute:",
         ["Hypocalcemia", "Hypoglycemia", "Hypokalemia", "Hypermagnesemia"],
         0, "The sudden drain of calcium into colostrum at the onset of lactation outpaces osteoclast mobilization and intestinal absorption, causing acute hypocalcemia and flaccid paralysis."),
        ("Which hormone is secreted by the pineal gland in response to darkness and regulates seasonal breeding in sheep and horses?",
         ["Melatonin", "Serotonin", "Dopamine", "Prolactin"],
         0, "Melatonin is synthesized exclusively during dark hours; short days in autumn increase melatonin, stimulating GnRH in short-day breeders (sheep/goats) and inhibiting it in long-day breeders (horses)."),
        ("Ewe and doe are classified reproductively as:",
         ["Seasonally polyestrous short-day breeders (fall breeders)", "Seasonally polyestrous long-day breeders (spring breeders)", "Continuous polyestrous", "Monoestrous"],
         0, "Sheep and goats are short-day breeders that cycle in autumn and winter when day length shortens and melatonin secretion increases."),
        ("The mare is classified reproductively as a:",
         ["Seasonally polyestrous long-day breeder (spring/summer breeder)", "Short-day breeder", "Monoestrous", "Induced ovulator"],
         0, "Horses cycle during long days of spring and summer when decreasing melatonin unlocks the hypothalamic-pituitary-ovarian axis."),
        ("The primary hormone responsible for secondary male sex characteristics and spermatogenesis is:",
         ["Testosterone", "Dihydrotestosterone only", "Estradiol", "Luteinizing Hormone"],
         0, "Testosterone produced by Leydig cells in response to LH stimulates Sertoli cells, accessory sex glands, spermatogenesis, and male behavior."),
        ("Inhibin is secreted by Sertoli cells in the male and granulosa cells in the female to selectively suppress:",
         ["Follicle-Stimulating Hormone (FSH)", "Luteinizing Hormone (LH)", "Progesterone", "Oxytocin"],
         0, "Inhibin acts directly on anterior pituitary gonadotrophs to downregulate FSH synthesis and secretion via negative feedback."),
        ("The thyroid gland predominantly secretes which form of thyroid hormone into the circulation?",
         ["Thyroxine (T4) (over 90%)", "Triiodothyronine (T3)", "Reverse T3", "Diiodotyrosine"],
         0, "The thyroid gland secretes ~90-95% T4, which is converted in peripheral tissues by 5'-deiodinase into the biologically active T3."),
        ("Cortisol is synthesized and released by which specific zone of the adrenal cortex?",
         ["Zona fasciculata", "Zona glomerulosa", "Zona reticularis", "Adrenal medulla"],
         0, "The zona fasciculata (middle and widest cortical layer) produces glucocorticoids (cortisol and corticosterone) under ACTH stimulation."),
        ("The adrenal medulla synthesizes catecholamines (epinephrine and norepinephrine) from the amino acid precursor:",
         ["Tyrosine", "Tryptophan", "Methionine", "Histidine"],
         0, "Tyrosine is converted by tyrosine hydroxylase to L-DOPA, then to dopamine, norepinephrine, and methylated to epinephrine by PNMT."),
        ("Glucagon is secreted by which endocrine cells of the pancreatic islets?",
         ["Alpha cells", "Beta cells", "Delta cells", "PP cells"],
         0, "Pancreatic alpha cells secrete glucagon during hypoglycemia, stimulating hepatic glycogenolysis and gluconeogenesis to elevate blood glucose."),
        ("The hormone Somatostatin, which exerts inhibitory paracrine control over insulin and glucagon, is secreted by:",
         ["Delta cells of pancreatic islets", "Beta cells", "Alpha cells", "Acinar cells"],
         0, "Delta cells synthesize somatostatin (GHIH), which inhibits the secretion of insulin, glucagon, gastrin, and GH."),
        ("Growth Hormone (GH / Somatotropin) exerts its growth-promoting actions on long bones primarily via liver production of:",
         ["Insulin-like Growth Factor 1 (IGF-1 / Somatomedin C)", "Insulin", "Thyroxine", "Calcitonin"],
         0, "GH stimulates hepatocytes to synthesize and secrete IGF-1, which acts on chondrocytes at epiphyseal plates to stimulate linear skeletal growth."),
        ("The duration of spermatogenesis in the bull from spermatogonium to mature spermatozoon is approximately:",
         ["61 days", "21 days", "90 days", "30 days"],
         0, "Bovine spermatogenesis spans ~61 days, followed by another 8-11 days of epididymal maturation and transport."),
        ("The acrosome of the spermatozoon is a modified lysosome derived from the:",
         ["Golgi apparatus", "Mitochondria", "Centriole", "Endoplasmic reticulum"],
         0, "During spermiogenesis, the Golgi apparatus coalesces over the anterior two-thirds of the sperm nucleus to form the acrosomal cap containing hyaluronidase and acrosin."),
        ("The primary energy substrate utilized by bovine spermatozoa for motility in seminal plasma is:",
         ["Fructose", "Glucose", "Sucrose", "Lactose"],
         0, "Seminal vesicles secrete large amounts of fructose, which serves as the primary glycolytic energy substrate for sperm flagellar motility in the female tract."),
        ("The 'thermoregulatory mechanism' of the mammalian testis maintains testicular temperature:",
         ["2 to 6 degrees C below core body temperature", "Equal to core body temperature", "2 degrees C above body temperature", "10 degrees C below body temperature"],
         0, "Normal spermatogenesis requires a temperature 2-6 degrees C cooler than core body heat, maintained by the pampiniform plexus countercurrent heat exchanger and dartos/cremaster muscles.")
    ]

    for idx, item in enumerate(raw_vpy[:120]):
        questions.append({
            "id": f"vpy_q_{idx+1:03d}",
            "domain": "veterinary_science",
            "year": "1st_year",
            "subjectId": "vpy",
            "topic": "Physiology & Endocrinology",
            "questionText": item[0],
            "options": item[1],
            "correctOptionIndex": item[2],
            "explanation": item[3],
            "difficulty": "Medium",
            "tags": ["Physiology", "VPY"],
            "createdAt": 1773000000000 + idx
        })
    return questions

if __name__ == "__main__":
    qs = get_vpy_questions()
    print(f"Loaded {len(qs)} Veterinary Physiology questions.")
